### ISSUE TITLE
[Tree][Closure] - Entity Inheritance can break closure-trees on persist.

### ISSUE THREAD

**Issue by timdev** [doctrine-extensions/DoctrineExtensions#1030]
I'm working on an application that deals with inventory locations, as well as other kind of "containers" for inventory (some physical, like a carton or shipping container, some virtual, like a company).

So I've got a superclass "Container", and a subclass "Location" (which is just a subclass of container with a couple of extra properties).

Closure table breaks (in EntityManager::flush()) when I do something like this:

``` php

$em->beginTransaction();

$ss = new Location();
$ss->setIdentifier('Shipment Staging Area');
$em->persist($ss);

$picking = new Location();
$picking->setIdentifier('Picking Area');
$em->persist($picking);

$warehouse = new Location();
$warehouse->setIdentifier('Warehouse');
$em->persist($warehouse);

$universe = new Container();
$universe->setIdentifier('Universe');
$em->persist($universe);

$warehouse->addContainer($picking);
$warehouse->addContainer($ss);
$universe->addContainer($warehouse);

$em->flush();
```

resulting in:

```
Doctrine\ORM\ORMInvalidArgumentException
 Binding entities to query parameters only allowed for entities that have an identifier.
```

The problem is that the UoW ["chunks" inserts by class](https://github.com/doctrine/doctrine2/blob/a03c8da683ee6b0e8363b022b936cdd956513ecf/lib/Doctrine/ORM/UnitOfWork.php#L349), and that's where postPersist events [are triggered](https://github.com/doctrine/doctrine2/blob/a03c8da683ee6b0e8363b022b936cdd956513ecf/lib/Doctrine/ORM/UnitOfWork.php#L1001).

This means that when postPersist fires for Locations that are children of "Universe" (a container, not a location), "Universe" hasn't been persisted yet, and thus has no identifier.

Strategy\ORM\Closure [expects](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Closure.php#L260) all nodes have been persisted on postPersist.  But if you've got subclasses, a node's parent might not be persisted yet, since it's going to persisted on a future iteration of [UnitOfWork::executeInserts($class)](https://github.com/doctrine/doctrine2/blob/a03c8da683ee6b0e8363b022b936cdd956513ecf/lib/Doctrine/ORM/UnitOfWork.php#L349)

---

Unfortunately, I don't see a way around this yet.  If anyone has a pointer, I'd be happy to put together a PR.  But as of yet, I don't see a solution.  I had originally thought onFlush would happen later, but doesn't appear true.

The most obvious solution would be for Doctrine itself to "chunk" by the highest entity class in the inheritance hierarchy.  But I'm not sure what side-effects such a change might have, since I'm not sure about the reasoning behind that "chunking" to begin with.

**Comment by mjpvandenberg** [comment]
The workaround is to flush after each persist. 
I think changing the postPersist event to postFlush would fix this problem.
