### ISSUE TITLE
[Timestampable] XML mapping is not support array of values for the field.

### ISSUE THREAD

**Issue by yethee** [doctrine-extensions/DoctrineExtensions#1088]
#776, this PR adds ability to set array of tracking fields, but the XML driver is not support this feature.

From the driver [code](https://github.com/Atlantic18/DoctrineExtensions/blob/9554a8123cbc79c7bc27eaea2b5423268a27d8bf/lib/Gedmo/Timestampable/Mapping/Driver/Xml.php#L72-L76):

``` php
$trackedFieldAttribute = $this->_getAttribute($data, 'field');
$valueAttribute = $this->_isAttributeSet($data, 'value') ? $this->_getAttribute($data, 'value' ) : null;
if (is_array($trackedFieldAttribute) && null !== $valueAttribute) {
    throw new InvalidMappingException("Timestampable extension does not support multiple value changeset detection yet.");
}
```

Method `_getAttribute` always returns a value of the string type.

**Comment by mathewrapid** [comment]
ping

**Comment by l3pp4rd** [comment]
maybe you can contribute?
