### ISSUE TITLE
[Translatable] TranslationWalker turns fallback off when hydratation mode is scalar

### ISSUE THREAD

**Issue by DaveLister007** [doctrine-extensions/DoctrineExtensions#1122]
When executing query with TranslationWalker and hydrating it into array:

``` php
$query = .. create query..
$query->setHint(
               \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
                ' Gedmo\Translatable\Query\TreeWalker\TranslationWalker'
            );
$query->setHint(
                \Gedmo\Translatable\TranslatableListener::HINT_FALLBACK,
                1 // fallback to default values in case if record is not translated
            );
$res = $query->getScalarResult()
```

Fallback is not used, even though the hint specify it to. Reason of this is TranslationWalker::needsFallback method:

``` php
    /**
     * Checks if translation fallbacks are needed
     *
     * @return boolean
     */
    private function needsFallback()
    {
        $q = $this->getQuery();
        $fallback = $q->getHint(TranslatableListener::HINT_FALLBACK);
        if (false === $fallback) {
            // non overrided
            $fallback = $this->listener->getTranslationFallback();
        }
        return (bool)$fallback
            && $q->getHydrationMode() !== Query::HYDRATE_SCALAR
            && $q->getHydrationMode() !== Query::HYDRATE_SINGLE_SCALAR;
    }
```

Is there particular reason why queries with hydratation mode scalar (ie. array) have fallback diasabled? There is no way of overriding this behavior because needsFallback method is private.

**Comment by xxccdef** [comment]
I would like to reiterate on this one. I'm using fallback translations together with Doctrine's Paginator. To get correct results when toMany association is joined, the Paginator does three things:

Perform a Count query using DISTINCT keyword.
Perform a Limit Subquery with DISTINCT to find all ids of the entity in from on the current page.
Perform a WHERE IN query to get all results for the current page.

The count query is executed like this:

    $ids = array_map('current', $subQuery->getScalarResult());

As you can see, it is using scalar hydration which returns incorrect paginated results when filtering, ordering by a translated field. Unfortunatelly Doctrine guys have made it really difficult to extend the Paginator, therefore at the moment I'm just using their code in my own namespace with this patch:

    $ids = array_map('current', $subQuery->getArrayResult());

This makes updating Doctrine really brittle. Does anyone else has this problem and maybe found a workaround?
