### ISSUE TITLE
Softdelete DQL not supported when deleting?

### ISSUE THREAD

**Issue by ghost** [doctrine-extensions/DoctrineExtensions#1125]
```
$em ->createQuery('delete from Test a where a.id = :id')
->setParameter('id', $id)
->execute();
```

this results in:

```
DELETE FROM Test WHERE (a_id = ?) AND (Test.deletedAt IS NULL) ["164"]
```

Shouldnt this be something like "update test set deletedAt = now()"? Removing through the $em and flushing does it correctly.

"symfony/symfony": "~2.5",
"doctrine/orm": "~2.2,>=2.2.3",
"doctrine/doctrine-bundle": "~1.2",
"stof/doctrine-extensions-bundle": "~1.1@dev",
"gedmo/doctrine-extensions": "~2.3.1"

**Comment by fyrye** [comment]
To resolve the issue use a Query Hint as explained in the [documentation](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/softdeleteable.md).

```php
$query = $em ->createQuery('delete from Test a where a.id = :id')
   ->setParameter('id', $id);

//php >= 5.5
$query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
           \Gedmo\SoftDeleteable\Query\TreeWalker\SoftDeleteableWalker::class);
/**
 * //for php < 5.5
 * $query->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
 *          '\Gedmo\SoftDeleteable\Query\TreeWalker\SoftDeleteableWalker');
 */

$query->execute();
```

Results in

```sql
UPDATE a.deletedAt = now() WHERE a.id = ?
```
