### ISSUE TITLE
[Tree] childrenHierarchy not returning the results sorted the same way in different requests

### ISSUE THREAD

**Issue by iulian-gioada** [doctrine-extensions/DoctrineExtensions#1128]
Hello,

We are working currently on a project that uses the ClosureTreeRepository class. We make two different requests for childrenHierarchy one with $node = null and one with a certain node set. We are using the childSort option and it's the same in the both cases.

The problem is that the sort order of the result set is different for the same node in the two different scopes.

Example:

We have three level 1 nodes, each with three children each with a position defined which we are using for the child sort.

```
a        
-a1 (1)
-a2 (2)
-a3 (2)

b
-b1 (1)
-b2 (2)
-b3 (3)

c
-c1 (1)
-c2 (2)
-c3 (3)
```

In the case we are requesting the childrenHierarchy for the node "a" we get this:

```
a
-a1
-a2
-a3
```

but in the case we are requesting for the whole tree hierarchy we get this (I'm listing only the a category):

```
a
-a1
-a3
-a2
```

The problem is that the result set doesn't have a primary key that would act as a fallback sort field.

We solved the problem by adding an extra field for sorting (name) as a fallback in our extending class in the getNodesHierarchyQueryBuilder function.

Can you please add an option to sort by multiple fields, or maybe add a default sort field?

Regards,
Iulian

**Comment by emovere** [comment]
> We solved the problem by adding an extra field for sorting (name) as a fallback in our extending class in the getNodesHierarchyQueryBuilder function.

How have you done this?
I'am trying to add a extra field to my function, please take a look:
https://github.com/Atlantic18/DoctrineExtensions/issues/2093

But I'am getting an error.
