### ISSUE TITLE
Timestampable does not work with ORM and PostgreSQL database

### ISSUE THREAD

**Issue by reypm** [doctrine-extensions/DoctrineExtensions#1140]
I added support for `Timestampable` in my entity as follow: `use Gedmo\Timestampable\Traits\TimestampableEntity;`. I have updated my DB by running `doctrine:schema:update --force` but any time I try to insert a new record I get this message:

> SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "createdat" violates not-null constraint

Why? I'm using latest Symfony 2.5.3 and PostgreSQL 9.2.9. This is the complete error:

> An exception occurred while executing 'INSERT INTO usuarios_externos.usuarios (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, 
> roles, credentials_expired, credentials_expire_at, id, persona, correo_alternativo, telefono, telefono_movil, fax, pagina_web, direccion, deletedAt, createdAt, updatedAt, pais_id, estado_id, municipio_id, ciudad_id, parroquia_id) VALUES (?, 
> ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["reynier", "reynier", "reynierpm@gmail.com", "reynierpm@gmail.com", "false", "hhm95if1uog88koggos48csk48k0w80", 
> "sVzbTOHgZzhU92zPHBFsVG3GqV+DO5xvXxvNdC5\/GVJ\/Hnvlm8rBsNDsIgPKYXdZ4NcnONqXnrOB6UR+lAluAw==", null, "false", "false", null, null, null, "a:0:{}", "false", null, 3, "true", "reynierpm1@gmail.com", "021245678999", "", "", "", "sadasdasd", 
> null, null, null, 23, 1, 1, 1, 22]

Any advice?

**Comment by vinigarcia87** [comment]
Thanks! This save my life!
This info should be on documentation!
