### ISSUE TITLE
NestedSet::Recover() method in nestedSet does not calculate level

### ISSUE THREAD

**Issue by birko** [doctrine-extensions/DoctrineExtensions#1164]
When I used recover function on my NestedSet table, column representing the level of node in tree was not recalculated correctly.
Probably there is missing a variable setter in the method.

Edit: probably the verify method will have a bug too with wrong level numbers

**Comment by stephanvierkant** [comment]
+1

**Comment by stephanvierkant** [comment]
Is this related to #1568?

**Comment by birko** [comment]
I think yes, it is
