### ISSUE TITLE
[Tree] NestedTreeRpository verifyTree fails

### ISSUE THREAD

**Issue by chovan-zoltan** [doctrine-extensions/DoctrineExtensions#1172]
Scenario:
I create a node in an entity thats using the tree behaviour. Then I run the verify() method called from the NestedTreeRepository class. This returns with an error saying `"node [{$id}] has invalid left or right values"` This happens because in the line 825 there is the following if statement:

```
if (!$right || !$left)
```

The statement in the if will always be true for the node that has 0 for left or right index, hence the verification will fail eventhough there is nothing wrong with the tree. 
My recommendation would be that either this should be verified differently or the left/right indexing should start from 1.

**Comment by Canser** [comment]
I have a problem with this. lft sets to -1 and right sets to 0 for first data. Please see my question here:

http://stackoverflow.com/questions/27739610/gedmo-tree-starts-from-1-negative-one

**Comment by symfonyaml** [comment]
@chovan-zoltan @Canser Hi guys, what did you do to fix this ? I have the same issue.
```php
// $right = 0 and $left = -1
if (!$right || !$left)
```
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Tree/Entity/Repository/NestedTreeRepository.php#L1007
Thanks
