### ISSUE TITLE
Uploadable -> Unable to create directory && Directory is not writable

### ISSUE THREAD

**Issue by khalilst** [doctrine-extensions/DoctrineExtensions#1180]
Hello
I'm using Uploadable behavoir according to its documentation in Symfony 2.5.
When for the first time (directory doesn't exist) I want to execute UpdateAction an error raised with this message
     Directory "%kernel.root_dir%/../uploads/" does is not writable. 
But when it creates uploads directory in web folder.
Second time (directory exists), it raised another error with this message:
      Unable to create "%kernel.root_dir%/../uploads/" directory. 
I did a trace on Gedmo/Uploadable/Mapping/Validator.php, validatePath function: 
is_dir($path) returns 0 even if file exists
@mkdir($path, 0777, true) returns 0 if file exists
is_writable always returns 0. (chmod 777 has no effect, Symfony documentation about file permission has no effect).
So I replace below lines in validatePath from this:

```
    if (!is_dir($path) && !@mkdir($path, 0777, true)) {
        throw new UploadableInvalidPathException(sprintf('Unable to create "%s" directory.',
            $path
        ));
    }

    if (!is_writable($path)) {
        throw new UploadableCantWriteException(sprintf('Directory "%s" does is not writable.',
            $path
        ));
    }
```

into this:
    mkdir($path, 0777, true);
Now everything works fine. Why? Whats the problem?

**Comment by piotrekkr** [comment]
It's probably because `mkdir()` and `is_writeable()` gets string:

    %kernel.root_dir%/../some/dir

which does not exists. I think Symfony does not replace parameters in entity configuration yaml files. You can fix this like this:

Set `pathMethod` in entity class:

    Your\TestBundle\Entity\Test:
        repositoryClass: Your\TestBundle\Entity\TestRepository
        type: entity
        table: test
        gedmo:
            uploadable:
                pathMethod: getUploadDir

Adding method to entity:

```
<?php
namespace Your\Test\Entity;
class Test
{

    private $uploadDir;

     public function setUploadDir($dir)
    {
        $this->uploadDir = $dir;
        return $this;
    }

    public function getUploadDir()
    {
        return $this->uploadDir;
    }
}
```

Just before persisting entity (controller probably):

```
<?php

$uploadableManager = $container->get('stof_doctrine_extensions.uploadable.manager');
$entity->setUploadDir($container->getParameter('kernel.root_dir') . '/../web/uploads/presentations');

```
Quite ugly solution but works without changing `Uploadable` code.
