### ISSUE TITLE
[Tree] issue when persisting element: lvl isn't changed

### ISSUE THREAD

**Issue by Morgorth** [doctrine-extensions/DoctrineExtensions#1216]
Hello,

I'm using Tree extension (type nested) on several entities of mine.
I randomly have an issue when saving new element or changing parents of existing ones.

I simply create the element, then call the setParent($object); and then persist+ flush:
The "parent_id" is always correctly affected but the lvl is never update (stays NULL), thus the tree is false (root also isn't touched).

Is this a known issue of the bundle ? I've searched by didn't find anything. Is there something to force to set the right lvl ?

**Comment by l3pp4rd** [comment]
can you make an use case in the test? you can change composer dependencies based on your use case.
