### ISSUE TITLE
[Timestampable] Apply timezone to created and updated fields

### ISSUE THREAD

**Issue by hugomn** [doctrine-extensions/DoctrineExtensions#1217]
Hi! I couldn't find any way to apply a timezone to created and updated fields. In my system, I store user timezone in the database, and when insertingdates on db, I need to do proper conversions to UTC. Today TimestampableListener is inserting dates in my machine timezone. @stof suggested to override the listener, but I could not find the right place to change how dates are set. Any ideias?

Thanks in advance,

**Comment by maffpool** [comment]
Hi ! I've got the same problem, the best improvement would be to use `datetimetz` fiels instead of `datetime`.
A possible workaround is to create a doctrine pre persist listener :

```php
class LogEntryPrePersistListener
{
    public function prePersist(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();

        if ($entity instanceof LogEntry) {
            if ($entity->getLoggedAt()->getTimezone()->getName() !== 'UTC') {
                $entity->getLoggedAt()->setTimezone(new \DateTimeZone('UTC'));
            }
        }
    }
}
```
