### ISSUE TITLE
Get parent nodes

### ISSUE THREAD

**Issue by Ziiweb** [doctrine-extensions/DoctrineExtensions#1225]
I didn't find any method to get the parent nodes. For example, given Apple category, I would like to get an array containing the Fruit category and the Food category.

Don't you find this method interesting or is it implemented in some place I can not see?

**Comment by lsv** [comment]
+1

**Comment by l3pp4rd** [comment]
I think that translates to path, there is a **getPath** method in nested tree repository

**Comment by phansys** [comment]
Closing as `MaterializedPathRepository::getPath()` was added in version [`2.4.10`](https://github.com/doctrine-extensions/DoctrineExtensions/releases/tag/v2.4.10).
Thank you.
