### ISSUE TITLE
translator document

### ISSUE THREAD

**Issue by ghanbari** [doctrine-extensions/DoctrineExtensions#1246]
Hi, How can i find document for Translator extension?
exists any document for this extension?(i search in google, but can not find any)

what is difference between translation & translator?

**Comment by brizzz** [comment]
+1 cant find the docs for Translator extension

**Comment by l3pp4rd** [comment]
the link is removed, the fast alternative is https://github.com/KnpLabs/DoctrineBehaviors#translatable

**Comment by AkenRoberts** [comment]
@l3pp4rd I noticed this as well going through the readme. Why is there `Translatable` AND `Translator`?

**Comment by sirdiego** [comment]
> @l3pp4rd I noticed this as well going through the readme. Why is there `Translatable` AND `Translator`?

I don't get what the `Translator` is for either. Maybe @everzet can chime in with some info?
