### ISSUE TITLE
[Question][Sluggable] generate slug only when publish my documents

### ISSUE THREAD

**Issue by florentcoquel** [doctrine-extensions/DoctrineExtensions#1254]
Hello,

I have an application that needs to have slugs for each content but only when they are published online and not at the creation of the content.

My documents contain fields "title" with which I generate the slug, a field "publicationStatus."

``` php
/**
 * @var string
 *
 * @ODM\String
 * @ODM\Index(unique=true)
 * @Assert\NotBlank(message="article.title.required")
 */
protected $title;

/**
 * @ODM\String
 * @Gedmo\Slug(fields={"title"})
 */
private $slug;

/**
 * @var string
 *
 * @ODM\String
 */
protected $publicationStatus;

```

What I would do is generate the slug when the status of publication is set to "online". 

``` php
$entity = $em->find('Entity\Something', $id);
$entity->setPublicationStatus("online");
$em->flush();
```

Once my slug is generated it could not be updated !

**Comment by ClementGautier** [comment]
ping @stof  @l3pp4rd  I would like to know how to deal with that too. I thought that setting the slug the null value in a prePersist / preUpdate event while the condition do not match the business rule would regenerate the slug but unfortunatly it does not. Any advice ? (Thanks for your time invested on this library btw)

**Comment by l3pp4rd** [comment]
Slug is always built on flush. There is no way to comfigure it differently. If slug does not regenerate when setting null, then it may be an issue. Concerning your problem, you may have two entities, Draft and Post. Library won't adapt to all use cases.
