### ISSUE TITLE
Using embedded documents for custom translation entities

### ISSUE THREAD

**Issue by coudenysj** [doctrine-extensions/DoctrineExtensions#1267]
I've been playing around with [translation entities](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#translation-entity) with MongoDB and it would be cool if the translations were actually embedded in the entity instead of in a different collection.

Is this something this is possible? If not, is it possible to make it possible? If so, how can I help out?

**Comment by l3pp4rd** [comment]
Hi, currently not sure if that is supported. The closest thing is these personal translations, which stands as a relation, see the [documentation](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#personal-translations) maybe it can be updated as an embedded relation..

**Comment by coudenysj** [comment]
Looks like the embedding is working with the personal translations, but the query still tries to look in a different collection. Will have a look at it when I have time to investigate.

**Comment by nicodmf** [comment]
I think too, that embedded translation is the good choice for an odm. A document should be unique and relation shouldn't exist for this part, the phpcr solution is in my mind another good choice which save the translation in a field whith custom name : i18n:language-fieldname

**Comment by markitosgv** [comment]
+1, I think the best approach for MongoDB is an embed document.
