### ISSUE TITLE
[Loggable] Log changes for an untouched entity

### ISSUE THREAD

**Issue by HooverG** [doctrine-extensions/DoctrineExtensions#1273]
Hello guys.

I have 2 classes which represent only one entity thanks to Class Table inheritance.
To make things simple the parent class contains a string and an integer. (both versioned) + 2 fields timestampable (createdAt and updatedAt).
The other class extends the first one and contains other fields versioned.

If I update the entity without any change there is a new line in ext_log_entries.
The string field in the parent class never appears in the data except if I update the field.
Is loggable supposed to store versioned entity fields each time a modification occurs or only differences between 2 versions ?

I suppose my entity is marked as dirty because of the timestampable fields.

Is it possible to avoid that behaviour ?

Ty.

**Comment by l3pp4rd** [comment]
Hi, not sure about your use case. But as far as I understand, loggable is logging only differences. The update triggers always if there is a change in the entity, it does not matter if the field is versioned or not. If you change any property of this entity and persist, timestampable will update accordingly and loggable will update diff if there was a date field versioned. If it is not so, please provide your entity example..
