### ISSUE TITLE
[Question][Tree]SQLite test fails in application

### ISSUE THREAD

**Issue by truckee** [doctrine-extensions/DoctrineExtensions#1284]
In a simple test of a Category entity in a Symfony application I get 

> Doctrine\DBAL\DBALException: An exception occurred while executing 'INSERT INTO category (title, lft, lvl, rgt, root, deletedAt, parent_id) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["Hook", null, null, null, null, null, null]:
> SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: category.lft

using a SQLite db in the test environment cache.  

Yet I see that Tree extension's own test uses a `pdo_sqlite` driver.  I do not understand why the difference in behavior using SQLite and thus cannot resolve the error. I am able to successfully test using MySQL so I do not think it's my test.

The test fixture:

```
    public function load(ObjectManager $manager)
    {
        $manager->clear();
        $cat = new Category();
        $cat->setTitle('Hook');
        $manager->persist($cat);
        $child = new Category();
        $child->setTitle('Dry');
        $child->setParent($cat);
        $manager->persist($child);
        $manager->flush();

    }
```

The test

```
    public function testCategoryCount()
    {
        $cats = $this->em
                ->getRepository('AppBundle:Category')
                ->findAll()
        ;

        $this->assertCount(2, $cats);
    }
```

Any insight or advice would be greatly appreciated!

**Comment by l3pp4rd** [comment]
have you looked at the tests? I think listener is not hooked or something similar, since most of the tests are sqlite based and contains similar scenarios
