### ISSUE TITLE
querybuilder very slow with hint

### ISSUE THREAD

**Issue by strauss69400** [doctrine-extensions/DoctrineExtensions#1317]
hello,

wanting to run querybuiders with the use of hint, 
I end up with hanging problems.for exemple I have a sql query that run in 12s  when using the hint.
here is my QueryBuilder:

```
    $qb = $this->createQueryBuilder('a')
    ->where('a.slug =\''.$slug.'\'' )
    ->andwhere('a.actif=1')
    ->andwhere('a.actifLocale=1');

    $query = $qb->getQuery();
    $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
    );
    $query->setHint(\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE, $locale);
```

the Symfony profiler gives me this result : 

SELECT 
  t2_.content AS actifLocale0, 
  a0_.id AS id1 
FROM 
  article a0_ 
  LEFT JOIN article_translations t1_ ON t1_.locale = 'fr' 
  AND t1_.field = 'slug' 
  AND t1_.object_class = 'Kiyoi\BlogBundle\Entity\Article' 
  AND t1_.foreign_key = a0_.id 
  LEFT JOIN article_translations t2_ ON t2_.locale = 'fr' 
  AND t2_.field = 'actifLocale' 
  AND t2_.object_class = 'Kiyoi\BlogBundle\Entity\Article' 
  AND t2_.foreign_key = a0_.id 
  LEFT JOIN article_translations t3_ ON t3_.locale = 'fr' 
  AND t3_.field = 'title' 
  AND t3_.object_class = 'Kiyoi\BlogBundle\Entity\Article' 
  AND t3_.foreign_key = a0_.id 
  LEFT JOIN article_translations t4_ ON t4_.locale = 'fr' 
  AND t4_.field = 'text_intro' 
  AND t4_.object_class = 'Kiyoi\BlogBundle\Entity\Article' 
  AND t4_.foreign_key = a0_.id 
  LEFT JOIN article_translations t5_ ON t5_.locale = 'fr' 
  AND t5_.field = 'content' 
  AND t5_.object_class = 'Kiyoi\BlogBundle\Entity\Article' 
  AND t5_.foreign_key = a0_.id 
ORDER BY 
  a0_.ordre ASC

is that there is a solution to avoid the problem of slowness??

thank you very much for your help

**Comment by l3pp4rd** [comment]
the default translation class is for small table sizes, if foreign key type is string, override the mapping to make it an integer, it does cast otherwise. But better make something more custom, try to run mysql **EXPLAIN** for the select statement run **order by** in PHP instead.

**Comment by TheRatG** [comment]
Hello I have the similar problem, query execution time is 0.06 sec, but php script time is more than 35 sec with HINT_CUSTOM_OUTPUT_WALKER.

gedmo/doctrine-extensions                v2.4.10

**Comment by l3pp4rd** [comment]
@TheRatG I doubt that it is an issue of translatable, if this query takes 0.06sec.. you should debug to know what takes so long.

**Comment by TheRatG** [comment]
- [x] to make it an integer
it works, thanks

**Comment by sirdiego** [comment]
> the default translation class is for small table sizes, if foreign key type is string, override the mapping to make it an integer, it does cast otherwise. But better make something more custom, try to run mysql **EXPLAIN** for the select statement run **order by** in PHP instead.

Hey @l3pp4rd what do you mean by "small table sizes" and "better make something more custom"? Would you be willing to explain a little more? Thank you for all the work you did back then!
