### ISSUE TITLE
Assigned left, right, root and level all 0

### ISSUE THREAD

**Issue by hisie** [doctrine-extensions/DoctrineExtensions#1321]
When persisting a new entity with Tree behaviour using Nested all values related to tree are 0.
The things i have seen are:
- Listener Working. Execution uses onFlush() method correctly
- Strategy correct: Nested Class used
- Call to processScheduledInsertion done: This is the method that change the null value of left, right, level, and root to 0.
- Call to flush end.
- Not call to updateNode anytime

Versions: 
Doctrine common 2.5
Doctrine extensions 2.3.12

**Comment by jayesbe** [comment]
Id like to confirm this issue. Trying to persist a new tree. all values are null. persistence fails.

there is someone over on stack trace that has posted the same issue

http://stackoverflow.com/questions/30264815/mapping-nested-tree-with-doctrine-2-and-yaml

**Comment by l3pp4rd** [comment]
well the stackoverflow has an answer that needs to be fixed for yaml and probably xml mapping drivers

**Comment by zuernBernhard** [comment]
Same Problem here with Symfony 2.3
