### ISSUE TITLE
[Translatable] Unexpexted default locale behaviour on new entity creation

### ISSUE THREAD

**Issue by brizzz** [doctrine-extensions/DoctrineExtensions#1322]
May be I missed something in the docs. I expected that if the new entity is not set in the default locale, TranslatableListener will try fill it with  nulls. And if translated field is required, then I get SQL exception - "value ... cannot  be null".

Let me explain with an example.

TranslatableListener settings:

$translationFallback = false; 
$locale = 'ru'; //current local
$defaultLocale = 'en'; 
version: 2.4.1

```
$book = new Book();
$book->setName('name in ru'); 

$em->persist();
$em->flush();
```

This is where I see unexpected begaviour. I expect SQL error, since I did not specify the value for the default locale. Current locale is ru, the default is en. However the value of the locale 'ru' pasted in the book table (should be null !). The book_translation table also have the appropriate record (as expected).

But when I upgrade the entity, it works as expected:

```
$book = $em->find('AppBundle:Book', 1);
$book->setName('updated name in ru'); 

$em->persist();
$em->flush();
```

Now in the book table we have 'name in ru', and in the book_translation - 'updated name in ru'. 

Question is: why on creation a new entity without providing value in default locale TranslatableListener sets the value from currently provided locale? And how to prevent it?

**Comment by Eraknelo** [comment]
Yes, thank you. I am pulling my hair out. Glad it's not just me. Is this normal behavior?
I also always have my default locale set to EN.
I create a new entity, with current locale set to NL.
And it writes the values to the entity itself, instead of creating a new NL translation.

**Comment by brizzz** [comment]
As a result, I decided to use alternative from knplabs https://github.com/KnpLabs/DoctrineBehaviors#транслятабле

Their implementation seemed to me simpler and more predictable. I have not yet any issue with that.

**Comment by l3pp4rd** [comment]
it cannot leave entity field value set to null, because it would fail to persist if field is not nullable. the translatable extension is far from being a good simple implementation, it was made for the easy integration and such use cases, to have something fast and working or at any point in time. use custom solutions if you want performance or different behavior. now it will remain backward compatible
