### ISSUE TITLE
Can't get any associated entity to a tree entity

### ISSUE THREAD

**Issue by sunviwo** [doctrine-extensions/DoctrineExtensions#1323]
I'm working on an e-learning application and I have to categorize courses. So my Section entity is one of Tree extension. In order to retrieve all courses of a section, I made the following assoication: 

```
/**
     * @ORM\OneToMany(targetEntity="Svi\FormationBundle\Entity\Course", mappedBy="section")
     */
    private $courses;
```

The problem is that when I try get courses in twig doing this `{% if section.courses|length > 0 %}`, I receive this error message `Key "courses" for array with keys "id, titre, sommaire, slug, deactivated, lft, lvl, rgt, root, __children" does not exist in SviFormationBundle:Formation:see_courses.html.twig at line 22`. I made a dump on the section object and it displayed all attributes except ones of OneToMany and ManyToOne associations. Any help please? Isn't it possible to associate other entities to a Tree entity? If so how to make a nested classification in Symfony? Thanks.

**Comment by l3pp4rd** [comment]
it is possible to add as many relations as you want. you are doing something wrong regarding orm rules.
