### ISSUE TITLE
[Tree] Having the option for level in tree to start from 1, instead of 0

### ISSUE THREAD

**Issue by pmishev** [doctrine-extensions/DoctrineExtensions#1328]
I'm working with an old database, where the level in the tree structure starts from 1, instead of 0.
It would be nice to have an option in the annotation, such as:

```
@Gedmo\TreeLevel(base=1)
```

**Comment by l3pp4rd** [comment]
hi, no, extend it for your own use cases these kind of options confuses people when they start to pile up

**Comment by karousn** [comment]
@l3pp4rd : i need to implement the same trick, can you give me the way that i should take it to override the initialization of the first level used ? should i override this class  `Gedmo\Tree\TreeListener` ?

**Comment by pmishev** [comment]
@karousn: you may have a look at my PR to see how I've implemented it: https://github.com/Atlantic18/DoctrineExtensions/pull/1340/files

**Comment by karousn** [comment]
@pmishev : I'll try to try it , thanks
