### ISSUE TITLE
Versioned with Translatable

### ISSUE THREAD

**Issue by PgPedroGabriel** [doctrine-extensions/DoctrineExtensions#1329]
When i set a translate in my not default language, its generate a log of my Object. In the log the action is Update, but my real object in DB is not changed because i set the translation in other language (not default language). What i can do to not create a log in this case? Or if create a log, i set that log to a "Language Log"?

**Comment by l3pp4rd** [comment]
you should have a custom log manager or extend the loggable listener, the default use case is basic and does not track other extension behavior

**Comment by jlchafardet** [comment]
would you be so kind as to provide us with an example on how to do this? or better yet! include a way to make them work together.

as it really makes no sense at all to have this behaviors and not being able to use them together.

**Comment by l3pp4rd** [comment]
I would suggest using https://github.com/DATA-DOG/DataDogAuditBundle it is much more robbust
