### ISSUE TITLE
Recovery fails because it ignore lft and rgt values

### ISSUE THREAD

**Issue by Drachenkaetzchen** [doctrine-extensions/DoctrineExtensions#1332]
I'm trying to upgrade from https://github.com/blt04/doctrine2-nestedset. My entity already had lft and rgt nodes. The difference between doctrine2-nestedset and this extension is that doctrine2-nestedset seems to operate on lft and rgt values only, while this extension seems to rely on parent relations.

What recover() should do is to go through the lft and rgt values and build the tree from that.

**Comment by l3pp4rd** [comment]
hi, you can contribute a different method named accordingly.

**Comment by stephanvierkant** [comment]
+1
