### ISSUE TITLE
problem in remove item from tree

### ISSUE THREAD

**Issue by ghanbari** [doctrine-extensions/DoctrineExtensions#1339]
If i have a `onDelete=restrict` on parent field and remove a node that have children by `$em->remove()`, tree is broken and have invalid `lft` & `rgt` values

[stack qustion](http://stackoverflow.com/questions/30974812/why-tree-is-invalid/30978344#30978344)

**Comment by l3pp4rd** [comment]
well, do not use restrict in that case. since it needs to cascade removes
