### ISSUE TITLE
Tree Nested no children

### ISSUE THREAD

**Issue by zuernBernhard** [doctrine-extensions/DoctrineExtensions#1341]
Hi, 

I have a Simple Category Entity using NestedTree, I have the parent column in my DB  and There Rows with valid parent_ids. 
But when I try to get e tree. For Example with:

$repo = $this->get('doctrine.orm.entity_manager')->getRepository('Eb\CategoryBundle\Entity\Category');

$arrayTree = $repo->childrenHierarchy();

I Only get Entites without Children. What am I Missing ?

**Comment by l3pp4rd** [comment]
maybe a level field is necessary, you should debug the method to see the reason.. should throw an execption probably

**Comment by zuernBernhard** [comment]
Yes you are right indeed. When I fix 'root' and 'lvl'-Column values by hand in the db everything is fine. There is no Exception (neither when the node is saved, nor when i read it with childrenHierarchy).
In my "Backend" I use the CypressTreeBundle (https://github.com/matteosister/CypressTreeBundle) to manage my tree. That Shows the right hierarchy even if root and lvl are NULL.

**Comment by l3pp4rd** [comment]
well, I do not know all bundles :) but may be useful to someone if they have no level column and want the same behavior
