### ISSUE TITLE
[References] Manually force dirty/property checking so preUpdate fires

### ISSUE THREAD

**Issue by aramalipoor** [doctrine-extensions/DoctrineExtensions#1350]
Imagine with have an entity `Product` and a document `Image` like below:

``` php
class Product {
  /**
   * @var Image
   * @Gedmo\ReferenceOne(
   *   type="document",
   *   identifier="imageId",
   *   class="Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Image"
   * )
   */
  private $image;

  /**
   * @var string
   */
  private $imageId;
}

class Image {
  /**
   * @var string
   */
  private $id;
}
```

A huge problem we have with References extension is that when the referenced field `image` (of Product) is the only field which has changed doctrine `preUpdate` event will not get fired, so References listener will do its job of setting `imageId`.

Do you think it's possible to use `UnitOfWork->propertyChanged` to manually force dirty checking on updated Product entity so that `preUpdate` is fired? Just like what [`Uploadable` extension](https://github.com/Atlantic18/DoctrineExtensions/blob/3940af1099c47dd4bea036616730e8760a3fdba1/lib/Gedmo/Uploadable/UploadableListener.php#L111-L133) is doing.

With this feature there's no need for an application to cover this case manually.

**Comment by l3pp4rd** [comment]
not sure if backward compatibility will be maintained. If you are sure it does not introduce problems and makes more sense you may submit a pr. I haven't used extensions for a long time now and do not remember all that stuff..
