### ISSUE TITLE
[Uploadable]  "The class 'Symfony\Component\HttpFoundation\File\UploadedFile' was not found in the chain configured namespaces Acme\Bundle\UserBundle\Entity"

### ISSUE THREAD

**Issue by korbav** [doctrine-extensions/DoctrineExtensions#1353]
Hi, I am using the Uploadable Extension on a fresh Symfony 2.7 installation.

My scenario does not make use of Form Component, so I attach manually the file entity "Avatar" to a "User" entity in my controller : 

The following error is triggered while I'm trying to persist the host entity :

`"The class 'Symfony\Component\HttpFoundation\File\UploadedFile' was not found in the chain configured namespaces Sowq\Bundle\UserBundle\Entity"`

Here is the relevant part of code of the controller which manages the request : 

```
public function postUserAvatarsAction($id, Request $request){
    $user = $this->get('security.context')->getToken()->getUser();

    $validator = $this->get('validator');
    $data = array();
    $em = $this->getDoctrine()->getManager();

    $files = $request->files;
    $avatar = $files->get('avatar');
    $user->setAvatar($avatar);

    $errorsAvatar = $validator->validate($user->getAvatar());
    if(count($errorsAvatar)){
        $view = $this->view($errorsAvatar, 400);    
    }
    else{
        $em->merge($user);          
        $uploadableManager = $this->get('stof_doctrine_extensions.uploadable.manager');
        $uploadableManager->markEntityToUpload($user, $user->getAvatar());              
        $em->flush();
        return new Response("done");
    }   
}
```

I have also dumped the exception stack to enquiry : [Full errror stack](http://pastebin.com/sgPE4Uh1)

I am absolutely not sure that the problem is linked to the doctrine extension isolatedly as the error stack clearly mention a doctrine mapping issue. I'm not doing anything special and my installation is fresh so I was thinking perhable of a compatibility issue, any help is welcomed :-) Thx

**Comment by victordit** [comment]
I think the problem is that you or (uploadableManager extension - I don't know this) try set an object file (of type "UploadedFile Class")

```php
   $files = $request->files;
    $avatar = $files->get('avatar');
 $files = $request->files;
    $avatar = $files->get('avatar');
    $user->setAvatar($avatar);
```
$Avatar is a file object if you want save to DataBase, you need a datatype blob.
Usually, before save the file on File System and then save $Avatar on DB, where $Avatar is just file path or file name o link to File System resource
Like This:

```php

       $newPath =  $this->getFile()->move(
        'destination/folder',
        'filename.jpg'
    );

```
