### ISSUE TITLE
[loggable] store embeddedDocument with version

### ISSUE THREAD

**Issue by codewode** [doctrine-extensions/DoctrineExtensions#1355]
I have a document

class MyDocument 
{
    /**
     \* @var $id
     \* @Gedmo\Versioned
     _/
    protected $id;
    /_*
     \* @var string
     \* @Gedmo\Versioned
     */
    protected $name = "page";

```
/**
 * @var null|Edge
 * @Gedmo\Versioned
 */
protected $node = null;
```

}

and its yml mapping is like

MyNamespace\MyDocument:
  gedmo:
    loggable:
      logEntryClass: MyNamespace\LogEntry
  fields:
    id:
      id: true
      strategy: AUTO
      gedmo:
        - versioned
    name:
      type: string
      gedmo:
        - versioned
  embedOne:
    node:
      targetDocument: MyNamespace\Edge
      gedmo:
        - versioned

the primitive type fields are well stored in LogEntry document, however, the computeChangeSet doesn't figures out change for the embeddedDocument, hence any change to the node field is not stored to the logEntry table.

is this a limitation of Loggable that it doesn't works for embeddedDocument, or for references?

**Comment by l3pp4rd** [comment]
well, yes that is not supported, someone should contribute if they need that behavior available in loggable
