### ISSUE TITLE
SoftDeletable query cache on custom repository not updating

### ISSUE THREAD

**Issue by phillipsnick** [doctrine-extensions/DoctrineExtensions#1356]
I'm having an issue with the queries being generated by Doctrine when using the SoftDeletable extension.

When I create a custom query within my EntityRepository the where deletedAt timestamp is returning a cached time from when it was first executed. I'm struggling to find where exactly this issue is coming from.

If I use `findAll` or another default doctrine method the timestamp returns the current time, this is only present with custom queries.

Issue can be resolved for a single page load via:
- Clearing all of memcached
- Clearing doctrine meta data cache
- Clearing doctrine query cache

My query with no specific caching options.

``` php
    /**
     * @param FaqFilter $filter
     * @return Paginator
     */
    public function findAllFiltered(FaqFilter $filter)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('f', 'fc')
            ->from('ContentBundle:Faq', 'f')
            ->innerJoin('f.faqCategory', 'fc')
            ->setFirstResult($filter->getFirstResult())
            ->setMaxResults($filter->getResultsPerPage());

        if ($filter->hasFaqCategory()) {
            $query
                ->andWhere('f.faqCategory = :faqCategory')
                ->setParameter('faqCategory', $filter->getFaqCategory());
        }

        $query
            ->addOrderBy('fc.position', 'ASC')
            ->addOrderBy('f.position', 'ASC')
            ->getQuery();

        $paginator = new Paginator($query);
        $paginator->setFilter($filter);

        return $paginator;
    }
```

Looking at MySQL query log I have the following:

``` sql
SELECT f0_.faqId AS faqId_0, f0_.title AS title_1, f0_.answer AS answer_2, f0_.position AS position_3, f0_.createdAt AS createdAt_4, f0_.updatedAt AS updatedAt_5, f0_.deletedAt AS deletedAt_6, f1_.faqCategoryId AS faqCategoryId_7, f1_.name AS name_8, f1_.position AS position_9, f1_.createdAt AS createdAt_10, f0_.faqCategoryId AS faqCategoryId_11 FROM faqs f0_ INNER JOIN faqCategories f1_ ON f0_.faqCategoryId = f1_.faqCategoryId WHERE (f0_.faqId IN (4)) AND ((f0_.deletedAt IS NULL OR f0_.deletedAt > '2015-07-16 17:07:36')) ORDER BY f1_.position ASC, f0_.position ASC
```

Specifically this part

``` sql
f0_.deletedAt IS NULL OR f0_.deletedAt > '2015-07-16 17:07:36'
```

This timestamp never changes until I manually execute one of the cache clearing methods mentioned above.

**Comment by l3pp4rd** [comment]
well, this could be changed to one of database methods like `NOW()` but it introduces a NOW() call to each row in the database when used in where statement, but probably that would be a reasonable change..

**Comment by phillipsnick** [comment]
Could you point me to the direction that this is added to the query? 

I'll have a play :)

**Comment by l3pp4rd** [comment]
well, you can submit a pull request by updating https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/SoftDeleteable/Filter/SoftDeleteableFilter.php#L46 to use database platform based now expression https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L868

**Comment by stephanvierkant** [comment]
This issue duplicates #1146, isn't it?

Any idea when the fix will be available in a tagged version? It's only merged into the master branch right now.
