### ISSUE TITLE
[Tree] ClosureTreeRepository::buildTreeArray can't handle root node

### ISSUE THREAD

**Issue by simshaun** [doctrine-extensions/DoctrineExtensions#1359]
Because the root is at level 0, when calling **`ClosureTreeRepository::buildTreeArray($nodes)`** where `$nodes[0]` is the root, it won't build the array. This is due to [**this line**](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Entity/Repository/ClosureTreeRepository.php#L300):

```
$l = 1;     // 1 is only an initial value. We could have a tree which has a root node with any level (subtrees)
```

Changing that to `$l = 0;` fixes the problem. I'm willing to make a quick PR. Do you have any concerns?

**Comment by simshaun** [comment]
So I think I may be getting confused after staring at this stuff for so long.

My understanding:

- Root node is always level 0.
- Closure table depths start at 0.
- A child of the root node is level 1.
- The root <> child closure is depth 1.

I have a page tree like so:

    Homepage (root node, level 0)
        - Cars (child, level 1)

When I attempt to add a child to Cars, Gedmo says that new child is level 3.

**Comment by simshaun** [comment]
Maybe the root is supposed to be level 1? Everything seems to be ok when it is.

I assumed it was supposed to be 0, from the tests: https://github.com/Atlantic18/DoctrineExtensions/blob/master/tests/Gedmo/Tree/TreeTest.php#L66

**Comment by l3pp4rd** [comment]
it should be 0, maybe it could take the level based on the $nodes[0] ? could accept any level nodes..

**Comment by l3pp4rd** [comment]
anyway, if you can update to support the backward compatibility it should be ok

**Comment by simshaun** [comment]
Does that mean [*this is wrong*](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Closure.php#L285-L286)?

Seems like if it has no parent, it is the root and should be level 0.
Side-issue: Those lines suffer from the same problem

**Comment by l3pp4rd** [comment]
well, you know what, I do not even remember now, whether it should be 0 or 1. but I tend to believe that it should be 0 for root without parent. so probably that is wrong..
