### ISSUE TITLE
[Sluggable] Slug value only from OneToOne relation.

### ISSUE THREAD

**Issue by jee7** [doctrine-extensions/DoctrineExtensions#1367]
I have following entities:

**Topic**
- title
- slug

**PublicTopic**
- slug
- topic

There are a number of Topics that will have the same title and need to be given an unique slug in the Topic table (eg. topic-a, topic-a-1, topic-b etc). This works well. But now I want to have some of those topics _public_. I created another table with an entity PublicTopic (it has more fields related to only public topics). Each entry there has OneToOne relation to some Topic. I want the slug for a PublicTopic to be generated from the title of the Topic.
I tried to use the RelativeSlugHandler, but it seems that the fields array is still mandatory. Thing is, there is no field in the PublicTopic table from which to create a slug from. It is in the OneToOne related Topic table (the title field). 
I guess the easiest solution now would be for me to just add the title to the PublicTopic and copy the contents from the Topic. In this way I don't even have to use the RelativeSlugHandler, but it creates data redundancy.

Here is an example how I would like the data to look like:

**Topic**

| id | title | slug |
| --- | --- | --- |
| 1 | Topic A | topic-a |
| 2 | Topic A | topic-a-1 |
| 3 | Topic B | topic-b |

**PublicTopic**

| id | slug | topic_id |
| --- | --- | --- |
| 1 | topic-a | 2 |
| 2 | topic-b | 3 |

**Comment by l3pp4rd** [comment]
Hi, in order to generate slug fields need to exist. Why you cannot just copy a slug since it is unique or add a boolean `$published` field? extensions will not provide all possible use cases, you need to adapt to working version. If the feature would be a very common use case, that could be considered, otherwise not.

**Comment by jee7** [comment]
I can't copy the slug, because I want the slug to be unique on only the public topics. Let's say we have a history of topic edits for example. There will be many versions of a Topic that each should have their own unique slugs. But only the latest version should be *public* and have a slug without a suffix.
As for a boolean field, like I mentioned, there is other data associated with the PublicTopic entity (public order, OG tag values etc). An entity in the Topic table is considered public if it has an associated OneToOne PublicTopic. It doesn't seem a good idea to have both the relation and a boolean specifying the same thing.
Of course, I understand that this feature (to generate a slug from only a field from an associated entity) might not be a common use case. Thought to give it a shot anyway and see if there will be any insight on the subject.

**Comment by l3pp4rd** [comment]
well, if you do not see how you can implement this behavior within the current sluggable features, that is an use case which is too rare to support and maintain. You could try to extend it or simply use the transliterator and handle uniqueness your own way. I still do not think that this is a good way to have a state history, you may create an event listener to store any change made in orm in a history log (I do not mean loggable extension here, it should be custom)

**Comment by jee7** [comment]
You might be right it being a rare case. Although all I would want is the Sluggable to allow no fields array if the RelativeSlugHandler is used. My field is "topic->title" or "topic.title", a field from the associated entity, not the current one.
Still, imagine you have some data that changes in time: a chain. Now, there are several gateways to access the data, each gateway is configured to show some link in the chain. There can be many such chains and each chain has its own slug. Each link in the chain should also be accessible via a slug. This is my structure. 
Maybe such a use case would be more clear: Let's say we have a repository of images. E.g. animal photos. Everyone can upload a photo of a cat, there will be cat-1.png, cat-2.png, cat-3.png. All those files should be accessible via their unique names. But now we want to show the best cat image there is and call it cat.png. A cat-expert can change to which existing image cat.png actually points to.
In such case I would have entities called Image and PrimaryImage.

**Image**

| id  | title | slug |
| ------------- | ------------- | ------------- |
| 1 | Cat | cat |
| 2 | Cat | cat-1 |
| 3 | Cat | cat-2 |


**PrimaryImage**

| id | slug | image_id |
| ------------- | ------------- | ------------- |
| 1 | cat  | 3 |

URL-s would be something like:
* pictures/primary/cat  (points to Image with id 3)
* pictures/cat
* pictures/cat-1
* pictures/cat-2

By the way, I suspect that I could get it working if I add a dummy column in the database and use that as the Sluggable field. Sluggable would take the correct field from the associated entity, urlize it and then concatenate an empty value to it.
But, yes, currently I created the data redundancy and copied the title field from the associated entity. Seems to be a bit better way than to try to trick the Sluggable.

**Comment by l3pp4rd** [comment]
well, if it is backward compatible and there aren't much to change I can accept the change in PR. but note that, it should allow no fields only in case if slug handler is used, since otherwise it does not make any sense.

**Comment by zeckon** [comment]
Hello,

is this possible now?

I need something similar, not in a OneToOne relation but in a OneToMany relation.

Let say we have blog posts and we want to keep multiple slugs for each post. So everytime i persist a PostSlug entity, it needs to generate a new slug from it's parent entity Post's title.

title
title-1
so on..

it would be great to be able to give only a relation field as slug source.

**Comment by zeckon** [comment]
So i followed a similar workaround approach, i created a dummy property to set as slug source field. i use it for other purpose later but since it is null at the insert time, RelativeSlugHandler gets an empty value from it. Also setting seperator to '' results in a child slug with parent propery ;)
