### ISSUE TITLE
Can't get uploadable entities children of another entity updated because path is set to null

### ISSUE THREAD

**Issue by cazzoo** [doctrine-extensions/DoctrineExtensions#1388]
Hello!

I try for several days to get uploadable entities well updated on update but I'm encoutering a eird issue that I could not resolve : The path attribute of my uplodable entity is set to NULL in database.

Here are my files to understand how I set it up : https://gist.github.com/cazzoo/47dbe2c59b611f08b462

When creating my Game Entity and adding files or when editing my Game Entity to add new files it's all working well.
Otherwise, when editing a Game Entity that has already files added, on my form, the "file field" is set to blank resulting a Null Data on my database when saving my Game Entity...

Is it a bug or an issue with my implementation? If so, what's my issue?
Thanks

**Comment by l3pp4rd** [comment]
@Atlantic18/team-doctrine anyone could answer that? I haven't personally used it. maybe looking at the [test](https://github.com/Atlantic18/DoctrineExtensions/blob/master/tests/Gedmo/Uploadable/UploadableEntityTest.php) could help you figure it out? Check your request->files and see if they are processed in the listener

**Comment by cazzoo** [comment]
For sure I checked the doc dozen of times and found no solution to my
problem.
Yet I de-activated this feature from my form but it's not a good long-term
solution.
Did you reproduce the issue?

I tought also to look into the tests to find anything that would resolve my
issue with no success...

2015-08-13 18:13 GMT+02:00 Gediminas Morkevicius <notifications@github.com>:

> @Atlantic18/team-doctrine
> <https://github.com/orgs/Atlantic18/teams/team-doctrine> anyone could
> answer that? I haven't personally used it. maybe looking at the test
> <https://github.com/Atlantic18/DoctrineExtensions/blob/master/tests/Gedmo/Uploadable/UploadableEntityTest.php>
> could help you figure it out? Check your request->files and see if they are
> processed in the listener
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Atlantic18/DoctrineExtensions/issues/1388#issuecomment-130745943>
> .
>



-- 
Casimir BONNET.
Port. : +33 650 612 550
e-Mail : casimir.bonnet@gmail.com
