### ISSUE TITLE
Softdeleteable not Loggable

### ISSUE THREAD

**Issue by gvanbeck** [doctrine-extensions/DoctrineExtensions#1397]
When those 2 extensions are combined the softdelete is not triggered in the audit-table of the entity.  Not even an update.  You would expect at least an update event is triggered because the timestamp of the deleteAt column is changed.

**Comment by l3pp4rd** [comment]
hi, yes that may be the case, have you tried switching listener positions to modify priority? so that softdelete triggers before timestampable?

**Comment by arrgson** [comment]
i had the same problem, changed the order (as @l3pp4rd pointed out) and all was fine
