### ISSUE TITLE
Softdeleteable feature request: add possibility to store deletedBy also.

### ISSUE THREAD

**Issue by KopiasCsaba** [doctrine-extensions/DoctrineExtensions#1403]
Hi!

Thank you for this stuff!
I would like to ask you to implement the deletedBy feature also in it!

Thanks!

**Comment by l3pp4rd** [comment]
use Blameable for that reason

**Comment by KopiasCsaba** [comment]
As i see it has no option for deletion, it only has create, update, change options, correct me if i'm wrong!

**Comment by l3pp4rd** [comment]
the last user who made an action to deleted item most probably be the one who removed it right?

**Comment by KopiasCsaba** [comment]
Yes, but until that the deltedBy field will be filled with the last user's id, and that looks kinda weird:)

**Comment by l3pp4rd** [comment]
yes but there are no other options, otherwise extend the listener to adapt it your way or add another one to populate this field.

**Comment by KopiasCsaba** [comment]
Okay, for others who struggling with this, the workaround was:

Have a subscriber for preRemove:
```php
class SoftDeletedBySubscriber implements EventSubscriber
{
    /**
     * @var User
     */
    private $user = null;

    public function getSubscribedEvents()
    {
        return array(
            'preRemove',
        );
    }

    /**
     * $em->remove esetén ha van deletedBy mezője az entitásnak, akkor beállítja az akutális userre.
     * @param LifecycleEventArgs $args
     */
    public function preRemove(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();

        if (method_exists($entity, "setDeletedBy")) {
            $entity->setDeletedBy($this->user);
            $args->getEntityManager()->flush();
        }
    }


    /**
     * DocctrineExtensionListener hívja.
     * @param User $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }
}

```

And the key is, to put the configuration of it BEFORE the softdeteletable listener:
```yaml
    foo.bar.softdeletedby:  #Fontos hogy softdeleteable előtt legyen.
        class: foo\bar\SoftDeletedBySubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    gedmo.listener.softdeleteable:
    ...
```

And then you also need the [DoctrineExtensionListener](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/symfony2.md#doctrine-extension-listener-services) that  calls the setUser of this service onKernelRequest:
```php
    if (null !== $securityContext && null !== $securityContext->getToken() && $securityContext->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            $softdeletedby = $this->container->get('foo.bar.softdeletedby');
            $softdeletedby->setUser($securityContext->getToken()->getUser());
        }
```

**Comment by KopiasCsaba** [comment]
Any suggestions and fixes are welcome:)

**Comment by l3pp4rd** [comment]
I'd probably do the same thing, cheers

**Comment by Mopster** [comment]
I'm also struggling to get this to work. I created an EventListener listening to preSoftDelete, I set $entity->setDeletedBy($user), but the change doesn't get saved to the DB (I don't persist/flush, since that would change the updated_[at|by]). 
I debugged and my listener does what it should. But somehow the field/value doesn't get saved when it gets persisted in the SoftDeleteableListener. Also no luck using the UnitOfWork. 

Would be great to have something that works out of the box like the create and update. :-)

**Comment by l3pp4rd** [comment]
you should listen to **preRemove** not **preSoftDelete** in this case

**Comment by Mopster** [comment]
preRemove also does not save the user. 

When I add the flush as stated in the above code extract, the updated_at and updated_by also gets changed unfortunately, I'd like to prevent that.

**Comment by l3pp4rd** [comment]
there are orm methods like `$uow->recomputeSingleEntityChangeSet($meta, $entity);` which should be used instead of persist and flush, `$uow` is `$em->getUnitOfWork()`

**Comment by Mopster** [comment]
Sorry for the trouble :P I did what you suggested, the change doesn't get commited to the DB. When adding $uow->commit() it does, but updated_at also gets changed.
I've been looking at UnitOfWork to see if there are other methods, I checked the SoftDeleteableListener and tried to mimick the behavior, but I'm not familiar with most of this.
```
    public function preRemove(LifecycleEventArgs $lifeCycleEvent)
    {
        $object = $lifeCycleEvent->getObject();
        if (method_exists($object, 'setDeletedBy')) {
            $token = $this->tokenStorage->getToken();
            if (is_object($token)) {
                $user = $token->getUser();
                $object->setDeletedBy($user);
	        $em = $lifeCycleEvent->getEntityManager();
	        $uow = $em->getUnitOfWork();
	        $meta = $em->getClassMetadata(get_class($object));
	        $uow->recomputeSingleEntityChangeSet($meta, $object);
            }
        }
    }
```

**Comment by l3pp4rd** [comment]
well, I do not have time to help you with that, but orm lifecycle events should work as expected since extensions use them in general.

**Comment by Mopster** [comment]
Ok, thanks for the help up to this point :+1: 
Hope this will be supported soon ;-)

**Comment by bobvandevijver** [comment]
For reference, I used the following method which works like a charm. Simple by hooking into the PreSoftDelete event, I know which entity is actually scheduled for removal, which I update. 

```php
<?php

namespace WespAdminBundle\Database;

use Doctrine\Common\EventSubscriber;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Gedmo\SoftDeleteable\SoftDeleteableListener;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class SoftDeletableSubscriber implements EventSubscriber
{

  /**
   * Field name for deleted by
   */
  const FIELD_NAME = 'deletedBy';

  /**
   * @var TokenStorageInterface
   */
  private $tokenStorage;

  /**
   * SoftDeletableSubscriber constructor.
   *
   * @param TokenStorageInterface $tokenStorage
   */
  public function __construct(TokenStorageInterface $tokenStorage)
  {
    $this->tokenStorage = $tokenStorage;
  }

  /**
   * Returns an array of events this subscriber wants to listen to.
   *
   * @return array
   */
  public function getSubscribedEvents()
  {
    return array(SoftDeleteableListener::PRE_SOFT_DELETE);
  }

  /**
   * Sets the deletedBy field
   *
   * @param LifecycleEventArgs $args
   */
  public function preSoftDelete(LifecycleEventArgs $args)
  {
    // Get needed objects
    $object = $args->getObject();
    $om     = $args->getEntityManager();
    $uow    = $args->getEntityManager()->getUnitOfWork();

    // Get old field value
    $meta     = $om->getClassMetadata(get_class($object));
    $reflProp = $meta->getReflectionProperty(self::FIELD_NAME);
    $oldValue = $reflProp->getValue($object);

    // Update the value
    $user = $this->tokenStorage->getToken()->getUsername();
    $reflProp->setValue($object, $user);

    // Make sure the unit of works knows about this
    $uow->propertyChanged($object, self::FIELD_NAME, $oldValue, $user);
    $uow->scheduleExtraUpdate($object, array(
        self::FIELD_NAME => array($oldValue, $user),
    ));
  }
}
```

With as configuration:
```yaml
  wesp_admin_bundle.database.soft_deletable_subscriber:
    class: WespAdminBundle\Database\SoftDeletableSubscriber
    public: false
    arguments:
      - "@security.token_storage"
    tags:
      - { name: doctrine.event_subscriber, connection: default }
```

Note, I've excluded the MongoDB check, as I do not use it (and currently my class does not have direct access to the `$ea` variable): 
```php
if ($uow instanceof MongoDBUnitOfWork && !method_exists($uow, 'scheduleExtraUpdate')) {
    $ea->recomputeSingleObjectChangeSet($uow, $meta, $object);
} else {
    $uow->scheduleExtraUpdate($object, array(
        $config['fieldName'] => array($oldValue, $date),
    ));
}
```

**Comment by oojacoboo** [comment]
I've just pushed a commit on this. @AkenRoberts I'm not sure how to turn it into a pull request. I tried and it resulted in a pull request with multiple commits from a fork.

abbe63a

I've added support for a new remove listener for the annotation on the Blameable extension. I think this should solve all of the issues people have been having here. I know it does for us.  I was a little unsure on how to get `AbstractTrackingListener::updateField` to register that an additional database commit was needed.  I therefore manually specified it for the listener which works fine.  Although, it'd be better if `updateField` was able to properly register it.  Unfortunately, I don't know enough about how `UnitOfWork` is functioning to update it as such.

If anyone has any comments or suggestions, please let me know.
