### ISSUE TITLE
Allow to create nodes with multiple parents

### ISSUE THREAD

**Issue by piotrkochan** [doctrine-extensions/DoctrineExtensions#1407]
Hi, it is possible to create nested sets like:

> 1. Animals >> 1.1 Elephant, 1.2 Monkey, 1.3 Dog
> 2. Pets >> 2.1 Turtle, 2.2 Dog

Where `Dog` is same category with 2 different parents?

**Comment by l3pp4rd** [comment]
Hi, no. this is nested set tree implementation. you are probably looking to a network tree. which is more  complex and less common
