### ISSUE TITLE
Caching of tree structure with Doctrine second level cache

### ISSUE THREAD

**Issue by SvetlinStaev** [doctrine-extensions/DoctrineExtensions#1408]
Hi,

I am using the nested tree extension for building category tree and it works perfect but since I am using that category list on every page I didn't want to query the database for that info on each request but rather cache it using the nice Doctrine second level cache with Redis. I am using a custom repository which extends Gedmo\Tree\Entity\Repository\NestedTreeRepository and gets the category list from there. I override the childrenQueryBuilder method as follows:

``` php
    public function childrenQueryBuilder($node = null, $direct = false, $sortByField = null, $direction = 'ASC', $includeNode = false)
    {
        $queryBuilder = parent::childrenQueryBuilder($node, $direct, $sortByField, $direction, $includeNode);
        $queryBuilder
            ->setCacheable(true)
            ->setCacheRegion('category')
            ->setCacheMode(ORM\Cache::MODE_GET)
        ;

        return $queryBuilder;
    }
```

My entity is set to use:

```
    cache:
        usage: NONSTRICT_READ_WRITE
        region: category
```

and it puts the entries into Redis but I get misses when it tries to retrieve them. Do you guys think it is a issue with the way the base repository works that prevents proper caching or am I missing something in there?

**Comment by l3pp4rd** [comment]
it cannot be related to doctrine extensions, it uses standard query builder and the cache should work the same way as to any query you make. Unless the cache is disabled by default. Try to simply set the unique cache id and see whether it caches the query. maybe it is being reset on each query for you
