### ISSUE TITLE
[Loggable] Invalid serialization data for DateTime object

### ISSUE THREAD

**Issue by zyphlar** [doctrine-extensions/DoctrineExtensions#1416]
Somehow records are being saved to ext_log_entries with empty DateTime objects, which from my research should be almost impossible; upon deserialization the above error is generated. Their occurrence is odd, too, because they don't happen regularly, yet most have decided to happen on a pretty unremarkable day (though I did enable APC caching yesterday, I haven't been at my computer during half of these events and there are thousands of log entries that are just fine before after and during these times.) My solution so far has been to just delete the offending rows, but it seems like there should be a way to prevent malformed serializations in the first place.

```
> select * from ext_log_entries where data LIKE "%DateTime\":0%";                                                                                  +--------+-------
+--------+--------+---------------------+-----------+--------------+---------+---------------------------------------------
| id     | action | logged_at           | object_id | object_class | version | data
+--------+--------+---------------------+-----------+--------------+---------+---------------------------------------------
| 590999 | update | 2015-09-21 23:59:53 | 57        | User         |     192 | a:1:{s:11:"lastLoginAt";O:8:"DateTime":0:{}}
| 591005 | update | 2015-09-22 01:40:44 | 34        | User         |     414 | a:1:{s:11:"lastLoginAt";O:8:"DateTime":0:{}}
| 591040 | update | 2015-09-22 04:29:07 | 1948      | Account      |      13 | a:1:{s:26:"reportLastViewedAt";O:8:"DateTime":0:{}}
| 591049 | update | 2015-09-22 12:13:11 | 231       | User         |      85 | a:1:{s:11:"lastLoginAt";O:8:"DateTime":0:{}}
| 591134 | update | 2015-09-22 15:33:23 | 271       | User         |     223 | a:1:{s:11:"lastLoginAt";O:8:"DateTime":0:{}}
| 591155 | update | 2015-09-22 15:40:53 | 295       | User         |       6 | a:1:{s:17:"passwordChangedAt";O:8:"DateTime":0:{}}
| 591172 | update | 2015-09-22 16:06:30 | 324       | User         |      55 | a:1:{s:11:"lastLoginAt";O:8:"DateTime":0:{}}
| 591181 | update | 2015-09-22 16:10:48 | 236       | User         |      30 | a:1:{s:11:"lastLoginAt";O:8:"DateTime":0:{}}
| 591219 | update | 2015-09-22 17:00:24 | 389       | User         |      57 | a:1:{s:11:"lastLoginAt";O:8:"DateTime":0:{}}
+--------+--------+---------------------+-----------+--------------+---------+---------------------------------------------
9 rows in set (0.47 sec)
```

Using DoctrineExtensions v2.3.9, Doctrine DBAL 2.3.4, the error is generated in `vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/
ArrayType.php` line 48. I haven't traced the cause of the empty DateTimes since it's sporadic and doesn't generate errors.

```
    public function convertToPHPValue($value, \Doctrine\DBAL\Platforms\AbstractPlatform $platform)
    {
        if ($value === null) {
            return null;
        }

        $value = (is_resource($value)) ? stream_get_contents($value) : $value;
        $val = unserialize($value); // LINE 48 //
        if ($val === false && $value != 'b:0;') {
            throw ConversionException::conversionFailed($value, $this->getName());
        }
        return $val;
    }
```

Any ideas? Anyone else dealt with PHP/Doctrine/Loggable serialization issues? Personally I feel like a serialization format like JSON would be more fault-tolerant; I wouldn't care so much except that unserialize() generates a Fatal Exception that can't be caught.

**Comment by l3pp4rd** [comment]
probably would be good idea to change it to **json**, but that should not be the case of serialization problem. The date objects being empty is probably a cause of a bug in APC or PHP, not the first time.
