### ISSUE TITLE
Existing database and Translatable extension

### ISSUE THREAD

**Issue by andreagianfreda** [doctrine-extensions/DoctrineExtensions#1431]
Hi,
a costumer has a recipes website based on Symfony 2. It now would like to internationlize it and translate each recipe in several languages.
I've tried to use the Translatable extension and I expect the generation of a table in my DB that not seem to happen.
Is it correct to use this extension or am I wrong?
What I think is that the extension works properly when a project starts from scratch and not if it is a consolidated product. Hope that impression is wrong.

Please, let me know on how can I approach this.

Thanks,
Andrea

**Comment by l3pp4rd** [comment]
Hi Andrea, there is no automatic migration process, unless you build it for your requirements.

- You may set default locale to one which is used untranslated. And translatable will use that for the default locale translations.
- You can use something else or custom.
- Or analyse how extensions store translations and run a migration.

Cheers,

**Comment by andrea-gianfreda** [comment]
Thanks l3pp4rd,
I think that the last point is the one I should follow. If I understood, I can try to make a new Symfony2 project and apply those extensions, in order to see which database structures it creates. Then I could try to apply it to my existing project.

Is it right?

Thanks,
Andrea

**Comment by l3pp4rd** [comment]
Yes, exactly. Also look first if you have only one language to migrate, choosing default locale does not create extra translation records..

**Comment by andrea-gianfreda** [comment]
If I have more languages to provide, should I not consider this way?

Generally speaking, what I would like to do is to define the logic at the Entity level, passing it the locale and then quering the content from a single translation table that contains all the translations.

If it is well explained, what do you suggest to do?

**Comment by l3pp4rd** [comment]
well, just look how it works and populates translation table, then create a migration script and all should work. one field is translated per row. if you want more elegant solution, go with custom.

**Comment by andrea-gianfreda** [comment]
When you say custom, which are the best practices? Can you suggest me something?
Right now I'm not able to figure out how to define the logic to catch an alternative string once it is defined a specific locale. I would like to act at the Entity class level.

Thanks for your really fast replies!

**Comment by l3pp4rd** [comment]
Ask that question on stackoverflow
