### ISSUE TITLE
[Sluggable] Unique slug for table not for discriminator

### ISSUE THREAD

**Issue by GyniO** [doctrine-extensions/DoctrineExtensions#1472]
Hi,

I have problem with sluggable navigation

My entity:

abstract class Page extends AbstractNavigationPage {
    /**
     \* @Form\Exclude()
     \* @ORM\Column(type="string",nullable=true,unique=true)
     \* @Gedmo\Slug(fields={"name"})
     \* @var string 
     */
    protected $slug;
}

class CmsPageArticle extends Page{

}

class CmsPageGallery extends Page{

}

My table looks like the following:
id,name,slug,discriminator [cmspagegallery / cmspagearticle]

And problem is when I want to add 
cmspagegallery with name "TEST" when I have added element with this name but by entity cmspagearticle
But when I add element with this same name by entity cmspagearticle this is working and my slug is named "slug-1".

Anybody have a idea to that what I want to achieve?

**Comment by l3pp4rd** [comment]
sluggable checks base class for uniqueness, that is how it works. inheritance is complex, I would avoid it in your place anyway

**Comment by GyniO** [comment]
Anyone have a idea how to fix that problem or have other way to avoid this problem?
