### ISSUE TITLE
Change property to getter/setters (Traits + YAML)

### ISSUE THREAD

**Issue by robhunt3r** [doctrine-extensions/DoctrineExtensions#1474]
see https://github.com/doctrine/common/pull/701

This makes possible to map YAML Traits, but DoctrineExtensions events aren't working.

As a workaround I've managed to change `ExtensionMetadataFactory` line
`foreach (array_reverse(class_parents($meta->name)) as $parentClass) {`
to
`foreach (array_reverse(array_merge(class_uses($meta->name), class_parents($meta->name))) as $parentClass) {`

So it will merge parent class and trait properties into our mapping (like I've done on the PR above) but throws exceptions because it's trying to access private/protected (?) properties.

`Error: Cannot access protected property AppBundle\Entity\Foo::$slug`

So, as another workaround I've created getter and setters for properties inside `SluggableListener`,

``` php
$camelizedSlugField = self::camelize($meta->getReflectionProperty($slugField)->getName());
$camelizedSlugFieldSetter = "set".$camelizedSlugField;
$camelizedSlugFieldGetter = "get".$camelizedSlugField;
```

So instead `$meta->getReflectionProperty($slugField)->setValue($object, $slug);` we set our data with `$object->$camelizedSlugFieldSetter($slug);`

that would be necessary for every event...

All of this is because Doctrine isn't able to use Traits with YAML, it just doesn't work, and when you have a big project you don't use Annotations (maybe you do, but I've never met someone who does, if you have 1000 lines inside an entity, it's a mess to find your annotation).

It is our case, we are using Yaml for our entities and we need to use some Traits...

otherwise we need to set properties to public (heh, no thanks) and everything will work with just the `array_merge` line.

PS: (camelize) `return strtr(ucwords(strtr($string, array('_' => ' ', '.' => '_ ', '\\' => '_ '))), array(' ' => ''));`

**Comment by l3pp4rd** [comment]
Hi, I'm glad you find ways to work it around, I do not use extensions or ORM for big projects and I do not remember giving advice to use extensions for non prototype projects. People use what is easy to setup, though extensions are not simple, they are complex as is ORM. Extensions are in feature freeze
