### ISSUE TITLE
Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry" is not a valid entity or mapped super class

### ISSUE THREAD

**Issue by LoveOfLava** [doctrine-extensions/DoctrineExtensions#1488]
Hi,

When I do
$repo = $oGestionnaireEntites->getRepository('Gedmo\Loggable\Entity\LogEntry');
I got the error Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry" is not a valid entity or mapped super class

I used the last version of doctrine and gedmo extensions.
How can I resolve this issue ?

Thanks
Regards

**Comment by l3pp4rd** [comment]
hi, the repository is not meant to be used directly, you should extend it on your own repository.

**Comment by LoveOfLava** [comment]
Hi,

I created an article class

/**
 * @Entity
 * @Gedmo\Loggable
 * @Entity(repositoryClass="gestionnaireDoctrine\GestionnaireArticle")
 */
class Article {

    /**
     * @Column(name="id", type="integer")
     * @Id
     * @GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @Gedmo\Versioned
     * @Column(name="title", type="string", length=88)
     */
    private $title;

    public function getId() {
        return $this->id;
    }

    public function setTitle($title) {
        $this->title = $title;
    }

    public function getTitle() {
        return $this->title;
    }

}

then an repository class

class GestionnaireArticle extends \Gedmo\Loggable\Entity\Repository\LogEntryRepository {
}

but I got the error Doctrine\ORM\Query\QueryException: [Semantical Error] line 0, col 53 near 'objectId = :objectId': Error: Class classeDoctrine\Article has no field or association named objectId in

**Comment by l3pp4rd** [comment]
have you went through [documentation](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/loggable.md)? maybe the reason is that you did not map entities from this library at all [see](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/loggable.md#setup-and-autoloading)

the example application shows how to configure extensions properly. if you use a framework, check for a module or bundle for extensions, most of them has one.

**Comment by LoveOfLava** [comment]
I didn't use a framework.

I took this file as exemple https://github.com/Atlantic18/DoctrineExtensions/blob/master/example/em.php in order to configure doctrine.

**Comment by l3pp4rd** [comment]
in that case, the only difference here is that in example it uses only [abstract mapped supperclasses](https://github.com/Atlantic18/DoctrineExtensions/blob/master/example/em.php#L46) you would need to use [this method](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/DoctrineExtensions.php#L35) instead and your first version should work as expected. maybe it is not clear enough and documentation could be improved..

**Comment by LoveOfLava** [comment]
Sorry I didn't understand what you mean ?

In the exemple it uses Gedmo\DoctrineExtensions::registerAbstractMappingIntoDriverChainORM
and you show me that's method.

**Comment by l3pp4rd** [comment]
change **registerAbstractMappingIntoDriverChainORM** to **registerMappingIntoDriverChainORM**

**Comment by LoveOfLava** [comment]
HI,

I tried this but I facing the same issue. 
I even tried my second method and I have the same issue :(

**Comment by l3pp4rd** [comment]
if `$entityManager->getRepository('Gedmo\Loggable\Entity\LogEntry');` does not work that means there is no such metadata. run command to clear **metadata:cache** and **schema:update**

**Comment by LoveOfLava** [comment]
Still didn't work :(

One question about the functionnality. A loggable entity still have the same id when they are update ?

I attach the connection code if it can help you 

//définit la racine du projet
define('ROOT', dirname(dirname(__FILE__)));

use Doctrine\ORM\EntityManager,
    Doctrine\ORM\Configuration,
    Doctrine\ORM\Tools\Setup,
    Doctrine\ORM\Proxy\Autoloader;
use Doctrine\Common\Annotations\AnnotationRegistry;

//charge l'autoload voir composer.json
require_once ROOT . "/librairies/autoload.php";

// First of all autoloading of vendors
$loader = require ROOT . "/librairies/autoload.php";
// gedmo extensions
$loader->add('Gedmo', ROOT . "/librairies/gedmo/doctrine-extensions/lib");

$tCheminEntites = array(
    ROOT . '/class/doctrine',
    ROOT . '/class/doctrine/entite/grilleResultat',
    ROOT . '/class/doctrine/entite/analyse',
    ROOT . '/class/doctrine/entite/matrice',
    ROOT . '/class/doctrine/entite/test',
);

foreach ($tCheminEntites as $sCheminEntite) {
    // autoloader for Entity namespace
    $loader->add('classeDoctrine', $sCheminEntite);
}



//Paramètre de la base de données
$tBddParametres = array(
    'driver' => 'pdo_mysql',
    'user' => 'root',
    'password' => '',
    'dbname' => 'easyprod',
    'charset' => 'UTF8'
);



Doctrine\Common\Annotations\AnnotationRegistry::registerFile(
        ROOT . '/librairies/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php'
);


AnnotationRegistry::registerAutoloadNamespace("Gedmo\Mapping\Annotation\\", "Gedmo/Mapping/Annotation");
AnnotationRegistry::registerAutoloadNamespace("Doctrine\ORM\Mapping\\", $tCheminEntites);
AnnotationRegistry::registerAutoloadNamespace("Gedmo\Mapping\Annotation\\", $tCheminEntites);

//Doctrine\Common\Annotations\AnnotationRegistry::registerAutoloadNamespace($tCheminEntites, $tBddParametres);


$bModeDeveloppement = true;
// globally used cache driver, in production use APC or memcached
$cache = new Doctrine\Common\Cache\ArrayCache;
// standard annotation reader
$annotationReader = new Doctrine\Common\Annotations\SimpleAnnotationReader();
$annotationReader->addNamespace('Doctrine\ORM\Mapping');
$cachedAnnotationReader = new Doctrine\Common\Annotations\CachedReader(
        $annotationReader, // use reader
        $cache // and a cache driver
);
// create a driver chain for metadata reading
$driverChain = new Doctrine\ORM\Mapping\Driver\DriverChain();
// load superclass metadata mapping only, into driver chain
// also registers Gedmo annotations.NOTE: you can personalize it
/* Gedmo\DoctrineExtensions::registerAbstractMappingIntoDriverChainORM(
  $driverChain, // our metadata driver chain, to hook into
  $cachedAnnotationReader // our cached annotation reader
  );
 */
Gedmo\DoctrineExtensions::registerMappingIntoDriverChainORM(
        $driverChain, // our metadata driver chain, to hook into
        $cachedAnnotationReader // our cached annotation reader
);


// now we want to register our application entities,
// for that we need another metadata driver used for Entity namespace
$annotationDriver = new Doctrine\ORM\Mapping\Driver\AnnotationDriver(
        $cachedAnnotationReader, // our cached annotation reader
        $tCheminEntites// paths to look in
);



// NOTE: driver for application Entity can be different, Yaml, Xml or whatever
// register annotation driver for our application Entity namespace
$driverChain->addDriver($annotationDriver, 'classeDoctrine');



//$oDefaultAnnotationDriver = $config->newDefaultAnnotationDriver($tCheminEntites);
// NOTE: driver for application Entity can be different, Yaml, Xml or whatever
// register annotation driver for our application Entity fully qualified namespace
//$driverChain->addDriver($oDefaultAnnotationDriver, 'classeDoctrine');
// general ORM configuration
$config = new Doctrine\ORM\Configuration;
$config->setProxyDir(sys_get_temp_dir());
$config->setProxyNamespace('Proxy');
$config->setAutoGenerateProxyClasses(false); // this can be based on production config.
// register metadata driver
$config->setMetadataDriverImpl($driverChain);
// use our already initialized cache driver
$config->setMetadataCacheImpl($cache);
$config->setQueryCacheImpl($cache);






// create event manager and hook preferred extension listeners
$evm = new Doctrine\Common\EventManager();
// gedmo extension listeners, remove which are not used
// loggable, not used in example
$loggableListener = new Gedmo\Loggable\LoggableListener;
$loggableListener->setAnnotationReader($cachedAnnotationReader);
$evm->addEventSubscriber($loggableListener);


//Paramètre de la base de données
$tBddParametres = array(
    'driver' => 'pdo_mysql',
    'user' => 'root',
    'password' => '',
    'dbname' => 'easyprod',
    'charset' => 'UTF8'
);

$oGestionnaireEntites = EntityManager::create($tBddParametres, $config, $evm);

$oGestionnaireEntites->getConfiguration()->addCustomHydrationMode('HydratorValeurSansNomColonne', 'boiteAOutils\HydratorValeurSansNomColonne');

**Comment by l3pp4rd** [comment]
well, this is hardly readable, use composer. try to check if LogEntry entity is available in metadata in your setup run `var_dump($driverChain->getAllClassNames());` and make sure you understand what you are doing, because your code is hardly understandable..

**Comment by LoveOfLava** [comment]
Hi,

On my var_dump I only have 'Gedmo\Translatable\Entity\Translation' 

I use on the composer require this line "gedmo/doctrine-extensions": "dev-master"

**Comment by l3pp4rd** [comment]
well, that is the reason, you do not have Gedmo LogEntry mapped in your metadata

**Comment by LoveOfLava** [comment]
It's strange because on when I call the function registerMappingIntoDriverChainORM it creates this array
        $annotationDriver = new DriverORM\AnnotationDriver($reader, array(
            __DIR__.'/Translatable/Entity',
            __DIR__.'/Loggable/Entity',
            __DIR__.'/Tree/Entity',
        ));

then   $driverChain->addDriver($annotationDriver, 'Gedmo');

**Comment by l3pp4rd** [comment]
probably these classes are not autoloaded..

**Comment by LoveOfLava** [comment]
Ok when I comment these lines

Doctrine\Common\Annotations\AnnotationRegistry::registerFile(
        ROOT . '/librairies/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php'
);

the $driverChain->getAllClassNames() return nothing I investigate

**Comment by LoveOfLava** [comment]
I investigate on the function getAllClassNames() in the line 
 if (in_array($sourceFile, $includedFiles) && !$this->isTransient($className)) {
the $this->isTransient($className) return true

**Comment by l3pp4rd** [comment]
ave you solved the issue?
