### ISSUE TITLE
[Translatable] Performance issues workaround

### ISSUE THREAD

**Issue by TriAnMan** [doctrine-extensions/DoctrineExtensions#1512]
Hey guys!

I've found a workaround for performance issues of Translatable. E.g. #860

Currently it applies for MySQL DB, PostgreSQL users should make little more things to make indexes working. I.e. use Gedmo v2.4.1 or less in case of b90d088a64715015720d669050ad0eabde169903 (see #1249).

So the main problem is type mismatch of a `foreignKey` field in a translations table (which is a varchar) and a primary key of translated entities tables which in most cases is integer. In this case MySQL silently converts one type to another and obviously not uses indexes. Postrges has more reliable behavior and warns the user about a type mismatch if there is no explicit typecasting. See #1249 (also #1168, #1142 and #1383)

Current behavior is satisfactory if there is no many translations (but for my mind such assumption is too naive). If there is more than 1 thousand of translations then a lot of performance problems arise, especially for queries with joins.

To workaround this problem we should harmonize types of columns. Obviously we can't force an autoincremental ID to be a string. So the only option left is to change a type of the `foreignKey` field. Here is a way to do this.
1. Override `\Doctrine\ORM\Mapping\ClassMetadataFactory`

```
<?php

namespace YourNameSpace;

use Doctrine\ORM\EntityManager;

class ClassMetadataFactory extends \Doctrine\ORM\Mapping\ClassMetadataFactory
{
    /**
     * @var EntityManager
     */
    private $em;

    /**
     * Workaround for private EntityManager field in \Doctrine\ORM\Mapping\ClassMetadataFactory::newClassMetadataInstance()
     * @inheritdoc
     */
    public function setEntityManager(EntityManager $em)
    {
        $this->em = $em;
        parent::setEntityManager($em);
    }

    /**
     * @inheritDoc
     */
    protected function newClassMetadataInstance($className)
    {
        return new \YourNameSpace\ClassMetadata($className, $this->em->getConfiguration()->getNamingStrategy());
    }
}
```
1. Override `\Doctrine\ORM\Mapping\ClassMetadata`

```
<?php

namespace YourNameSpace;

class ClassMetadata extends \Doctrine\ORM\Mapping\ClassMetadata
{
    /**
     * @inheritdoc
     */
    public function mapField(array $mapping)
    {
        // Fix performance issue with column types mismatch and lack of indexes optimization
        if (
             $this->name === 'Gedmo\Translatable\Entity\Translation'
             // If you have a custom translation entitny. See: https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#translation-entity
             || $this->name === 'YourNameSpace\CustomEntityTranslation'
        ) {
            if ($mapping['fieldName'] === 'foreignKey') {
                $mapping['type'] = 'integer';
                unset($mapping['length']);
            }
        }
        parent::mapField($mapping);
    }
}
```
1. Configure Doctrine to use your ClassMetadataFactory

```
doctrine:
    orm:
        entity_managers:
            default:
                class_metadata_factory_name:  YourNameSpace\ClassMetadataFactory
```
1. Create and apply a migration with `doctrine:migrations:diff` and `doctrine:migrations:migrate` console commands.
2. Have fun with blazing speed of your DB queries. (In some cases we have accelerated our queries in more than 500 times: 130 milliseconds instead of 72 seconds)

**Comment by l3pp4rd** [comment]
Hi, I think if you'd create an event listener which modifies metadata, the result would be the same and you would not need to extend ClassMetadata and it's factory. Probably it is worth adding it to the docs/translatable.md

**Comment by nino-s** [comment]
Perfect, helped me with my performance problem as well! An entity with 8 translatable fields lead to 8 left joins. A generated query without this ClassMetadataFactory last 5.5s, now it's only 0.1s.

**Comment by DanieleGBX** [comment]
Small note, this might break with UUID situations.

**Comment by Pixelshaped** [comment]
This is MANDATORY KNOWLEDGE. This translatable functionality **_does not scale well at all_** without it. Thanks @TriAnMan  for posting your solution!
