### ISSUE TITLE
Documentation for Sortable should be updated?

### ISSUE THREAD

**Issue by Ziiweb** [doctrine-extensions/DoctrineExtensions#1563]
Hi,

I have found annotations for sortable behaviour don't match those used in doc. Now we should use `SortablePosition` and docs said we should use just `Sortable`:

https://github.com/l3pp4rd/DoctrineExtensions/blob/master/lib/Gedmo/Sortable/Sortable.php

https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/sortable.md#sortable-entity-example

**Comment by Padam87** [comment]
Hi,

The documentation in the master branch refers to the upcoming 3.0 release. Please check the docs for the 2.4 branch.

A link for the current version would be great somewhere though.
