### ISSUE TITLE
Add XML mapping example for References

### ISSUE THREAD

**Issue by webdevilopers** [doctrine-extensions/DoctrineExtensions#1564]
In a new project I need to get the annotation example to work with XML mapping on the ODM side:
http://atlantic18.github.io/DoctrineExtensions/doc/references.html

In my case the use case is flipped. I have a `Branch` Entity (with annotations) in one bundle and an `Order` Document (with XML mapping) in the other bundle.

I have no idea how the XML mapping would have to look like. I tried some variations but none looks valid.
Can someone please post the correct mapping? Thanks in advance!

``` xml
<doctrine-mongo-mapping xmlns="http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping
                    http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping.xsd"
                        xmlns:gedmo="http://Atlantic18.github.io/DoctrineExtensions/schemas/orm/doctrine-extensions-3.0.xsd">

    <document name="Acme\Contract\DomainModel\Order" collection="orders">
        <field fieldName="id" id="true" strategy="UUID" />
        <field fieldName="orderStatus" type="string" />
        <field fieldName="orderNumber" type="string" />
        <field fieldName="customerId" type="integer" />
        <!--<field fieldName="customer">-->
            <!--<gedmo reference="referenceOne" inversed-by="orders" type="entity" class="Acme\ContractBundle\Entity\Branch" identifier="customer" />-->
        <!--<gedmo reference="referenceOne" inversed-by="orders" type="entity" class="Acme\ContractBundle\Entity\Branch" identifier="customerId" />-->
        <gedmo:reference reference="referenceOne" inversed-by="orders" type="entity" class="Acme\ContractBundle\Entity\Branch" identifier="customerId" />
        <!--<reference-one inversed-by="orders" type="entity" class="Acme\ContractBundle\Entity\Branch" identifier="customerId" />-->
        <!--</field>-->
        <!--<reference-one fieldName="customer" inversed-by="orders" type="entity" class="Acme\ContractBundle\Entity\Branch" identifier="customer" />-->
        <!--<reference-one fieldName="customer" inversed-by="orders" />-->
    </document>
</doctrine-mongo-mapping>
```

**Comment by l3pp4rd** [comment]
try to read it [from xml driver](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/References/Mapping/Driver/Xml.php) the extension was contributed, sadly documentation for xml mapping was not, if you cannot find it.

**Comment by webdevilopers** [comment]
I tried @l3pp4rd - as you can see from my various attempts in my code example. :/

I also talk a look at the YAML driver:
https://github.com/Atlantic18/DoctrineExtensions/pull/1262/files

I'm really unsure how / where to use `gedmo` e.g. `<gedmo:reference` or just `<reference` and `gedmo` somewhere else or just `<gedmo reference`.

Any hint?

**Comment by l3pp4rd** [comment]
gedmo is just an xml namespace, if you need to use xml, understand how it works first. take a look at any [example](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/sortable.md#xml-mapping-example) and you can see that initially it imports **gedmo** namespace for custom elements. The global scope import is used for doctrine orm namespace. So in result you have to prefix gedmo xml mappings with **gedmo:** prefix.

**Comment by l3pp4rd** [comment]
it may be possible that the xml driver is broken for reference extension, I doubt that someone had ever used it before.

**Comment by webdevilopers** [comment]
Yes possibe. Maybe @jwage or @frejfrej know.

I took a look at some other XML samples. The big different with `references" is that the Gedmo Annotation is related to class property that MUST NOT BE MAPPED to the ODM:
https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/references.md#annotations

```php
    /**
     * @ODM\String
     */
    private $name;

    /**
     * @Gedmo\ReferenceMany(type="entity", class="Entity\StockItem", mappedBy="product")
     */
    private $stockItems;
```

So I can't use the XML `<fieldName>`. Now I wonder If I can simply add a `<gedmo:reference`> root in the XML anywhere instead. See my last attempt:
https://github.com/Atlantic18/DoctrineExtensions/issues/1564#issue-148766564
