### ISSUE TITLE
Personal translations and @assert in entity

### ISSUE THREAD

**Issue by ktrzos** [doctrine-extensions/DoctrineExtensions#1566]
I'm using personal translations and [these files](https://gist.github.com/peter-gribanov/06aeffbf10b94b998fc3) in my **Symfony 3** application. I have a problem when I'm using `@Assert` for particular translatable file. For example:

```
class Page
{
    /**
     * @var string
     * @Gedmo\Translatable
     * @ORM\Column(name="content", type="text")
     * @Assert\Length(min="10")
     */
    private $content;
}
```

Lets assume, that I have site in two languages  (en - english, pl - polish) and above entity property is created by personal translations. Then, I have two inputs (one for each language): `content:en` and `content:pl`. When I'm submitting my form with one of those fields values shorter than 10 characters, Symfony creates an error corresponding to the `content` property, and `Form` component is showing me that error above all fields (not near the particular one).

![capture 41](https://cloud.githubusercontent.com/assets/14212721/14587439/7b55702e-04b3-11e6-9179-c3412902fa10.png)

What I must do to make Symfony (or Doctrine) to create this error for `content:en` field and not `content`?

**Comment by l3pp4rd** [comment]
Doctrine extensions is a library and it does not provide implementation details to all frameworks out there. I just mean this is not the right place to ask such questions. You should create the symfony forms in different way. It should be based on translation records and not on your entity having these translations, except the foreign key reference. Validation should apply to this custom form type model. There are so many ways people use translations, you have to adapt it to your use case, there is no silver bullet to all kinds of use cases.

**Comment by ktrzos** [comment]
First of all, I have just begun an adventure with Symfony 3. Learning all of this alone, having no mentor :). For couple of days I'm trying to create an admin panel with [EasyAdminBundle](https://github.com/javiereguiluz/EasyAdminBundle) which could have possibility to handle translatable entities. This is extremely difficult :/. For now, I achieved above (screenshot) and don't know what to do next cuz of this error and don't know where to get any help.

Secondly, I not exactly know what You wanted to tell me. Form is created by EasyAdmin and all the rest is done by DoctrineExtensions. Don't know who to ask to make above problem dissapear.

If this question shouldn't be here, then I'm very sorry and if no one can help, please close it.
