### ISSUE TITLE
[Sluggable] don't search for slugs similar to empty

### ISSUE THREAD

**Issue by MatTheCat** [doctrine-extensions/DoctrineExtensions#1578]
I took a long time yesterday understanding why a colleague could crash Apache just trying to insert a document into MongoDB. Turned out she wrote `//` as a placeholder in the field used for slug generation. When an empty slug is passed to [`getSimilarSlugs`](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Sluggable/Mapping/Event/Adapter/ODM.php#L22) the collection is searched for a slug which match the regex `/^/`. I thought this would return nothing but the exact opposite happens: the **entire** collection is returned and [`$result->toArray()`](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Sluggable/Mapping/Event/Adapter/ODM.php#L48)  exhaust memory.

Anyway it's not necessary to search for similar slugs when slug is empty.

**Comment by l3pp4rd** [comment]
usually empty slugs are not allowed. but ODM is less used in general, this type of bug is not that common. thanks for reporting.

**Comment by MatTheCat** [comment]
Throwing an exception would suffice. For now we have no way to prevent a crash if the generated slug is empty.

**Comment by Padam87** [comment]
How about extending the slug handler, and throwing the exception there?
