### ISSUE TITLE
[Translatable] Strange Issue with Query Hint and APC

### ISSUE THREAD

**Issue by calumbrodie** [doctrine-extensions/DoctrineExtensions#158]
I have a strange issue with the Translatable Query Hint when using APC as the metadata cache. I have my entity manager conifgured as follows.

``` php
<?php
$cache = new \Doctrine\Common\Cache\ArrayCache;
$DoctrineConfig->setMetadataCacheImpl($cache);
```

When using the Array Cache (as above) my application works as expected (including auto joining translation tables by using the Query Hint provided)

When I use the APC Cache for Metadata - but I manually clear the APC cache before each run, the application also works as expected

``` php
<?php
apc_clear_cache();
apc_clear_cache('opcode');
apc_clear_cache('user');
$cache = new \Doctrine\Common\Cache\ApcCache;
$DoctrineConfig->setMetadataCacheImpl($cache);
```

**THE PROBLEM**

The problem comes when I use APC caching, but don't clear it manually every time (i.e Using It would be doing in a live environment)

``` php
<?php
$cache = new \Doctrine\Common\Cache\ApcCache;
$DoctrineConfig->setMetadataCacheImpl($cache);
```

What I'm finding is that while everything is working as expected (including the query hint), there are a whole bunch of weird queries being generated (around translations) that are neither required, nor do they return any useful information. There are tons of these being generated on every request.

``` sql
SELECT m0_.content AS content0,
m0_.field AS field1 FROM color_translation m0_ 
WHERE m0_.foreign_key = '12451'
AND m0_.locale = '12451' 
AND m0_.object_class = '12451'
```

As you can see the `locale` and `object_class` fields are using the foreign key value instead of something sensible.
I'm going to look into this further next week when I have more time. In the meantime - any ideas?

*n.b I'm using yml mapping for all my entities, and annotation mapping for `Gedmo\Translatable\Entity` only.

**Comment by CreativeNative** [comment]
I have the same wired behaviour with doctrine APCu cache. @sfblaauw Do you have any updates?
With doctrine array cache or if I useQueryCache(false) it works perfect.

* APCu Version 4.0.6
* PHP Version 5.5.22
* Server Software Apache/2.4.12 (Ubuntu)
* Doctrine 2.4
* ZF2 2.3.5
