### ISSUE TITLE
Custom slug style

### ISSUE THREAD

**Issue by andrewpositiv** [doctrine-extensions/DoctrineExtensions#1580]
Hello, 
I want to create custom slug style:

Entity:
`/**
     * @Gedmo\Slug(fields={"title"}, style="withoutLowercase")
     * @ORM\Column(length=128, nullable=false, unique=true)
     */
    private $slug;
`
I expect such an effect:
Title: TestTitle
Slug: TestTitle

When I use "camel" style slug is: Testtitle
Any ideas?

**Comment by l3pp4rd** [comment]
Hi use custom transliterator, you can override it in listener. sluggable supports most common behavior, the rest needs to be customized on your own.
