### ISSUE TITLE
Uploadable with stream wrappers: "Unable to create "gs://bucketname/foldername" directory."

### ISSUE THREAD

**Issue by comxd** [doctrine-extensions/DoctrineExtensions#1581]
Hi,

I have a problem with the Uploadable extension when using a stream wrapper (Gaufrette). The Gedmo\Uploadable\UploadableListener::getPath() method call the Validator::validatePath($path); that trying to create the specified folder (mkdir). But, the Gaufrette\StreamWrapper::mkdir is not implemented and throw an Gedmo\Exception\UploadableInvalidPathException.

**Comment by l3pp4rd** [comment]
Hi, well, extension does not support these types of streams which may be S3 or whatever. you probably have to implement a custom listener for your use case

**Comment by comxd** [comment]
Ok thanks for our reply, but what about https://github.com/Atlantic18/DoctrineExtensions/pull/564 ?

This extension working good with this streams, it only fail about the mkdir call by the Validator::validatePath() method.

My currently temp "fix":
`<?php
namespace App\ORM\Extension\Uploadable;
use ...;

class UploadableListener extends \Gedmo\Uploadable\UploadableListener
{
    protected function getPath(ClassMetadata $meta, array $config, $object)
    {
        // code of the parent method...
        ...

        try {
            Validator::validatePath($path);
        } catch (UploadableInvalidPathException $e) {
            // IGNORED
        }

        $path = rtrim($path, '\/');
        return $path;
    }
}`

**Comment by l3pp4rd** [comment]
hm, in that case, probably we need to customize validation, but it is hard to know whether it uses filesystem storage or not. maybe a validatePath option could be set. I think maintainer of uploadable is off. so that is left to user contributions

**Comment by comxd** [comment]
+1 for validatePath option or symply check if the mkdir method is implmented?

**Comment by stephanvierkant** [comment]
#705

**Comment by comxd** [comment]
Do not close.
