### ISSUE TITLE
[Tree] Allow add own valid path types

### ISSUE THREAD

**Issue by TomasPilar** [doctrine-extensions/DoctrineExtensions#1585]
Hi,

I use PostgreSQL and I just discovered that sort by materialized path does not work properly. 

Here is my TreePath annotation:

``` php
/**
 * @Gedmo\TreePath(separator="/")
 * @ORM\Column(type="string", nullable=TRUE)
 * @var string
*/
protected $materializedPath;
```

PostgreSQL sort materializedPatch as string so instead of result like this: 

```
1/
1/2/
1/2/3/
1/22/
1/22/23/
1/4/
1/4/5/
1/4/5/6/
1/44/
```

i get:

```
1/
1/2/
1/22/
1/22/23
1/2/3/
1/4/
1/44/
1/4/5/
1/4/5/6
```

and `\Gedmo\Tree\RepositoryUtils::buildTreeArray` than build wrong tree. 

In PostgreSQL is module called [LTree](http://www.postgresql.org/docs/9.1/static/ltree.html) which order materialized path right. So I used [semin-lev/ltree-extension-bundle](https://github.com/semin-lev/ltree-extension-bundle) so i change TreePath annotation to:

``` php
/**
 * @Gedmo\TreePath(separator=".", startsWithSeparator=FALSE, endsWithSeparator=FALSE)
 * @ORM\Column(type="ltree", nullable=TRUE)
 * @var string
 */
protected $materializedPath;
```

and `InvalidMappingException` was [thrown](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Mapping/Driver/Annotation.php#L187).

So first solution is  add `ltree` to `$validPathTypes` or allow dynamic adding via some method. Second solution is rewrite `\Gedmo\Tree\RepositoryUtils::buildTreeArray` method and not to be dependent on the sort of results returned from database.

Thanks for reply.

**Comment by l3pp4rd** [comment]
Hi, I would recommend to simply override the repository method and sort it in plain php, it will be the most efficient way.

**Comment by Aweptimum** [comment]
This is honestly the only limitation keeping me from using this bundle, but I'd like to help in adding custom types.

Though, I'm not sure what a good way of implementing would be. Simple, probably bad ideas I have are: 
1. The Validator class needs an `add/removeValidType` method to be exposed to the user
2. The `isValid` functions might rely instead on the return type of `convertToDatabaseValue` for the field

If anyone wants to point me in the right direction, I'll try my hand at it
