### ISSUE TITLE
[Loggable] I want to specify a custom username for specific operations 

### ISSUE THREAD

**Issue by alexseif** [doctrine-extensions/DoctrineExtensions#1586]
I have some commands that create records, that I keep track of with an empty username.
Now I have a new command, that will update these records and I would like to single these out in the log.
Is that possible?

**Comment by l3pp4rd** [comment]
you can always set the "system" user when running in command line. otherwise just update the related log entries in database.

**Comment by alexseif** [comment]
Thank you, I'll go dig. 
So I shouldn't try and set it in the logger
