### ISSUE TITLE
Translatable not working correct on field types that are not string or text

### ISSUE THREAD

**Issue by do-web** [doctrine-extensions/DoctrineExtensions#1591]
If my doctrine field type is array the translateable returns the serialized array string and not the array.

`
    /**
     * @ORM\Column(name="multi", type="array", nullable=true)
     * @Gedmo\Translatable
     */
    protected $multi;
`

**Comment by l3pp4rd** [comment]
hi, can you update [test case](https://github.com/l3pp4rd/DoctrineExtensions/blob/master/tests/Gedmo/Translatable/MixedValueTranslationTest.php) with a failing translation type?
