### ISSUE TITLE
TreeSlugHandler - uniqueness referring only on the first slug part

### ISSUE THREAD

**Issue by ikodev** [doctrine-extensions/DoctrineExtensions#1595]
Hi,

Is there a possibility to configure the uniqueness of a TreeSlugHandler by referring only on its first part/slug ?

I would like this : 
/mick-brien/sub-toto/folder
/**mick-brien-1**/sub-toto/folder
/**mick-brien-2**/sub-toto/folder
/geoffroy-george/sub-toto/folder
/**group-toto**/sub-toto/folder
/**group-toto-2**/sub-toto/folder

here I have :
- 2 users (User entity) with the same names : mick brien (two user slugs)
- 2 groups (Group entity) with the same names : toto (two group slugs)

Groups and Users can have folders (Folder Entity).
Folders have a TreeSlugHandler based on the folder name which is filled manually by a process that recover user slugs and group slugs.

Here is my annotation code on Folder Entity (slug property) :

``` php
/**
     * @Gedmo\Slug(handlers={
     *      @Gedmo\SlugHandler(class="Gedmo\Sluggable\Handler\TreeSlugHandler", options={
     *          @Gedmo\SlugHandlerOption(name="parentRelationField", value="parent"),
     *          @Gedmo\SlugHandlerOption(name="separator", value="/")
     *      })
     * }, separator="-", unique=true, updatable=true, fields={"name"})
     * @Doctrine\ORM\Mapping\Column(type="string", unique=true)
     */
    protected $slug;
```

So, I suppose I could not use relations in this annotation cause my slugs are based on differents values types (user or group). I have check an [issue is opened](https://github.com/Atlantic18/DoctrineExtensions/issues/1058) but it seems not fully resolve my need.

Thanks for your help :)

**Comment by l3pp4rd** [comment]
there are no options to support your needs. the code is quite complex already and I do not think I would ever find time to implement this. unless someone else takes over extension maintenance. I only try to maintain extensions to be stable at the moment. if you really need that behavior, the only choice is - custom impl.
