### ISSUE TITLE
[Sluggable] Custom entity manager

### ISSUE THREAD

**Issue by Tetdoss** [doctrine-extensions/DoctrineExtensions#1596]
Hello, i have my custom entity manager and i wonder if it is possible to use it with sluggable ?

If not, here my issue :

I have a table like this

slug |config_id
foo | 1

When i add a row (foo,2) , slug generate :

slug |config_id
foo | 1
foo-1 | 2

But i'd like an unicity based on the 2 columns like that

slug |config_id
foo | 1
foo | 2
foo-1 | 1
........................

Thank you if you can help me !

**Comment by l3pp4rd** [comment]
read the sluggable documentation, you can specify the fields you wish to slug.

**Comment by Tetdoss** [comment]
Thanks for your answer l3pp4rp,
Yes I read it but it generates me a slug like <config_id>/foo

I don't like something like

1/foo
2/foo
1/foo-1

But I want

foo
foo-1
foo-3

I hope I was clear :/

**Comment by l3pp4rd** [comment]
and how your entity mapping looks like?

**Comment by Tetdoss** [comment]
It looks like : 

    /**
     * @ORM\ManyToOne(targetEntity="ZC\CMS\SiteBundle\Entity\Config")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    protected $config;

    /**
     * @Gedmo\Slug(handlers={
     *      @Gedmo\SlugHandler(class="Gedmo\Sluggable\Handler\RelativeSlugHandler", options={
     *          @Gedmo\SlugHandlerOption(name="relationField", value="config"),
     *          @Gedmo\SlugHandlerOption(name="relationSlugField", value="id"),
     *          @Gedmo\SlugHandlerOption(name="separator", value="/")
     *      })
     * }, fields={"title"})
     * @ORM\Column(length=128)
     */
    private $slug;

**Comment by l3pp4rd** [comment]
slug handlers cannot be configured to match your expectations. only slug **fields** are first combined then checked unique constraint. Slug handlers does not support that behavior, you'll have to make something custom.

**Comment by Tetdoss** [comment]
Ok then, thank you, i'll keep my little hack
