### ISSUE TITLE
How to add or change from child root item

### ISSUE THREAD

**Issue by duskohu** [doctrine-extensions/DoctrineExtensions#1617]
Hi I use nested for router where I have basic structure:

```
root
-- page1
-- page2
---- subpage1
------ n level of subpages
---- subpage2
-- page3
......
```

is possible? 
**when I create new item:**
1. set as root
2. all old root subitems set as children for new root
3. old root set as child of new root

**when I edit anny child item:**
1. set as root
2. all old root subitems without actual item set as children for new root
3. old root set as child of new root

With this process I can create different homepage, or change any child item as homepage.
It is possible for nested architecture?

**Comment by l3pp4rd** [comment]
don't use TreeRoot in this case
