### ISSUE TITLE
[Tree] How to clone categories ?

### ISSUE THREAD

**Issue by eved42** [doctrine-extensions/DoctrineExtensions#1637]
Hello,

I use the Tree Extension to build catalogs tree structures.
It works well but, I would like to know if it's possible to clone a tree ?

I know I have to extends Symfony `__clone()` function but I don't know how to proceed for children categories, roots, etc.

I wrote this in my Level entity (= category) : 

```

public function __clone() {
    if ($this->id) {
        $this->id = null;
    }
}
```

When I create a new catalog, I create a new root Level (which is hidden for the user) in order to manage the order of each level (root category can't be moved).

I created a form to select the catalog tree that the user wants to copy. Here is my `duplicateAction()` in the CatalogController : 

```
// $catalog is the catalog in which I want to import the tree structure of another catalog.

if ($form->isSubmitted() && $form->isValid()) {
    // get catalog to copy
    $origin = $form->getData()['catalog'];

    // get root level
    $root = $catalog->getLevels()[0];

    foreach ($origin->getLevels() as $level) {
        // duplicate every level except root
        if ($level->getLevel() !== 0) {
            $clone = clone $level;
            $clone->setRoot($root->getId());
            $clone->setCatalog($catalog);

            $catalog->addLevel($clone);
        }
    }

    # update database
    $em->flush($catalog);

    # success message
    $this->addFlash('notice', 'Tree structure has been duplicated successfully !');

    # redirection
    return $this->redirectToRoute('catalog_tree', array('code' => $code));*/
}
```

I don't know how to change the parent_id for each level. If I want to clone each level, we have to clear the id...

Any idea ?

**Comment by fsevestre** [comment]
You might take a look at this repository https://github.com/myclabs/DeepCopy.
We used it to clone a lots of entities (including trees managed by the `Tree` extension of this repo) and it work as excepted.

**Comment by eved42** [comment]
I tested this bundle but I have an error : 
`Property Proxies\__CG__\AppBundle\Entity\CatalogLevel::$id does not exist `

CatalogLevel is my "tree" entity. If you use it, maybe you can help me...

I have a catalog that has many levels. These levels can have children levels. Each level can have one or many products.

So, `Catalog` has an ArrayCollection of `CatalogLevel`.
`CatalogLevel` has an ArrayCollection of `CatalogProduct`.

In my controller, I want to duplicate just the levels of a catalog, so I wrote this : 

```
// $catalog is the catalog in which I want to import the tree structure of another catalog.

if ($form->isSubmitted() && $form->isValid()) {
    // get catalog to copy
    $origin = $form->getData()['catalog'];

    // callbacks
    $cbCode = function() { return $code; };
    $cbCat = function() { return $catalog; };

    $clones = new ArrayCollection();
    foreach ($origin->getLevels() as $level) {
		$deepCopy = new DeepCopy();
		// clear id
		$deepCopy->addFilter(new SetNullFilter(), new PropertyNameMatcher('id'));

		// replace catalog code
		$deepCopy->addFilter(new ReplaceFilter($cbCode), new PropertyNameMatcher('catalogCode'));

		// replace catalog object
		$deepCopy->addFilter(new ReplaceFilter($cbCat), new PropertyNameMatcher('catalog'));

		// copy the products of the level
		$deepCopy->addFilter(new DoctrineCollectionFilter(), new PropertyTypeMatcher('Doctrine\Common\Collections\Collection'));

		// copy the level
		$copy = $deepCopy->copy($level);

		$clones->add($copy);
    }

    // [...]
}
```
Is it a correct way to use this bundle ? I don't understand very well the documentation...

**Comment by Perni1984** [comment]
@fsevestre: Is there a way to persist the whole object graph of the tree in the db with a persistAll()? 

I succeded in cloning the tree structure, but I only get new id's when I persist each TreeNode in the db. Is this expected?
