### ISSUE TITLE
Can unique_base also have non-mapped properties and/or callback functions?

### ISSUE THREAD

**Issue by taylankasap** [doctrine-extensions/DoctrineExtensions#1645]
I think the question is clear. Is there a reason for `unique_base` to only accept mapped properties?
This feature would also fix other issues which want `entity.relation.moreRelation` as `unique_base`, which could be solved with callbacks.

**Comment by l3pp4rd** [comment]
this feature was contributed, if you can make it functionally correct with test cases, that could be accepted, there are no active maintainers currently concerning new features.
