### ISSUE TITLE
[Timestampable] Set default value of createdAt/updatedAt at database-level

### ISSUE THREAD

**Issue by ste93cry** [doctrine-extensions/DoctrineExtensions#1661]
The timestampable fields do not have a default value set at the database-level. While it's not a real problem, if you want to insert some records manually (e.g. with phpMyAdmin) or with a custom query you always need to specify the values of those fields. My proposal is to use the `default` option of the `Column` class to set the default value of the field to `CURRENT_TIMESTAMP`. After googling that function it seems that it's standard SQL and so it's supported by all major database vendors. I could prepare a PR if you agree on my considerations.

**Comment by l3pp4rd** [comment]
Hi, the default value is `null` and it is proper value since the timestamp is not set. timestampable sets timestamp based on current options. There won't be any other default value as far as this library is concerned.

**Comment by ste93cry** [comment]
> timestampable sets timestamp based on current options

As I set CURRENT_TIMESTAMP on my entities, could you explain better to me if there is any drawbacks in having done it?

**Comment by l3pp4rd** [comment]
extend the listener and do whatever you want, having default value any other than null, does not make any sense to most of the library users and there won't be any other option for 1 out of 1000 use cases - this is a common behavior library. having more options confuses people and makes it harder to maintain.

**Comment by ste93cry** [comment]
> having default value any other than null, does not make any sense to most of the library users

The field is set as non-nullable by default since you did not set `nullable` to `true` in the column options, having a default value at database-level for me is what as an user I would expect (as it would be something I expect being the field not nullable). The field is populated anyway with a value when the entity is saved or updated, so the behaviour of the library does not change. The only thing that changes is that if an user inserts a record not using the entity manager (maybe because he uses a custom query), he won't have to specify those values.

 - this is a common behavior library. having more options confuses people and makes it harder to maintain

I can't see how adding a default value would make harder to maintain the library, but I got the point you won't change mind, so no problem

**Comment by ndyakov** [comment]
Bumping this up, if you add the extension on a later stage when you have records, the database won't accept null as value to populate the currently added records.
