### ISSUE TITLE
Unique slug suffix index started from 1, not empty prefix

### ISSUE THREAD

**Issue by tttptd** [doctrine-extensions/DoctrineExtensions#1663]
Sorry for my english).

I have problem with sluggable behavior. For example:

MainTable has slug: "mielovoi-liettieringh"
SecondTable, OneToMany-relation table's slug must have slug from MainTable + unique index started from 1, not from empty index:

mielovoi-liettieringh-1
mielovoi-liettieringh-2
mielovoi-liettieringh-3
...

But i have:

mielovoi-liettieringh
mielovoi-liettieringh-1
mielovoi-liettieringh-2
...

How i can do that?

**Comment by l3pp4rd** [comment]
Hi, this is expected behavior, if you want something different fork extensions and adapt

**Comment by tttptd** [comment]
Okay, thank you for reply. I think, maybe i missed something.
