### ISSUE TITLE
SoftDeleteable: allow timestamp instead of \DateTime

### ISSUE THREAD

**Issue by dontub** [doctrine-extensions/DoctrineExtensions#1664]
It should be possible to use a timestamp instead of \DateTime in SoftDeleteable as it is possible in Timestampable.

**Comment by stephanvierkant** [comment]
Just checking: you mean Unix time (also known as POSIX time or Epoch time)?

**Comment by dontub** [comment]
> Just checking: you mean Unix time (also known as POSIX time or Epoch time)?

Exactly.
