### ISSUE TITLE
Injecting service into Filename generator

### ISSUE THREAD

**Issue by toby-griffiths** [doctrine-extensions/DoctrineExtensions#1672]
I'm needing to inject the Doctrine entity manager into the Filename Generator for the Uploadable file entities in my project, but as the filename generator uses a static class method call, there's no service definition in my project.

Is there any way of of using an instantiated object as the filename generator, at all?

**Comment by l3pp4rd** [comment]
I understand these static methods gets in your way. but currently uploadable uses a generator configuration per uploadable file. For this reason extension library must construct the generator and in that case we cannot know how it should be constructed as this library, does not have a dependency injection container. If you can make an option to UploadableListener which registers a callable which could be used instead as default and make a PR that could be accepted.
