### ISSUE TITLE
[Translatable] Defaut locale and join

### ISSUE THREAD

**Issue by Maraumax** [doctrine-extensions/DoctrineExtensions#1678]
I actually have one locale : fr.

When i get all entities i have one query per entities but the original query is good :

```
SELECT 
  p0_.id AS id_0, 
  t1_.content AS title_1, 
  t2_.content AS description_2, 
  p0_.url AS url_3, 
  p0_.image AS image_4, 
  p0_.active AS active_5, 
  p0_.slug AS slug_6, 
  p0_.date_created AS date_created_7, 
  p0_.date_updated AS date_updated_8, 
  p0_.site_id AS site_id_9 
FROM 
  partners p0_ 
  LEFT JOIN partners_translations t1_ ON t1_.locale = 'fr' 
  AND t1_.field = 'title' 
  AND t1_.object_class = 'AppBundle\\Entity\\Partner' 
  AND t1_.foreign_key = p0_.id 
  LEFT JOIN partners_translations t2_ ON t2_.locale = 'fr' 
  AND t2_.field = 'description' 
  AND t2_.object_class = 'AppBundle\\Entity\\Partner' 
  AND t2_.foreign_key = p0_.id 
ORDER BY 
  t1_.content ASC
```

Explain : get all entities (Partner) and field title and description for local fr.

But after this i have one query for all entites :
`SELECT p0_.content AS content_0, p0_.field AS field_1 FROM partners_translations p0_ WHERE p0_.foreign_key = ? AND p0_.locale = ? AND p0_.object_class = ?`

All my information are in first query, with another?

I tried:
- change default local
- enable / disable fallback
- enable / disable cache

I added in my repository:

```
        $query->setHint(
            Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );

        $query->setHint(TranslatableListener::HINT_TRANSLATABLE_LOCALE, $locale);
```

The only way to get it working is to use default symfony local "en" and set HINT_TRANSLATABLE_LOCALE to "fr". In this case i only get one query.

**Comment by l3pp4rd** [comment]
Hi, in order to have fallbacks on translation query walker, you have to set a hint.

``` php 
       $query->setHint(
            Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );

        $query->setHint(TranslatableListener::HINT_TRANSLATABLE_LOCALE, $locale);
        $query->setHint(TranslatableListener::HINT_FALLBACK, true);
```

By default it does not fallback as far as I remember
