### ISSUE TITLE
Camel and empty separator

### ISSUE THREAD

**Issue by Valantir007** [doctrine-extensions/DoctrineExtensions#1681]
If I have field with value "Paczka w ruchu", separator is empty, I got slug "PACZKAWRUCHU". Is it possible to got "PaczkaWRuchu"?

My orm configuration is:

`<field name="name" type="string" column="name" />
<field name="slug" type="string" column="slug">
      <gedmo:slug unique="true" updatable="false" separator="" fields="name" style="camel"/>
</field>`

**Comment by adrx** [comment]
I have exactly the same question! I hope someone can answer!
