### ISSUE TITLE
Sluggable -> Document -> date type + dateFormat

### ISSUE THREAD

**Issue by KASTINpl** [doctrine-extensions/DoctrineExtensions#1707]
```
/** @MongoDB\Document() */
class Document {
// [..]
/**
     * @Gedmo\Slug(fields={"title", "createdAt"}, unique=true, separator="-", dateFormat="Y")
     * @MongoDB\Field(type="string")
*/
protected $slug;
/**
     * @var \DateTime $createdAt
     * @MongoDB\Field(type="date", name="created_at")
     * @Gedmo\Timestampable(on="create")
*/
protected $createdAt;
}
```

error:
`Cannot use field - [createdAt] for slug storage, type is not valid and must be 'string' or 'text' in class - Document`

https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Sluggable/Mapping/Driver/Annotation.php#L47
for mongo should be
```
protected $validTypes = array(
// ...
        'date',
// ...
);
```

**Comment by l3pp4rd** [comment]
not allowed means not allowed. if you want to manage that type, fork extensions. why, because there are tons of issues converting dates or datetimes to string associated to timezones and formats and etc..
