### ISSUE TITLE
Best way to Extend LogEntry Entity to add new indexes

### ISSUE THREAD

**Issue by mbates** [doctrine-extensions/DoctrineExtensions#1712]
What is the best way to setup some new indexes on the ext_log_entries table?

At the moment I have just added them directly to my database, but that means that Doctrine Migrations wants to remove them every time I run a diff.

I may be making my life more difficult by using the StofDoctrineExtensionsBundle, but I'm having to override lots of classes to do this which is causing me lots of other problems. So I think I must be overlooking something obvious as this seems like it should be a pretty simple thing to do.

Thanks

**Comment by l3pp4rd** [comment]
you can use an abstract mapped superclass and extend it, add your own indexing [like in this example for translatable](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/translatable.md#translation-entity) and call it for example MyLogEntry
