### ISSUE TITLE
Translatable does a lot of queries even with HINT_CUSTOM_OUTPUT_WALKER

### ISSUE THREAD

**Issue by immae** [doctrine-extensions/DoctrineExtensions#1714]
I have the following strange behavior:
In my entity repository, I have a function of the form
```
public function getEntities($property) {
  return $this
    ->createQueryBuilder('e')
    ->where('e.property = :property')
    ->setParameter('property', $property)
    ->getQuery()
    ->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker')
    ->getResult();
}
```
This function is called several times in the process. I clearly see the effect of the setHint in the doctrine debug panel, in the sense that *each* call to that function makes a "big" query fetching all the needed translations.

However, only the first call to that function is correctly used, that is, all the subsequent calls are making the "big" query, but each use of an entity then remakes translation queries to the database, as if the setHint were absent.
I also changed the order of the calls, and it's always the first one that "works" correctly.

Did I miss anything in the configuration? The fact that the first call is correctly used seems to mean that I configured it correctly, but maybe I missed something else?

Please ask for more details if I forgot something.

**Comment by immae** [comment]
Forgot to mention: I use v2.4.13

**Comment by immae** [comment]
I finally found the origin of the problem:
The "walkSelectStatement" function in lib/Gedmo/Translatable/Query/TreeWalker/TranslationWalker.php doesn't get called when the Doctrine query is cached, which it is by default. Then, the query is reused (hence the "big" query), but the Translatable hydrator doesn't get called, hence the subsequent calls to fill the hole.
Maybe the cache should be disabled by the walker to avoid that kind of behavior? (more generally it seems preferrable to me not to cache that kind of select statement)
As far as I can see, there is no way to ask for the query *not* to go to the cache (we can only ask for it not to get fetched), so I guess it's too late when Translatable comes to the scene. I may have missed something, so I let you decide whether to keep the issue open or not

**Comment by l3pp4rd** [comment]
add a hint for locale, because it will cache only the first locale you call it with. cache key must be unique

**Comment by immae** [comment]
hmm the thing is, I'm calling for different values of a property that is not the locale, so the cached query is correct. The problem here is that having a cache "removes" the Translatable hydration process

**Comment by l3pp4rd** [comment]
it should not require hydration as far as I remember, maybe you can try to replicate that test in unit tests? Because I think there is a cached query test.

**Comment by l3pp4rd** [comment]
is other caching working, like simple key value cache you are using, try to test it. So many people would complain if that would not work. Most problems in php are cache related.

**Comment by immae** [comment]
There is a hydration done after the query. I went through the code to find the origin of the problem given above. And I confirm that if I disable the "query cache" (with `->useQueryCache(null)` just after  the getQuery() in the given example), everything starts working as expected (only one query per "function call" is done instead of one per entity). Note that here the problem is specific to the case where you do twice the same "prepared query" with different parameters, otherwise we have a cache miss and the problem doesn't show up. That would explain the little number of people seeing that issue.

**Comment by immae** [comment]
I'll try to create a unit test that fails for that specific case.

**Comment by immae** [comment]
Ok I give up I don't have the required level to write that test. Here is what I was trying to do:
If you look at the file `tests/Gedmo/Translatable/TranslationQueryWalkerTest.php`, function "shouldHandleQueryCache" (which I think is incorrect by the way, the last `$q->getArrayResult()` should probably be `$q2->getArrayResult()`, but it's the same for my claim).

Then you expect to do exactly two "select" (with left joins), one for each query. Here, you will actually do 3, unless you put `$q2->useQueryCache(null)`: two with joins and one that queries only the translation table.
I have no proof for that except that it corresponds exactly to what I see in the symfony profiler, but I'm not able to count or extract those queries to prove it.

**Comment by pekarja5** [comment]
The problem is caused by hydration mode change inside translation walker https://github.com/Atlantic18/DoctrineExtensions/blob/113a5c0494254d2e29d8b4ebc622dba0c8abe922/lib/Gedmo/Translatable/Query/TreeWalker/TranslationWalker.php#L118-L143

The translation walker changes hydration mode inside the walkSelectStatement method, which is actually called by [ORM query parser](https://github.com/doctrine/orm/blob/ed61f0e64777378050d255caaadb8c67ecf85a70/lib/Doctrine/ORM/Query/Parser.php#L369). As parser is used only for parsing DQL to AST and the cached query is already parsed the walker is not used, hydration mode remains unchanged, therefore the postLoad event on all hydrated entities will result in additional database queries for translations. 
Disabling query cache works as a workaround as the parser is always used.

**Comment by elninopl** [comment]
> I was having the same issue. Setting the locale hint, and everything as documented in the docs. But it was still making a lots of queries during hydration.
> 
> `$query->getSQL()` was giving me the right query but the results were all wrong. Turns out when you are using custom sql walker it doesnt set the skip bit to false in the listener, which goes ahead and does all the queries anyhow.
> 
> This is how I am getting around it.
> 
> ```
> $listener = $this->get('gedmo.listener.translatable');
> $skip = $listener->isSkipOnLoad();
> 
> $listener->setSkipOnLoad(true);
> $foods = $repo->getAll($filters);
> $listener->setSkipOnLoad($skip);
> ```

I had the same problem. Language hint is present, main query correct (with joins to translations). Still one extra query for each record. This workaround works perfectly but maybe it's possible to fix it?
