### ISSUE TITLE
Sluggable Translatable questions, slug not updated when updating the entity

### ISSUE THREAD

**Issue by nacholibre** [doctrine-extensions/DoctrineExtensions#1716]
First of all, thanks for the great library, it's really useful.

I'm using symfony and the stof wrapper. I have the following scenario. Here is my entity:
```
class Page {
//...
    /**
     * @Gedmo\Translatable
     * @ORM\Column(name="name", type="string", unique=true, length=255)
     */
    protected $name;

    /**
     * @Gedmo\Translatable
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(length=128, unique=true)
     */
    protected $slug;

//...
}
```

Upon creation, the slug is translated and added to the table with translations. But when I update the entity field `name` slug is no longer updating in the translations table. How can I fix this?

**Comment by l3pp4rd** [comment]
Hi, thanks, you have the unique=true by default, see [here](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Mapping/Annotation/Slug.php#L25) set it to false in your annotation and read the docs for similar questions.

**Comment by l3pp4rd** [comment]
maybe you change the translation in different language? it will translate slug only for default locale in this case. not sure if unique=true constraint on field has something to do with it, try changing it to false and see what happens

**Comment by nacholibre** [comment]
Nope, it's not updating. Another thing, when trying to persist multiple translations like so

```
$repository->translate($article, 'title', 'de', 'my article de')
    ->translate($article, 'content', 'de', 'content de')
    ->translate($article, 'title', 'ru', 'my article ru')
    ->translate($article, 'content', 'ru', 'content ru')
;
```

slug is not generated for the other locales except the default one. How can I fix this?

**Comment by l3pp4rd** [comment]
you can't because translations are stored in separate entities. in general when sluggable and translatable is combined on the same field, you have many limitations. it would be complex to manage it like translated url slugs, unless you have something custom implemented on top of it.

**Comment by jmariller** [comment]
hi @l3pp4rd, first of all thanks a lot for those extensions, they are really very helpful :)

I would like to come back to what you wrote quite some years ago:
> you can't because translations are stored in separate entities. in general when sluggable and translatable is combined on the same field, you have many limitations. it would be complex to manage it like translated url slugs, unless you have something custom implemented on top of it.

Would there be any solution to fix this? I would really like to have a slug field that also gets translated, but it does not work and I believe I tried all possible options listed in the documentation. Thanks a lot in advance for any hints.
