### ISSUE TITLE
uploadables

### ISSUE THREAD

**Issue by iometrine** [doctrine-extensions/DoctrineExtensions#1729]
Hi,

I try to implement this bundle with multi uploadables files

but when i run command to generate Entity or to update the database an error occurs:

 [Doctrine\Common\Annotations\AnnotationException]
 [Semantical Error] The annotation "@Gedmo\Mapping\Annotation\Uploadables" in class AppBundle\Entity\MyOwnClass does not exist, or could not be auto-loaded.

Thank you

**Comment by stephanvierkant** [comment]
Did you add `use Gedmo\Mapping\Annotation as Gedmo;` to your file?

**Comment by iometrine** [comment]
Yes, this is my code below
```
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Doctrine\ORM\Event\LifecycleEventArgs;

/**
 * @ORM\Table(name="composant")
 * @ORM\Entity
 * @Gedmo\Uploadables(configurations={
 *  @Gedmo\Uploadable(identifier="name1",path="uploads", callback="myCallbackMethod", filenameGenerator="SHA1", allowOverwrite=true),
 *  @Gedmo\Uploadable(identifier="name2",path="uploads", callback="myCallbackMethod", filenameGenerator="SHA1", allowOverwrite=true),
 *  @Gedmo\Uploadable(identifier="name3",path="uploads", callback="myCallbackMethod", filenameGenerator="SHA1", allowOverwrite=true) 
 * })
 * @ORM\HasLifecycleCallbacks() 
 */
class Composant implements Translatable
{
   ...
```

I have the impression that I do not have the correct version of gedmo
I'm reading : https://github.com/Atlantic18/DoctrineExtensions/pull/1213/files?diff=split&short_path=04c6e90

And when I look in my vendor repository i didn't find any uploadables files

**Comment by iometrine** [comment]
when i use composer require stof/doctrine-extensions-bundle
I got   "stof/doctrine-extensions-bundle": "^1.2" in my composer.json

Do i need to force with master branch ?

**Comment by iometrine** [comment]
I understood, I use stof for my symfony project
and in the composer stof use ->         "gedmo/doctrine-extensions": "^2.3.1"

Can i upgrade the version manually and is it possible ?
