### ISSUE TITLE
Sortable - handle position change with events

### ISSUE THREAD

**Issue by houpli** [doctrine-extensions/DoctrineExtensions#1730]
Hi,

I have a sortable Entity.

Entity A, position 0
Entity B, position 1

When I update A with position 1, the new position is 1 and B has the position of A, 0.

I can handle position change of A with an event listener but no event is triggered for B.

I would like update status of my entites A and B if the position changes. It works for A but not for B.

Thank you and sorry for my english.

**Comment by l3pp4rd** [comment]
extensions will not have any new features
