### ISSUE TITLE
ZF2 Form integration (translatable)

### ISSUE THREAD

**Issue by hattingen** [doctrine-extensions/DoctrineExtensions#1740]
I might need some help.
Is there any example code on how to integrate translatable into a ZF2 form?
Recognition of translatable fields, populating fields, persisting....

Beeing thankfull for any advice

**Comment by l3pp4rd** [comment]
extensions is a library, it has nothing to do with web frameworks, there is no such documentation in extensions, try to google it, or implement they way it works for you

**Comment by hattingen** [comment]
Sure, I know and I am working on it. Just thought that I can't be the first dealing with it.
Thx for your great work.
