### ISSUE TITLE
Feature Request: Timestampable - Invertable on="change"

### ISSUE THREAD

**Issue by JProffitt71** [doctrine-extensions/DoctrineExtensions#1741]
I came across [issue #1281](https://github.com/Atlantic18/DoctrineExtensions/issues/1281) and wanted to submit a feature request with a class of valid use-cases.

In my applications, it is very common to have a set of properties related directly to the entity in the context of its domain, and then some (usually 2 or 3) metadata properties and are only used by the application internally.

When we want to know when an entity was last updated, typically we want to know when any of its domain properties were modified, which means we can't use the on="update" mapping which would change as soon as the metadata changed. Instead we need to use the on="change" mapping and list all of the domain properties. Then whenever we touch the entity, we need to make sure to update the on="change" listener too or suffer subtle bugs.

This is really inefficient because typically there are many more domain properties than metadata properties, and we change them more often (since they relate more to the public api of the entity).

If we add a boolean "invert" option or a "not_field" option or something to that effect to the on="change" listener, we can avoid this issue with minimal added complexity. I can submit a pull-request that implements this behavior.

To the argument that this needlessly complicates the options, any developer looking to integrate DoctrineExtensions should already be at a level where they will be able to understand that on="change" has an alt behavior that works like a blacklist instead of a whitelist, and know when that might be useful.

**Comment by l3pp4rd** [comment]
it sounds like you need something different like [audit logs](https://github.com/DATA-DOG/DataDogAuditBundle) it is easy to extract it for any framework. extensions will not have new features, unless someone else starts to maintain it ;)

**Comment by JProffitt71** [comment]
Audit logs are definitely overkill for this purpose. I would be introducing a whole framework when the only thing I want to do is make using the on="change" listener more convenient in one case.

I can understand not wanting to mess with something that's working for the typical case when the maintenance is demanding. That is unfortunate.

**Comment by l3pp4rd** [comment]
you can make a custom listener, timestampable uses trackable listener which is extended by blameable and etc, you can have a look and make your own easily, maybe without annotation support, only interface. that is an easy task. I do not work with php 2 years already, maintaining new features is the last thing I want :)
