### ISSUE TITLE
Locale en not retrieving translations

### ISSUE THREAD

**Issue by stefanenache89** [doctrine-extensions/DoctrineExtensions#1746]
Hi i have a problem with locale "en", if i set locale in db translation table to en translation isn't retrieved(locale from php is set to en), if i set it to "en_en"  it works (locale from php is set to en_en), for other languages also it woks ex:. for "ru", "de" maybe i'm missing some config.. can someone give me some advice?

**Comment by l3pp4rd** [comment]
this has nothing to do with extensions. whatever you set as locale in listener - you have it.. even if you name it **my-alien-locale**

**Comment by bravik** [comment]
Still it doen't work with 'en' locale in particular. If I set 'uz' for example - it works, 'en_US' - works, but 'en' is ignored for some reason.
