### ISSUE TITLE
[SoftDeleteable] Form with deleted relation exception

### ISSUE THREAD

**Issue by Glideh** [doctrine-extensions/DoctrineExtensions#1759]
Trying to display a form bound to an `objectA` linked to a soft deleted `objectB` selectable in a list will throw an exception.

Let's see some code:

```php
class EntityA
{
    /**
     * @ORM\ManyToOne(targetEntity="EntityB")
     */
    private $entityB
//...
```

```php
/**
 * ...
 * @Gedmo\SoftDeleteable(fieldName="deletedAt")
 */
class EntityB
//...
```

```php
class EntityAType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('entityB');
//...
```

```php
$objectA->setEntityB($objectB);
$em->delete($objectB);
$this->createForm(EntityAType::class, $objectA)
```

Gives

> Entity of type 'AppBundle\Entity\EntityB' for IDs id(42) was not found

... since the transformer can't get `objectB` anymore

**Is there a simple way to silently show the form just without `objectB` in the list ?**
I need this behavior in many places of my current application.

**Comment by l3pp4rd** [comment]
Hi, extensions do not provide ways to deal with relations of softdeleted items, it simply would be too cumbersome to implement and would not cover all possible options. I've seen someone has made a bundle to deal with it in some way. But I personally haven't used this extension and manually managed softdeletion.

**Comment by Glideh** [comment]
Don't hesitate to point me the bundle if you remember.
This seems to be linked to #1427
I'll also try to use EAGER fetch or exception when softdeleting parent objects

**Comment by l3pp4rd** [comment]
see #505

**Comment by Glideh** [comment]
Thank you, so a `SET NULL` with [SoftDeleteableListenerExtensionBundle](https://github.com/E-vence/SoftDeleteableListenerExtensionBundle) would be close to what I need.
I would have to define the inverse relations when needed though.
I'll try that.

**Comment by maxblache** [comment]
@Glideh Did that solve your problem ? I got same issue but can't get through. It seems that it works only if form is linked to the 'One' entity in the the ManytoOne relation. Which is not my case...

**Comment by Glideh** [comment]
I did finally not use this softdelete extension.
I managed it with a simple base repository with a filter (ex/in)cluding objects marked as deleted in the query builder.

**Comment by maxblache** [comment]
ok, thanks. I've finally chosen to use the 'fetch=eager' solution to bypass the filter
