### ISSUE TITLE
Tree listener was not found on your entity manager, it must be hooked into the event manager 

### ISSUE THREAD

**Issue by lt123456** [doctrine-extensions/DoctrineExtensions#1760]
first.   I   add bundle-》Entity-》role  use Gedmo;

second：
   if (!$back->getRoleId()) {
          $role = $em->getRepository('PowerBundle:Role')->all();
           $back->setRoleId();
        }

 I will  create backUser  then　
Tree listener was not found on your entity manager, it must be hooked into the event manager 

Stack Trace
in vendor\gedmo\doctrine-extensions\lib\Gedmo\Tree\Entity\Repository\AbstractTreeRepository.php at line 49   -
        }
        if (is_null($treeListener)) {
            throw new \Gedmo\Exception\InvalidMappingException('Tree listener was not found on your entity manager, it must be hooked into the event manager');
        }
        $this->listener = $treeListener;
  how solve ?   thank you ,

**Comment by Starojitski** [comment]
Got the same message trying to access repository for `Category` using `closure` strategy. How should i hook the listener into the entity manager? I saw some examples here and there but they look like standalone file examples and it is not clear how to do it the symfony way.

**Comment by AmProsius** [comment]
For everyone (like me) an updated answer:

In your `config/services.yaml` add

```php
# config/services.yaml

services:
    # ...
    Gedmo\Tree\TreeListener:
        tags:
            -
                name: doctrine.event_subscriber
                connection: default
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
```

**Comment by lt123456** [comment]
好的。谢谢

**Comment by RichardJong** [comment]
Updated config for Symfony 6,  you can remove the call to annotation reader:
https://github.com/doctrine-extensions/DoctrineExtensions/issues/2704#issuecomment-1850824493

**Comment by lt123456** [comment]
好的。谢谢
