### ISSUE TITLE
[Tree] Support for multiple closure tables related to one table

### ISSUE THREAD

**Issue by johnpancoast** [doctrine-extensions/DoctrineExtensions#1762]
It doesn't seem possible to have one owning side entity with more than one related closure table using this lib. I'm receiving FK errors about non-existent keys and I think it's due to how events are handled by the lib.

Biz case:
Imagine I have an `Item` that can have one parent for simple organization. This is a self-referencing many-to-one like you have in your `category.parent` [examples](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/tree.md#closure-table). But let's also say the same `Item` can have dependencies on many other items. One `Item` can have many `ItemDependency`ies. These are 2 different business cases and I'd like to setup both using a tree structure.

The library is erroring because it's attempting to insert closure table data before the related initial data has been inserted. My setup is fine if I use one or the other closure but not both. When the tree listener gets the `prePersist` event it will call on the [closure strategy](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Closure.php#L171) (for this case). This will be called for both closure tables and the pending child inserts for **both** closure tables will be saved before inserting anything. Doctrine then moves on to the [actual inserting](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L371). The problem is that doctrine will insert data related to the first closure table then fire a `postPersist` event. The closure strategy will then loop **both** closure tables [here](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Strategy/ORM/Closure.php#L242) and attempt to insert the related closure data **before** doctrine had a chance to insert the initial data for that closure.

I think a fix might be to instead use the passed `$entity` param to do a lookup in the pending child node inserts so that the only child data inserts that happen are for the entity that the event was fired for.

**Comment by l3pp4rd** [comment]
Hi, if there is a bug here, maybe you can contribute and submit a PR. extensions are now locked at current features and will remain as is, I'm personally stopped working with PHP few years ago.

**Comment by skianter** [comment]
I know this is very old question, but can I ask how did you resolve the situation where there are 2 object related like Item and ItemDependency using a nested-set Tree @johnpancoast 
Thanks

**Comment by johnpancoast** [comment]
Hi @skianter, unfrotunately don't know if we ever did from what I remember. and yeah, unfortunately it was so long ago I cann't remember, so sorry.
