### ISSUE TITLE
[Tree Closure Table] Ignores schema

### ISSUE THREAD

**Issue by darkphoenixff4** [doctrine-extensions/DoctrineExtensions#1769]
I'm using the Closure Tree extension on a PostgreSql Database under an alternate schema.  Everything else works fine, but trying to save the Closure Tree fails, because the Closure Table doesn't use schema at all.

    /**
     * Category
     *
     * @ORM\Entity(repositoryClass="Gedmo\Tree\Entity\Repository\ClosureTreeRepository")
     * @ORM\Table(name="categories", schema="ecommerce")
     * @Gedmo\Tree(type="closure")
     * @Gedmo\TreeClosure(class="ValorHealth\Models\CategoryTree")
     */
    class Category extends Object implements ExportableInterface
    {
        use Exportable;
        /**
         * @var int
         *
         * @ORM\Column(name="id", type="integer")
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="AUTO")
         */
        private $id;
    
        /**
         * @var string
         *
         * @ORM\Column(length=100, unique=true)
         */
        private $title;
    
        /**
         * @var int
         *
         * @ORM\Column(name="level", type="integer", nullable=true)
         * @Gedmo\TreeLevel
         */
        private $level;
    
        /**
         * @var Category|null
         *
         * @Gedmo\TreeParent
         * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
         * @ORM\ManyToOne(targetEntity="Category", inversedBy="children")
         */
        private $parent;
    
        /**
         * @var Collection
         *
         * @ORM\OneToMany(targetEntity="Category", mappedBy="parent")
         */
        private $children;
    ...
---
    /**
     * CategoryTree
     *
     * @ORM\Entity
     * @ORM\Table(name="category_tree", schema="ecommerce")
     */
    class CategoryTree extends AbstractClosure
    {
    }

Error message:

> [error]  An exception occurred while executing 'INSERT INTO category_tree (ancestor, descendant, 
> depth) VALUES (?, ?, ?)' with params [5, 5, 0]:
> SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "category_tree" does not exist
> LINE 1: INSERT INTO category_tree (ancestor, descendant, depth) VALU...

**Comment by l3pp4rd** [comment]
indeed, can you contribute a patch? guess that is very uncommon use case for different schema, since none issue requests were open regarding it before.

**Comment by darkphoenixff4** [comment]
Well, that's probably because (as I discovered after some research yesterday) that you can take care of it by running "SET search_path TO (schema);" on PostgreSQL to take care of it before you call any queries.  AFAICS, the schema table option is a new one, so I would imagine a lot of Doctrine code needs to be updated to take it into account.  I tried to patch it myself, but I don't know if I could find all the places where it would need to be adjusted, plus sadly I'm on a tight deadline at the moment (otherwise, I would give writing a patch a try).

**Comment by greabock** [comment]
up
