### ISSUE TITLE
[Tree] reorderAll doesnt work Error:

### ISSUE THREAD

**Issue by goelli** [doctrine-extensions/DoctrineExtensions#1786]
Hi,

i have a easy nested set tree. if i use the method reorderAll() (in NestedTreeRepository) then i get an exception:
Cannot get siblings from tree root node

The Problem is the moveDown() method.
`        $result = false;
        $meta = $this->getClassMetadata();
        if ($node instanceof $meta->name) {
            $nextSiblings = $this->getNextSiblings($node);
            if ($numSiblings = count($nextSiblings)) {`

Here use the getNextSiblings() method and this throw an exception:

the problem is, that the method use for a root entry use the getNextSiblingsQueryBuilder() method and thats doesnt work! 
here throw the exception in the getNextSiblingsQueryBuilder() method:
`$config = $this->listener->getConfiguration($this->_em, $meta->name);
        $parent = $wrapped->getPropertyValue($config['parent']);
        if (isset($config['root']) && !$parent) {
            throw new InvalidArgumentException("Cannot get siblings from tree root node");
        }`

**Comment by l3pp4rd** [comment]
Hi, maybe it was not tested with tree having root nodes. but I in general have no time to maintain this. unless someone contributes a fix here

**Comment by Padam87** [comment]
@goelli I'm not sure why, but one of my projects I have implemented a simple rebuild method myself, maybe it will help you.

```php
    public function rebuild()
    {
        $qb = $this->createQueryBuilder('u');

        $qb
            ->where($qb->expr()->isNull('u.parent'))
            ->orderBy('u.id', 'ASC')
        ;

        $this->rebuildRecursive($qb->getQuery()->getResult());
    }

    /**
     * @param User[] $users
     * @param int    $index
     * @param int    $lvl
     */
    protected function rebuildRecursive($users, &$index = 1, $lvl = 0)
    {
        foreach ($users as $user) {
            $user
                ->setLft($index++)
                ->setLvl($lvl)
            ;

            $this->rebuildRecursive($user->getChildren(), $index, $lvl + 1);

            $user->setRgt($index++);
        }
    }
```
