### ISSUE TITLE
[Tree][NestedTree] not updated when parent is set to null

### ISSUE THREAD

**Issue by yalg** [doctrine-extensions/DoctrineExtensions#1806]
Hi,

We've got some problem with nestedTree. One case that we reproduce systematicaly.
We have nullable parent, because we need multiple trees in the same entity.
- Create a new node with parent = null called id1
- Create a new node with parent = null called id2
- We create a new child into id1 called id3

id|parent|root        | lft | lvl | rgt
--|-------|----------|----|----|----
1 |null|1 |  1 |  0  |   4
2|null|2 |  1 |  0  |   2
3|1|1 |  2 |  1  |   3

- We decide to set parent null to id3 who became a new node

id|parent|root        | lft | lvl | rgt
--|-------|----------|----|----|----
1 |null|1 |  1 |  0  |   2 🆗 
2|null|2 |  1 |  0  |   2
3|null| 1⚠️ | 2⚠️ | 1⚠️ | 3 ⚠️

We can see that id1 is recalc, but id3 is not recalc anymore, and keep old root, lft, lvl and rgt

Here is what we expect :

id|parent|root        | lft | lvl | rgt
--|-------|----------|----|----|----
1 |null|1 |  1 |  0  |   2
2|null|2 |  1 |  0  |   2
3|null| 3 🆗   | 1 🆗  | 0  🆗  | 2 🆗 

- So, we can go ahead and set parent = 2 to id3. Logical behaviour because old root was kept.

id|parent|root        | lft | lvl | rgt
--|-------|----------|----|----|----
1 |null|1 |  1 |  0  |   0 ⚠️ 
2|null|2 |  1 |  0  |   4 🆗 
3|2  | 2 🆗  | 2 🆗  | 1 🆗   | 3 🆗 

I think there is a bug when parent is defined to null : root, lft, lvl, rgt are not recalc

**Comment by imsheng** [comment]
+1

**Comment by imsheng** [comment]
+1

**Comment by OndrejKubicek** [comment]
Any solution for this?

**Comment by imsheng** [comment]
if (null) {
                $em->getRepository('xxxxxxxx')->createQueryBuilder('xxxxxxx')->update()
                    ->set('xxxx.root', xxxxxx)
                    ->set('xxxx.lvl', 0)
                    ->set('xxxx.lft', 1)
                    ->set('xxxxx.rgt', 2)
                    ->where(xxxxxxx)
                    ->getQuery()
                    ->execute();
            }

This is my solution @OndrejKubicek @yalg

**Comment by Szyp** [comment]
Hi,
@imsheng your solution seem good but it only work if your node don't have child.

Personally I have wrote this doctrine listener on postUpdate : 

    public function postUpdate(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();
        $reflect = new \ReflectionClass($entity);

        $annotationReader = new AnnotationReader();
        $annotation = $annotationReader->getClassAnnotation($reflect, Tree::class);

        if ( $annotation === null) {
            return;
        }


        if ($entity->getParent() === null && $entity->getRoot() !== $entity) {

            $em = $args->getEntityManager();
            $expr = $em->getExpressionBuilder();

            $em->refresh($entity);
            $em
                ->getRepository($reflect->getName())
                ->createQueryBuilder('e')
                ->update($reflect->getName(), 'e')
                ->set('e.root', $entity->getId())
                ->set('e.lvl', 'e.lvl - ' . $entity->getLvl())
                ->set('e.lft', 'e.lft - ' . ($entity->getLft() - 1))
                ->set('e.rgt', 'e.rgt - ' . ($entity->getLft() - 1))
                ->where($expr->andX($expr->eq('e.root', $entity->getRoot()->getId()), $expr->gte('e.lft', $entity->getLft()), $expr->lte('e.rgt', $entity->getRgt())))
                ->getQuery()->execute();
            $em->refresh($entity);
        }

    }

**Comment by OndrejKubicek** [comment]
Hi,
@Szyp thanks for solution. Unfortunatelly it doesn't work in one case for me. When I have node with children and this node isn't the last child of parent, the nodes below new root node breaks (for example they have negative level).
But i managed to fix this by moving node down to the very end of its level before flush. This seems to work now.

`
if ($isNewRoot) {
            $this->treeRepo->moveDown($entity, true);
}
`

**Comment by Szyp** [comment]
Hi,
I failed to indicate that the listener is registered with a priority of -255

```
tags:
    - { name: doctrine.event_listener, event: postUpdate, method: postUpdate, priority: -255 }
```

**Comment by seed880505** [comment]
I have also the same problem. It seems that multiple root doesn't work as expects. I will have a try with unique root in database.
