### ISSUE TITLE
[Sluggable] Working on dev not working on production

### ISSUE THREAD

**Issue by pdziak** [doctrine-extensions/DoctrineExtensions#1808]
I have installed and configured Sluggable on my Symfony 3.2.11 project. 
Unfortunately when I try to insert new entity it revice null for slug. 

While debugging I stuck at \vendor\gedmo\doctrine-extensions\lib\Gedmo\Sluggable\Mapping\Driver\Annotation.php:66

`if ($slug = $this->reader->getPropertyAnnotation($property, self::SLUG)) {`

$slug variable is not readed.

Everything works fine on dev env so I think my configuration is just fine. 
app/config/services.yml

`    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: 1 }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]`

Entity:
```
use Gedmo\Mapping\Annotation as Gedmo;
    /**
     * @Gedmo\Slug(fields={"postTitle"})
     * @ORM\Column(type="string", length=255, nullable=false)
     */
```

**Comment by doctorx32** [comment]
same on symfony 2.8.26

**Comment by simongeekfamily** [comment]
Hello @pdziak, did you manage to get it working on your production environment ?
I'm facing the same issue at the moment.
Thanks !

**Comment by Nek-** [comment]
God, just ran into the same one @simongeekfamily , do you have somethin? x)
