### ISSUE TITLE
Translatable yml mapping

### ISSUE THREAD

**Issue by stoto34** [doctrine-extensions/DoctrineExtensions#1810]
Hi !

After a week wasted on internet to find a solution, I'm here to get an answer. Does Translatable work with yml mapping ? (Symfony 3.3.5)

Thank you very much !

**Comment by l3pp4rd** [comment]
Hi, well not sure, maybe something has changed in synfony yaml deendency. but in your situation I would [check and vardump $config here](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Translatable/Mapping/Driver/Yaml.php#L33) at the end of the function. If it hits this method with your metadata class name, then you can check there what happens exactly. If it never hits this method, may mean that metadata driver is not hooked properly

**Comment by stoto34** [comment]
Thank you for your answer @l3pp4rd. I've done what you suggested but I have not find any problem. it seems Yaml function works fine. My problem is not solved yet :(

When I use Yaml config with translatable, I have to create yml file for translation table and, more important, I have to set every field used by this table (locale, object_class, field, foreign_key) even my translation class extends AbstractTranslation. If I don't do that, doctrine migration command doesn't create any translation table (error : "locale field does not exist in CategoryTranslation class"). So I wrote this : 

`MyProject\MyBundle\Entity\Translation\CategoryTranslation:
  type: entity
  table: category_translation
  repositoryClass: Gedmo\Translatable\Entity\Repository\TranslationRepository
  indexes:
    category_translation_idx:
      columns: [ locale, object_class, field, foreign_key ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    locale:
      type: string
      length: 8
    objectClass:
      type: string
      length: 255
    field:
      type: string
      length: 32
    foreignKey:
      type: string
      length: 64
    content:
      type: text`


And then, category_translation table is created. BUT, when I try to add a new translation, "object_class" and "foreign_key" fields are "null" in my SQL query.

Any idea ? 
Thank you very much for your help :)
