### ISSUE TITLE
[Sluggable] Cannot update slug if it already null

### ISSUE THREAD

**Issue by doctorx32** [doctrine-extensions/DoctrineExtensions#1815]
It appears when database table already have data, and then will be inserted new slug field. After slug field inserting value of every record in slug column is null. When I'm trying to update this slug with $user->setSlug(NULL), it doesn't update depending on slug specified field. 

But if I before setting null persist to it random value, and then setting it to null, it updates normally.

In other words, the sequence:
1) field $slug added to table;
2) slug column value in every record is null;
3) I'm trying to $user->setSlug(NULL) and then persist($user) - nothing happens;
but
3) $user->setSlug("foo"); persist($user);
4) $user->setSlug(NULL); persist($user) - works ok

**Comment by grisha-chasovskih** [comment]
It happens because of doctrine doesn't see changes in property and as a result property just not updating. To fix this we have to manually create 'force' changing:
```
$uow = $em->getUnitOfWork();
$uow->propertyChanged($user, 'slug', $user->getSlug(), null);
$uow->scheduleForUpdate($user);
$em->flush();
```

**Comment by rileyrg** [comment]
His own way does it too. update with a random value then set it to null.

**Comment by rileyrg** [comment]
BTW it's incredibly slow on a reasonable size database.

**Comment by AliBenkahla** [comment]
hello,
thank you
where do you write the code?in your answers:

$uow = $em->getUnitOfWork();
$uow->propertyChanged($user, 'slug', $user->getSlug(), null);
$uow->scheduleForUpdate($user);
$em->flush();

and

I'm trying to $user->setSlug(NULL) and then persist($user) - nothing happens;
but
$user->setSlug("foo"); persist($user);
$user->setSlug(NULL); persist($user) - works ok

please?

**Comment by ylcdx** [comment]
Something is planned for it to work? because I have the same problem.
