### ISSUE TITLE
Translation Document example

### ISSUE THREAD

**Issue by redayoub** [doctrine-extensions/DoctrineExtensions#1840]
Could you please add a Translation Document in the doc like the example of the Translation Entity? I tried to follow the same steps by it's not working well.

**Comment by redayoub** [comment]
up

**Comment by l3pp4rd** [comment]
Hi, please open a PR if it is missing in the documentation, on branch 2.4.x.

**Comment by redayoub** [comment]
Should I open a PR even if I don't have a working example?

**Comment by l3pp4rd** [comment]
sure, if valid documentation
