### ISSUE TITLE
[Sluggable] Reserved words

### ISSUE THREAD

**Issue by samhastings** [doctrine-extensions/DoctrineExtensions#1841]
Is it possible to define reserved words that will always be suffixed if they end up being generated as a slug?

For example, if I have the following URL structure:

/projects/{project-slug}
/projects/create

I want to make sure that if somebody adds a project with the title "Create", the slug "create" will be automatically suffixed to avoid a URL conflict.

**Comment by l3pp4rd** [comment]
Hi, currently I maintain only current set of features. You will have to work around it, or fork it. this branch will not change much in the future. regarding a workaround, you may either extend the listener class or have another listener followed after sluggable to check and prefix slugs additionally.
