### ISSUE TITLE
Loading annotation metadata is really slow

### ISSUE THREAD

**Issue by OJezu** [doctrine-extensions/DoctrineExtensions#1842]
We are making quite an extensive use of Extensions. Few days ago I found out, that loading class metadata for them is taking 60% of our request processing time (it takes over 200 ms). I've been working on a solution for a few hours, and I'm planning to add methods allowing to add and dump from `Gedmo/Mapping/MappedEventSubscriber::$configurations` static property.

Intended use for that methods is to dump configurations to cache after they are generated once (e.g. during cache warm-up) and then add them from cache, saving in our case some 10,000 calls to `CachedReader->getPropertyAnnotations`.

The cache currently used in `MappedEventSubscriber` loaded from MetadataFactory seems to be doing nothing, at least when using PHP >=7.0, as it is discarded at end of each request. Moreover it is used in `getConfiguration()` while the listeners are calling `loadMetadataForObjectClass()` which loads metadata without even checking cache for complete configuration. Doctrine with Symfony meanwhile is using completely different cache, new `ArrayCacheAdapter` reading cache from generated PHP file.

Is there a better way then loading the whole `$configurations` from cache with a static method? I will also probably have some problems with the property being static, when trying to integrate that feature with a Symfony Bundle.

**Comment by l3pp4rd** [comment]
yes, extenstions and orm are not tools for best performance. these are more for rapid development, to have a quick implementation. If performance is the key bottleneck, probably first of all, php is not the right tool to have and extensions could be just a custom implementation.

Regarding caching, yes it should be implemented in the bundle and PR could be submitted to DoctrineExtensionsBundle. unless it turns out to be very simple extension, then it would be nice to have it in documentation.

**Comment by OJezu** [comment]
It just popped up as most time-intensive part of request processing, taking 60% of time in our case. From my preliminary testing, I can cut down metadata loading time by almost 100%, which is significant gain, no matter innate slowness of PHP and ORMs.

I'm looking for feedback before doing something PR-grade. I'm concerned with not breaking BC - not changing `$configurations` static protected property and what are effects of methods. Other concern is support for cache generation during Symfony warm-up.

I see two approaches. Allowing reading from and adding to aforementioned `$configurations`, or adding explicit cache support with `setCacheAdapter` method or similar. Only problem with latter is adding warm-up cache generation in Symfony bundle.

**Comment by l3pp4rd** [comment]
well I always thought the caching driver of doctrine orm was properly working, see https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Mapping/MappedEventSubscriber.php#L126 or is it something different that you try to cache?

**Comment by OJezu** [comment]
1. Listeners are calling `LoadMetadataForObjectClass` on metadata load directly, skipping cache in getConfiguration, as can be seen here: https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/SoftDeleteable/SoftDeleteableListener.php#L108
2. Cache loaded in line https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Mapping/MappedEventSubscriber.php#L126 is different from actual cache used by doctrine for annotations, at least when testing with Symfony 3.4 and PHP 7.1. Doctrine is using non-writable `\Symfony\Component\Cache\Adapter\PhpArrayAdapter` loading annotations from `%kernel.cache_dir%/annotations.yml`, while `$factory->getCacheDriver` returns an instance of `Doctrine\Common\CacheArrayCache` that is created empty at start of request, discarded at end of request, and never persisted.
3. That code has another bug, if configuration is not already loaded into `self::$configurations` and no cache driver is available, extensions will make no attempt to load metadata at all, but I guess there is always a cache driver, even though call at https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Mapping/MappedEventSubscriber.php#L123 is not backed up by `ClassMetadataFactory` Interface.

**Comment by OJezu** [comment]
I propose setting cache with explicit `setCache` method, refactoring to make sure it is used in `LoadMetadataForObjectClass`, and fixing `getConfiguration`. That will be most elegant change to API, but it may require a helper method or some extend hacks to allow warm-up cache generation and persistence.
