### ISSUE TITLE
Reading of Mapping-Configurations depends of State in MetadataFactory

### ISSUE THREAD

**Issue by addiks** [doctrine-extensions/DoctrineExtensions#1852]
The extension-metadata-factory (Gedmo\Mapping\ExtensionMetadataFactory) currently ask's the doctrine-metadata-factory whether it knows of the metadata of a parent class: ([link to the code](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Mapping/ExtensionMetadataFactory.php#L83))
```php
    ...
    public function getExtensionMetadata($meta)
    {
        ...
        $config = array();
        ...
        if (null !== $meta->reflClass) {
            foreach (array_reverse(class_parents($meta->name)) as $parentClass) {
                // read only inherited mapped classes
                if ($cmf->hasMetadataFor($parentClass)) {
                    $class = $this->objectManager->getClassMetadata($parentClass);
                    $this->driver->readExtendedMetadata($class, $config);
                    ...
                }
            }
            $this->driver->readExtendedMetadata($meta, $config);
        }
        ...
        return $config;
    }
    ...
```
The problem here is the call to **hasMetadataFor**. Because this method does _not_ check whether the metadata of that class exists at all, it just checks if the metadata was _already loaded into memory_.
See the definition of the method:
```php
    /**
     * Checks whether the factory has the metadata for a class loaded already.
     *
     * @param string $className
     *
     * @return boolean TRUE if the metadata of the class in question is already loaded, FALSE otherwise.
     */
    public function hasMetadataFor($className)
    {
        return isset($this->loadedMetadata[$className]);
    }
```
This means that loading of a parent-classes gedmo-configuration will not work if the metadata of that class has not been loaded before this by some other component.

I would suggest removing the condition "if ($cmf->hasMetadataFor($parentClass))" altogether. 

In my case the blamable feature did not work on a createdBy field of a parent class when creating a new object because the metadata of that parent class was not loaded at persist time. Commenting out lines 83 and 92 (the if statement and the closing curly bracket) solved this issue completely.

**Comment by ahilles107** [comment]
@addiks how it ended in Your case? I hitted into this same issue and created PR here: https://github.com/Atlantic18/DoctrineExtensions/pull/2076

**Comment by addiks** [comment]
Well, it did not end yet. The issue is still open. ;-)

We have "fixed" this using a workaround. Before the code above is called, we load the mapping for the base-class. In the bootstrap-file for the project (For symfony: `web/app.php`, like the `index.php` for other projects) we call this:

```php
# This is a workaround for https://github.com/Atlantic18/DoctrineExtensions/issues/1852
$container->get('gedmo.listener.blameable')->getConfiguration(
    $container->get('doctrine.orm.entity_manager'),
    BaseEntity::class
);
```
