### ISSUE TITLE
[Translatable] Personal Translations 

### ISSUE THREAD

**Issue by ceesvanegmond** [doctrine-extensions/DoctrineExtensions#1857]
This package is awesome, and I use it all the time. I have a question though when talking about personal translations. Especially the custom translation walker.             ```(->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, TranslationWalker::class))```

When an entity is retrieved with an query using the above method, how to get the translations from it? Say my default language is 'nl' and these info is stored in an pages table. I have translations in en en these are stored in the page_translations using the personal translations. 

When querying an object as en, how to get the translations from there? An left join to translations wouldn't work obviously.

**Comment by l3pp4rd** [comment]
Hi, thanks. if you need to have all translations for an entity in all languages, then select them from translation table directly. that will be easier to modify them and work with them. If you need to identify which are translated fields and which are not. then make a hint to disable translation fallback to default language, it should make those fields as nulls or empty.

**Comment by ceesvanegmond** [comment]
What i really want to build is an locale switch. So translate the current page into other languages and link to them. When having the base translation (pages table) this is fairly easy, but when having an translation for it and determine the other translations. That's difficult right?

**Comment by l3pp4rd** [comment]
well, with personal translations, you can have a collection of translations mapped to a translated entity. I do not think that this is tricky or hard to switch locale or find other translations

**Comment by ceesvanegmond** [comment]
@l3pp4rd Could you give an code example?

**Comment by l3pp4rd** [comment]
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/tests/Gedmo/Translatable/Fixture/Personal/Article.php#L28
