### ISSUE TITLE
Question : Unique_base on two columns?

### ISSUE THREAD

**Issue by DPerkunas** [doctrine-extensions/DoctrineExtensions#1873]
Is it possible to use unique_base with two columns specified?

I tried unique_base={'parent_id','section_id'}.

When doing it with one column, works fine. I need section_id and parent_id to be unique, so slug doesn't have to be unique for those sections.

Is there a fix or must do it manually? Thank you.

**Comment by delboy1978uk** [comment]
I think we have the same problem. We have a menu table, and a menu_item table. 

Gedmo does it's thing on the menu_item table, which works, but as well as the self referencing parent_id, I'd like to restrict by the menu_id which is a foreign key to the menu table, because right now it is calculating for every menu.

**Comment by delboy1978uk** [comment]
Thanks for the quick response! 
Could you explain the TreeRoot annotation? I looked in your examples and see that as well. We are only using `lft`, `rgt`, `lvl`, and `parent_id`. Is this maybe what I'm looking for? I just need the `lft` and `rgt` to be calculated for rows with menu_id x, not every row.

**Comment by l3pp4rd** [comment]
yes @delboy1978uk most likely. the TreeRoot is used mainly on relations, for example if you need differen trees for every menu item. then TreeRoot would be something to separate trees per menu item, try it in order to understand properly.

**Comment by delboy1978uk** [comment]
Hi again, and thanks once more for your assistance!

Using `TreeRoot` on our `menu` property does indeed number the `lft` and `rgt` columns independently from the other! 😃

This is a good step forward! The only problem I am left with is when we try to change the order of a `menu_item` that has a root but no parent. In that instance, we get the `InvalidArgumentException`.

So to try and fix that, I tried copying the methods `getNextSiblingsQueryBuilder` and `getPrevSiblingsQueryBuilder` into our repository extending yours, took out the exception, and I made the following change:

```php
// unchanged code here, then
if ($parent) {
            $wrappedParent = new EntityWrapper($parent, $this->_em);
            $qb->andWhere($qb->expr()->eq('node.'.$config['parent'], ':pid'));
            $qb->setParameter('pid', $wrappedParent->getIdentifier());
        } **else if (isset($config['root']) && !$parent) {
            $qb->andWhere($qb->expr()->eq('node.'.$config['root'], ':menu'));
            $qb->setParameter('menu', $node->getMenu());
        }** else {
            $qb->andWhere($qb->expr()->isNull('node.'.$config['parent']));
        }

        return $qb;
```
This kind of works until it hits `Strategy\ORM\Nested` line 331:
```php
    if (!$isNewNode && $root === $parentRoot && $parentLeft >= $left && $parentRight <= $right) {
        throw new UnexpectedValueException("Cannot set child as parent to node: {$nodeId}");
    }
```
Still debugging to see if it is possible, but if you know what I might need to do then please let me know!
If I get it working I'll show you what I did!

**Comment by delboy1978uk** [comment]
I think I just need to either extend or copy the Strategy, and get the Repository to use ours instead. Is this possible?

**Comment by l3pp4rd** [comment]
well I do not remember now what was it about, but seems like you cannot exchange parent with child, same as in filesystem, you cannot move Directory inside its child directory right? you need to perform this operation in different ways, not sure whether that is possible in this extension though, now the Root node without parent is not movable at all. guess you would need to first delete whole tree, then rearrange it. There is no quick method in repository as far as I know for that operation.

**Comment by delboy1978uk** [comment]
I just did it! Testing now, I will show you what I changed if it works, maybe we can figure out how to incorporate it in, and I can send a pull request! 😃

**Comment by delboy1978uk** [comment]
Here's a Gist of what I did: https://gist.github.com/delboy1978uk/7457dbcf5befff62668cba1f189d70ab#file-nested-php-L87

Next and previous sibling query builder was updated. As my TreeRoot is on a different column from the parent (in our case its the `menu_id` column), so I do the following:

```php
            $qb->andWhere($qb->expr()->eq('node.'.$config['root'], ':menu'));    
            $qb->andWhere($qb->expr()->isNull('node.parent'));                   
            $qb->setParameter('menu', $node->getMenu()); 
```
Obviously we would need a way to check this without being so specific, not everyone has a `getMenu()` method!

In the nested strategy's `updateNode()` method, where it switches position, I only throw the exception now if the config parent is the same as the config root. If they are different, we do nothing, and otherwise set the parent in an else block.

```php
                        if ( (is_null($newParent) && (isset($config['root']) && $config['root'] == $config['parent']) || $isNewNode)) {     // Check root is the same column from parent
                            throw new UnexpectedValueException("Cannot persist sibling for a root node, tree operation is not possible");   // Then throw Exception
                        } else if (is_null($newParent) && (isset($config['root']) || $isNewNode)) {                                         // if root column is different from parent column
                            // root is a different column from parent (pointing to another table?), do nothing                              // don't set the parent!
                        } else {                                                                                                            // else proceed as normal
                            $wrapped->setPropertyValue($config['parent'], $newParent);                                                      // set the parent
                        }
```

It seems to work great, like I say, the only issue now is the query builder part, we would need to be able to set the value generically.

Your thoughts? 😃

**Comment by l3pp4rd** [comment]
sure, probably many people would want that, I think I remember few issues before regarding it ;)

**Comment by delboy1978uk** [comment]
Any ideas how we could configure the root node identifier? 
As I mentioned previously, we have a `MenuItem` class, but as well as the `parent_id` column, we also have `menu_id`. In the code above I tweaked the query builder to fetch and restrict by menu id:
```php
$qb->andWhere($qb->expr()->eq('node.'.$config['root'], ':menu'));    
$qb->andWhere($qb->expr()->isNull('node.parent'));                   
$qb->setParameter('menu', $node->getMenu()); 
```
We would need to somehow tell `@TreeRoot ` annotation that my `getMenu()` method will return the root node ID.

**Comment by l3pp4rd** [comment]
is `$node->getMenu());` not the root of tree? if so it could be taken based on config[root] field name.

**Comment by delboy1978uk** [comment]
I now have the identifier from an annotation, here's the PR https://github.com/Atlantic18/DoctrineExtensions/pull/1877
