### ISSUE TITLE
relation of soft deleted entities

### ISSUE THREAD

**Issue by emr** [doctrine-extensions/DoctrineExtensions#1884]
can I get soft deleted entity from another entity?

MyEntity
```php
/**
 * @ORM\Entity
 */
class MyEntity
{
    /**
     * @ORM\OneToOne(targetEntity="MySoftEntity")
     */
    public $mySoftEntity;
}
```

MySoftEntity
```php
/**
 * @ORM\Entity
 * @Gedmo\SoftDeleteable
 */
class MySoftEntity
{
    /**
     * @ORM\OneToOne(targetEntity="MyEntity")
     */
    public $myEntity;
}
```

I want to get deleted `MySoftEntity` record  entity `MyEntity`

**Comment by l3pp4rd** [comment]
Hi if you cascade remove at ORM level (do not remember, but configurable in annotations). then it will cascade softdeletion, but both of entities should be soft deletable, otherwise you will end up with null relations
