### ISSUE TITLE
Use trait repositories instead of repository

### ISSUE THREAD

**Issue by Taluu** [doctrine-extensions/DoctrineExtensions#1908]
Some repositories are traits (e.g the Tree one), and some are not (e.g Sortable). Wouldn't be better, instead of having multiple repositories, having traits instead ?

With the current state to things, it seems impossible to combine 2 behaviors that are relying on repositories for listeners, which don't have traits. Using traits would allows us to solve that (so we could have our own repository, tagged with the according traits).

**Comment by l3pp4rd** [comment]
Hi, pull request can be accepted if made backward compatible with the current repository.
