### ISSUE TITLE
Translatable and join

### ISSUE THREAD

**Issue by zim32** [doctrine-extensions/DoctrineExtensions#1935]
It seems line TranslatableWalker does't honor joined entities. Am I right?

**Comment by andrewtch** [comment]
@zim32 , can you provide use-case / some code?

**Comment by zim32** [comment]
I have parent child relation on translatable entity and want to join and select all child nodes using DQL. But they are not translated.

**Comment by Brewal** [comment]
I think I have the same problem. I can't manage to filter results on a translated child entity field
