### ISSUE TITLE
[RFC] Branching

### ISSUE THREAD

**Issue by AkenRoberts** [doctrine-extensions/DoctrineExtensions#1940]
I'd like to thank @l3pp4rd for bringing myself and others in as collaborators. I'm excited to work with everyone to bring Doctrine Extensions to the next level.

I've taken a few preliminary actions, with an emphasis on language/documentation and standardization: #1937, #1938, #1939. I also created two initial [Projects](https://github.com/Atlantic18/DoctrineExtensions/projects) for organizing issues and tasks for our assumed next major and minor releases. My hope is that, as existing issues are triaged and collaborators begin recommending their courses of action, they can be added to these projects and acted upon.

Along with these projects, we should determine our branching model. Here's my recommendation:

[Current Branches](https://github.com/Atlantic18/DoctrineExtensions/branches)

- `v2.4.x` - Active and up-to-date. Keep and continue to use for 2.4 patch releases. I would personally rename to `2.4` for brevity.
- `master` - Initially a next major release (3.0) branch. With new people coming in whom are unfamiliar with its history (like me), I would scrap it and recreate `master` as a branch from the current `v2.4.x` branch. This would correspond with the 3.0 Project.
- `2.2.x` - Old version history. Unsure where 2.3.x went. Because of age and refreshing nature of new collaborators, I would delete this. Leaving it archived would not hurt anything, though.
- `wip-2.4.x` An old unreleased attempt at 2.4. Delete.
- `clean/*` - Temporary feature branches I created; deleted upon PR closure.
- `gh-pages` current out of date documentation. Can re-use if needed (I have another proposal for docs I'll post tomorrow).

A new branch `2.5` would be created for the next minor version, and correspond to the 2.5 Project. Each minor release branch would be kept and maintained for as long as our defined life cycle.

Existing quality pull requests can be updated to reflect any phased-out branches.

Any other advice?

**Comment by andrewtch** [comment]
Not sure about the master - Gedeminas merged something in June to the master branch. Are we using git flow when master = bleeding edge and others are release versions?

**Comment by AkenRoberts** [comment]
Not exactly a Git Flow model, which uses a permanent `develop` and temporary release branches. `master` would indeed be bleeding edge, meant-for-next-major-release features/changes. Then, minor release branches like `2.4` and `2.5` for maintaining those releases (2.5 would be considered an upcoming release right now). `3.0` would be created from master whenever it is released. And of course, temporary feature branches can be created by collaborators as needed.
