### ISSUE TITLE
[Timestampable] Implement "Clock" provider layer

### ISSUE THREAD

**Issue by AkenRoberts** [doctrine-extensions/DoctrineExtensions#1946]
The Timestampable extension should have a specific layer for providing the current date/time object. Commonly referred to as a Clock. This will help with testing primarily, along with adding another abstraction for customization.

A more detailed explanation: https://blog.frankdejonge.nl/being-in-control-of-time-in-php/

Example of a failing test due to passage of time: https://travis-ci.org/Atlantic18/DoctrineExtensions/jobs/422502612

Targeting the 3.0 refresh release.

**Comment by AkenRoberts** [comment]
This is actually part of a broader issue/feature, where the "value provider" layer needs to be interfaced and customizable. For example, allowing users to specify a custom DateTime object for Timestampable (e.g. Chronos or Carbon).

**Comment by juherr** [comment]
Any update about this issue?

I'm using php 7.4 and I had the following issue:
> PHP Fatal error:  Uncaught TypeError: Typed property Chargemap\Recurly\Domain\Subscription::$dateCreated must be an instance of Carbon\Carbon, DateTime used in /app/vendor/gedmo/doctrine-extensions/lib/Gedmo/AbstractTrackingListener.php:220

But `datetime` is overriden by my own CarbonType

```php
class CarbonType extends DateTimeType
{
    /**
     * @inheritdoc
     */
    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        if ($value === null) {
            return null;
        }
        return Carbon::instance(parent::convertToPHPValue($value, $platform));
    }

    /**
     * @inheritDoc
     */
    public static function override(): void
    {
        static::overrideType(Types::DATETIME_MUTABLE, get_called_class());
    }
}
```

Moving from 

```php
    /**
     * @Timestampable(on="create")
     * @Column(type="datetime",name="date_created")
     */
    private Carbon $dateCreated;
```
to

```php
    /**
     * @Timestampable(on="create")
     * @Column(type="datetime",name="date_created")
     */
    private \DateTime $dateCreated;
```

is resolving the issue.

**Comment by AkenRoberts** [comment]
@juherr No updates on this unfortunately. I'm not sure when this will be dealt with. Grateful for any ideas or pull request contributions you may have to help.

FYI, extensions doesn't use DBAL's type system to generate the values, which is why your override didn't work. That's the goal for whenever this is updated, so we can relegate value generation to DBAL and not reinvent that wheel.

**Comment by nesl247** [comment]
Bumping to remove staleness.
