### ISSUE TITLE
[SoftDeleteable] deletedAt field using immutable types will fail to persist on soft deletion

### ISSUE THREAD

**Issue by clement-michelet** [doctrine-extensions/DoctrineExtensions#1957]
If the field is configured to use immutable datatype it will fails when persisted.
The listener create a `DateTime` instance and set the value using reflection.

https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/SoftDeleteable/SoftDeleteableListener.php#L66

When the entity is persisted, it fails because doctrine will not try to convert from DateTime as it expects DateTimeImmutable or null for the given field.

* doctrine/orm: 2.6.2
* gedmo/doctrine-extensions: 2.4.36

**Expected:**
The entity is properly soft deleted on database

**Actual:**
Doctrine\DBAL\Types\ConversionException : Could not convert PHP value of type 'DateTime' to type 'datetime_immutable'. Expected one of the following types: null, DateTimeImmutable

**Comment by fabianerni** [comment]
Field type would be available one Line 66 via

$meta->getFieldMapping($config['fieldName'])['type']

maybe port this helper from timestampable

https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Timestampable/Mapping/Event/Adapter/ORM.php

**Comment by AntoniusGolly** [comment]
any news on this?

**Comment by AkenRoberts** [comment]
I'd be happy to merge a pull request to add this feature. As @fabianerni said, borrowing the helper from Timestampable would be a good start. Make sure to test as well!

**Comment by AntoniusGolly** [comment]
As long as this is not part of the package I helped myself by not using `remove()` of the Repository but write a simple custom `softDelete()` method.
```
/**
     * @throws \Exception
     */
    public function softDelete(): void
    {
        $localDate = new \DateTimeImmutable();
        $utcDate = $localDate->setTimezone(new \DateTimeZone('UTC'));
        $this->setDeletedAt($utcDate);
    }
```
As I have a put this in a SoftDeleteableTrait I can reuse it in all Entities.

**Comment by oojacoboo** [comment]
@AntoniusGolly I guess you're still using the extension to handle your queries?  You could always custom roll that as well I guess, but having a `softDelete` method is only part of the solution for a real soft delete implementation.

**Comment by oojacoboo** [comment]
Submitted pull request #2067

**Comment by AntoniusGolly** [comment]
@oojacoboo please specify `using the extension to handle your queries` and what you mean with `part of the solution`. Thanks.

**Comment by oojacoboo** [comment]
@AntoniusGolly When you query the database for a soft-deleted entity, you have to add the `WHERE deleted_at IS NULL [OR deleted_at > NOW()]`.

**Comment by AntoniusGolly** [comment]
Ah, right. 
So, here is how I do it.
Regular querybuilder -> ignores soft-deleted entities (i.e. does *not* return them)
Query builder with temporarily disabled filter -> does return soft-deleted entities

```<?php

public function findByMember(
	ProjectMember $projectMember
	bool $findDeleted = false
): ?DataRevisionAccess {

	/** @var SoftDeleteableFilter $filter */
	$filter = $this->getEntityManager()->getFilters()->enable('softdeleteable');

	if ($findDeleted) {
		$filter->disableForEntity(DataRevisionAccess::class);
	}

	$dataRevisionAccess = $this->createQueryBuilder('dra')
		->andWhere('dra.projectMember = :projectMember')
		->setParameter('projectMember', $projectMember)
		->getQuery()
		->getOneOrNullResult()
	;

	$filter->enableForEntity(DataRevisionAccess::class);

	return $dataRevisionAccess;
}```

Happy for comments.

**Comment by phansys** [comment]
I'm closing this issue as this issue is currently resolved.
https://github.com/doctrine-extensions/DoctrineExtensions/blob/7744700f90fa8836cc71d52271d3b4bfae83faa2/src/SoftDeleteable/SoftDeleteableListener.php#L64
Thank you.
