### ISSUE TITLE
Using UUID as ID type and using tree hydrator does not work because of illegal type

### ISSUE THREAD

**Issue by lsv** [doctrine-extensions/DoctrineExtensions#1992]
As the `$this->getPropertyValue($parentProxy, $this->idField);` is expected not be a object due to it is parsed into as a array key, you can not use `ramsey\uuid` as a id type.

I have already fixed it by adding a `getIdPropertyValue($node)` and then using `__toString` if the id value is a object.

Used in repository

```
$tree = $this
            ->createQueryBuilder('node')
            ->getQuery()
            ->getResult('tree');
```

It seems that `$data = parent::hydrateAllData();` does not fetch the parent, and therefor can not build `$this->buildChildrenHashmap($data)`

But if I remove `'tree'` and use doctrine object hydrator, the parent is the correct object

**Comment by koioannis** [comment]
Hi! I know that this is a bit old, but I'm facing the same issue. As far as I can tell this has not been merged. Is there any other way to fix this issue?

**Comment by karl-foerster** [comment]
I'm facing the same issue trying to implement the tree with symfony/uuid as id. Applying all changes of that linked pull request everything works fine. I have no issues with parent.
