### ISSUE TITLE
SoftDeleteable Annotation not read in trait

### ISSUE THREAD

**Issue by D4rkMindz** [doctrine-extensions/DoctrineExtensions#1994]
I was trying to create a MetaField trait for my entities. 
The trait should be used in every entity, that needs some fields like created_at, modified_at, deleted_at, etc. 
My intention was to use the SoftDeleteable annotation within this trait (or configure it there). E.g. Like this:
```php
namespace App\Entity\Traits;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * Trait MetaFieldTrait
 *
 * @Gedmo\SoftDeleteable(fieldName="deletedAt") // this here
 */
trait MetaFieldTrait
{
   // created and modified fields here ...
    /**
     * @var DateTime|null
     * @ORM\Column(name="deleted_at", type="datetime", nullable=true)
     * @Groups({"readable"})
     */
    protected $deletedAt;

   // created and modified field getter and setters here here ...

    public function getDeletedAt(): ?\DateTime
    {
        return $this->deletedAt;
    }

    public function isDeleted(): bool
    {
        return $this->deletedAt instanceof \DateTimeInterface;
    }

    public function recover()
    {
        $this->deletedAt = null;
    }
}

```

The problem is, that the annotation of the trait is not used in the configuration of the [`Gedmo\Mapping\MappedEventSubscriber`](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Mapping/MappedEventSubscriber.php#L119)

I think, it really should possible to either:

- Use the annotation in a trait (but i'm not sure if thats possible with the annotation loader), or
- Configure the SoftDeletable in the trait itself with either a static method (e.g. `SoftDeletable::setFieldName($name)`, etc) or with an annotation on the field
```php
    /**
     * @Gedmo\SoftDeletable()
     */
    protected $deletedAt;
``` 

Otherwise, this might be a violation of the [DRY Principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) (to use the annotation on every entity that uses the described MetaFieldTrait)

**Comment by oojacoboo** [comment]
I agree, it'd be really great if this annotation didn't have to be included on the main class, and instead could be included in the trait somewhere.  It's much easier to manage this by simply adding a trait to an entity and knowing it handles everything itself.  As it is now, logic is spread.

**Comment by oojacoboo** [comment]
Still important

**Comment by borodean** [comment]
Still important :)

**Comment by franmomu** [comment]
Annotations/Attributes cannot be used at the top of a trait.

An solution here I think it would be to allow to use [SoftDeleteable attribute/annotation](https://github.com/doctrine-extensions/DoctrineExtensions/blob/f3a912950c3eaadbe0b4eac69c9424e62176f902/src/Mapping/Annotation/SoftDeleteable.php#L25) also for class properties, similar to `Timestampable`.
