### ISSUE TITLE
[Timestampable] Please add a trait with DateTimeImmutables

### ISSUE THREAD

**Issue by mordilion** [doctrine-extensions/DoctrineExtensions#1997]
It would be great if there will be a `TimestampImmutableEntity` trait with DateTimeImmutable types.

**Comment by bixelsnl** [comment]
Or typehint against `DateTimeInterface`

**Comment by endelwar** [comment]
Given that minimum supported PHP version in 7.2, I think that it's time to type-hint against `DateTimeInterface` in timestampable traits

**Comment by franmomu** [comment]
We need minimum of PHP 7.4 to be able to do that, someone might have created an interface like https://3v4l.org/U4c75

In any case, these traits are quite simple, if you need any change you can create your own traits.

**Comment by bt-nn** [comment]
Minimum PHP version is now 7.4 so we could use `DateTimeInterface` now
