### ISSUE TITLE
Record still exist one second after softdelete 

### ISSUE THREAD

**Issue by ls-amir-beygi** [doctrine-extensions/DoctrineExtensions#2010]
If you delete a record using softDelete and search for the record immediately after deletion, the deleted record will be returned (with deleted_at filed already populated).

It is happening because on softDelete we will set deleted_at value to current timestamp with milliseconds (`2019-04-30 16:57:19.572480`)

When we are checking for the deleted record the condition will be something like :
`... AND ((l0_.deleted_at IS NULL OR l0_.deleted_at > CURRENT_TIMESTAMP)`
In mysql the `CURRENT_TIMESTAMP` will return the timestamp without milliseconds (`2019-04-30 16:57:19`), so the query will look like this:
`... AND ((l0_.deleted_at IS NULL OR 2019-04-30 16:57:19.572480 > 2019-04-30 16:57:19)`

This is causing the deleted record to be returned as not deleted until `2019-04-30 16:57:20`

**Comment by ngrevet-lightspeed** [comment]
I think this has been happening since this change: https://github.com/Atlantic18/DoctrineExtensions/commit/51e9ac2326d83d9c6f1a3f27a12596db1283fbfc
If the field used to detect soft-deletion is a `DATETIME` with fractional seconds like in our case, it won't work.

**Comment by oojacoboo** [comment]
@ls-amir-beygi have you tried setting the `timeAware` property to `false`?

`@Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, hardDelete=false)`
