### ISSUE TITLE
[Question] Using materialized path and nested together

### ISSUE THREAD

**Issue by taita-wizard** [doctrine-extensions/DoctrineExtensions#2017]
Hello!
Is there any opportunity to using at the same time materialized path and nested?
Are there plans to implement this feature?

**Comment by cybernet** [comment]
they don't even answer to security issues, don't bother with features 😄

**Comment by AkenRoberts** [comment]
Hi @taita-wizard, sorry for the lack of attention.

I don't believe it's currently possible to combine tree strategies on a single entity, nor are there any plans to add it. Can I ask why you want to use both at the same time?
