### ISSUE TITLE
[Tree][Closure] Using ValueObject as identity within tree

### ISSUE THREAD

**Issue by agluh** [doctrine-extensions/DoctrineExtensions#2042]
Hi!

I'm trying to use closure table for comments tree in my project. The code of the comment entity is exactly the same as in example from docs. But i'm using DDD's ValueObject as id for entities.

Identity looks like this

```php
final class Identity
{
    protected $id;

    protected function __construct(string $id)
    {
        $this->id = $id;
    }

    public static function fromString(string $id): self
    {
        return new static($id);
    }

    public function equals($other): bool
    {
        if($other instanceof $this) {
            return $this->toString() === $other->toString();
        }
        return false;
    }

    public function toString(): string
    {
        return $this->id;
    }

    public function __toString()
    {
        return $this->toString();
    }
}
```

Following custom field type is used for it (based on Ramsey\Uuid lib):
```php
final class IdentityType extends UuidBinaryType
{
    const NAME = 'identity';

    /**
     * @inheritDoc
     * @throws ConversionException
     */
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return (null === $value) ? null : parent::convertToDatabaseValue($value->toString(), $platform);
    }

    /**
     * @inheritDoc
     * @throws ConversionException
     */
    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        $uuid = parent::convertToPHPValue($value, $platform);
        return (null === $uuid) ? null : Identity::fromString($uuid->toString());
    }
}
```

An error occurs when I persist a new comment object
```
An exception occurred while executing 'INSERT INTO comment_closure (ancestor, descendant, depth) VALUES (?, ?, ?)' with params [{}, {}, 0]:

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ancestor' at row 1
```

In Symfony's profiler I can see the INSERT query and it looks strange:

![insert](https://user-images.githubusercontent.com/25745005/63963691-3be4ba80-ca9e-11e9-963f-80edb03dad72.jpg)

It looks like Doctrine try to store the whole Identity object. I've used those Identities before with other entities and all worked just fine. I figured out that at this line i've got an object instead of some integer(or mayby string):

https://github.com/Atlantic18/DoctrineExtensions/blob/92ab6b0d38eec38858476103df5410d2eb974a25/lib/Gedmo/Tree/Strategy/ORM/Closure.php#L247

![dd](https://user-images.githubusercontent.com/25745005/63964157-2e7c0000-ca9f-11e9-9081-790a8ad2d055.jpg)

Could anyone please help me to solve this problem?

**Comment by alexg-nn** [comment]
If I pass types as third argument to insert() function at

https://github.com/Atlantic18/DoctrineExtensions/blob/92ab6b0d38eec38858476103df5410d2eb974a25/lib/Gedmo/Tree/Strategy/ORM/Closure.php#L293

like

```php
                if (!$em->getConnection()->insert($closureTable, $closure, ['identity', 'identity', 'integer'])) {
```

then it works as expected. I think we should not rely on fact that identifier is a number. Maybe it would be better to add type-checking logic to pass the third argument to insert() and update() functions.

**Comment by AkenRoberts** [comment]
Thank you @alexg-nn. Definitely something that should be looked into.

Unfortunately, I don't have a specific timeline for when I might be able to. There's a pretty extensive to-do list for Doctrine Extensions. If you're able to provide a pull request with relevant tests, I'd happily take a look and merge.
