### ISSUE TITLE
[Loggable] How to get history of entity already deleted?

### ISSUE THREAD

**Issue by pyatnitsev** [doctrine-extensions/DoctrineExtensions#2064]
Hi!

I working on Log Viwer functionality based of this extention. In the docs I have looked using following way:

```php 
$repo = $em->getRepository('Gedmo\Loggable\Entity\LogEntry'); // we use default log entry class
$article = $em->find('Entity\Article', 1 /*article id*/);
$logs = $repo->getLogEntries($article);
```

It works great if acticle with id equals 1 actualy exists. 
this extantion can write action remove, but how to get history of deleted entity? There is no method to do that, existed needs entity object. 

I can add a PR for new method in LogEntryRepository that could get logs by entity's class name and it's id. 

WDYT?

**Comment by svycka** [comment]
Why not just use query builder and select by `objectClass` and `objectId`? why do you need a special method for this?

**Comment by pyatnitsev** [comment]
I can't use revert method. It use entity.

I try to resolve it by passing new entity object with the same class.

**Comment by svycka** [comment]
Hmm not sure what to do with deleted entities maybe use soft delete? I am not sure this lib supports reverting the deleted entity.

**Comment by pyatnitsev** [comment]
This library support it as well. Tomorrow I can post a code :)

**Comment by jkammann1701** [comment]
Hi, how did you managed to revert deleted entities?

**Comment by pyatnitsev** [comment]
So, if you store all props, when entity was created, you can restore it from the history table.
Can you post more details please?

**Comment by jkammann1701** [comment]
So, you don't use the revert method and create the entity 'manually'?

I created an entity and processor . Inside the processor I'm doing what is explained [here](https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/loggable.md) 

```php
namespace App\Entity\Util;

use ApiPlatform\Metadata\Post;
use App\State\RevertChangeProcessor;

#[Post(
    uriTemplate: 'revert_change',
    formats    : ["json", "jsonld"],
    output     : Bare::class,
    processor  : RevertChangeProcessor::class
)]
class RevertChange
{
    public ?int $logId = null;

    public function getLogId(): ?int
    {
        return $this->logId;
    }
}
```

```php
namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Entity\Util\Bare;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\Persistence\ObjectManager;
use Gedmo\Loggable\Entity\LogEntry;
use Gedmo\Loggable\Entity\Repository\LogEntryRepository;

class RevertChangeProcessor implements ProcessorInterface
{
    private ObjectManager $em;
    private LogEntryRepository $logRepo;

    public function __construct(ManagerRegistry $registry)
    {
        $this->em = $registry->getManager();
        $this->logRepo = $this->em->getRepository(LogEntry::class);
    }

    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): Bare
    {
        $logId = $data->getLogId();
        $log = $this->logRepo->find($logId);
        $entity = $this->em->find($log->getObjectClass(), $log->getObjectId());
        $this->logRepo->revert($entity, $log->getVersion());
        $this->em->persist($entity);
        $this->em->flush();

        return new Bare();
    }
}
```

**Comment by mbabker** [comment]
You can't use the `revert()` method on a fully deleted object (for both the ORM and MongoDB ODM) because it requires you to provide a known managed object to revert.  Another issue you're going to run into is that the loggable extension doesn't record the object's state when it logs a remove action, so even if it could revert a deletion, at best it would only be able to go back to the last update action.  And since only changed fields are recorded in each action and not the full object state, you'd have to step back through the revision history for that record to get a complete object, assuming that all required fields exist in the version history.

If you need to be able to restore a deleted object, this would be a better case for using the soft-deleteable extension instead of loggable.

**Comment by jkammann1701** [comment]
Thank you. I'm now using soft-deletable extension to restore deleted objects.
