### ISSUE TITLE
Update or Add installation documentation for Symfony 5

### ISSUE THREAD

**Issue by templton** [doctrine-extensions/DoctrineExtensions#2065]
Hello!

I get started with symfony 5 and install doctrine extensions. 

In the your doc said "edit app/config/config.yml". But such file doesnt exist in symfony skeleton project. 

As I understand it I need edit "config/packages/doctrine.yaml" file ? 

And second. Into the doc written "dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"" 

But now it's need use kernel.project_dir instead kernel.root_dir 

Where can I see entire list of changes?

**Comment by fd6130** [comment]
https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html

Maybe you can install this one for for easy config.

**Comment by andrekutianski** [comment]
> https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
> 
> Maybe you can install this one for for easy config.

Unfortunately, this package appears to be outdated like discuss in https://github.com/stof/StofDoctrineExtensionsBundle/issues/422#issuecomment-771026242

Like @templton suggests in their question, these small changes can confuse sometimes new projects.

**Comment by stephanvierkant** [comment]
I think we should consider StofDoctrineExtensionsBundle being unmaintained. Related issue: https://github.com/symfony/symfony-docs/pull/14909

**Comment by AkenRoberts** [comment]
I wonder if he'd be willing to transfer it to our org. 🤔

**Comment by stephanvierkant** [comment]
We could ask him. That'd be great. Ping @stof

**Comment by VincentLanglet** [comment]
The last option could be a fork
