### ISSUE TITLE
Performance issue when using `AbstractTreeRepository` in a Symfony project with many Doctrine event listeners

### ISSUE THREAD

**Issue by anyt** [doctrine-extensions/DoctrineExtensions#2082]
### Prerequisites
- We are using Symfony 4.4. 
By default, with the Symfony, all the listeners are not initialized until they are requested from the EventManager. It's done by `Symfony\Bridge\Doctrine\ContainerAwareEventManager` class.
- We have hundreds of doctrine event listeners in an application. 

### Current Behaviour
`AbstractTreeRepository::_construct()` method instantiates all the doctrine event listeners for all the entities registered in a system by calling `$em->getEventManager()->getListeners()` in this foreach statement:
https://github.com/Atlantic18/DoctrineExtensions/blob/efe9c08b81e3614f3c1e07ed8cb243569f5e4978/src/Tree/Entity/Repository/AbstractTreeRepository.php#L36-L46

As a result, when using DoctrineExtensions, all the doctrine listeners initialized every time we call `getRepository(Category::class)` and as we are rendering categories in all the pages, this code slows down everything.

### Proposed solution
Instead of search for the event listener, that is an instance of TreeListener, at every request, this can be configurable per entity manager or done in a container compile-time and handled with the setter method in AbstractTreeRepository.

**Comment by AkenRoberts** [comment]
Definitely agree, pretty clear room for improvement here.

This Extensions lib isn't being actively maintained, unfortunately, so I have no timetable for when an improvement like this would be made. Always open to PRs.
