### ISSUE TITLE
Filter not being applied everywhere.

### ISSUE THREAD

**Issue by AdtHO** [doctrine-extensions/DoctrineExtensions#2104]
- I am able to fetch soft-deleted entities using a `$this->entityManager->find()` , i.e. the EntityManger Interface in doctrine. Not sure why this happens but, looks like the filter is not being applied through this.

- Also, when using a doctrine query to fetch entities, relations are not being filtered out either.
Given that I have 2 soft-deletable entities A and B, and entity B related to A with a Many:One relation, when, I enable the filter and fetch Entity A, I will get entities from A filtered, but then the query also fetches every entity B related to A and does not filter out soft-deleted entities from B.

Is there something I am missing out?

- I have directly added the filter the config/doctrine.php
- I enable the filters right before using the doctrine queries too.

**Comment by AdtHO** [comment]
Here are a few related issues too,

https://github.com/Atlantic18/DoctrineExtensions/issues/1463

https://github.com/doctrine/orm/issues/6343

**Comment by AkenRoberts** [comment]
Are you using a bundle to install extensions in Symfony, or configured manually?

**Comment by ahmed-bhs** [comment]
Up @AdtHO any news ?
