### ISSUE TITLE
RelativeSlugHandler vs TreeSlugHandler

### ISSUE THREAD

**Issue by nuryagdym** [doctrine-extensions/DoctrineExtensions#2121]
Hi, 
I did several test to understand what is the difference between RelativeSlugHandler and TreeSlugHandler. They both produce the same outputs. When I configure it in the same way described in the [documentation](http://atlantic18.github.io/DoctrineExtensions/doc/sluggable.html)

Secondly, given the example below:
```
namespace Sluggable\Fixture\Handler;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class User
{
    /**
     * @ORM\Column(length=64)
     */
    private $username;

    /**
     * @Gedmo\Slug(handlers={
     *      @Gedmo\SlugHandler(class="Gedmo\Sluggable\Handler\RelativeSlugHandler", options={
     *          @Gedmo\SlugHandlerOption(name="relationField", value="company"),
     *          @Gedmo\SlugHandlerOption(name="relationSlugField", value="alias"),
     *          @Gedmo\SlugHandlerOption(name="separator", value="/")
     *      })
     * }, separator="-", updatable=true, fields={"username"})
     * @ORM\Column(length=64, unique=true)
     */
    private $slug;
```

```
namespace Sluggable\Fixture\Handler;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Company
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(length=64)
     */
    private $title;

    /**
     * @Gedmo\Slug(handlers={
     *      @Gedmo\SlugHandler(class="Gedmo\Sluggable\Handler\InversedRelativeSlugHandler", options={
     *          @Gedmo\SlugHandlerOption(name="relationClass", value="Sluggable\Fixture\Handler\User"),
     *          @Gedmo\SlugHandlerOption(name="mappedBy", value="company"),
     *          @Gedmo\SlugHandlerOption(name="inverseSlugField", value="slug")
     *      })
     * }, fields={"title"})
     * @ORM\Column(length=64, unique=true)
     */
     private $alias;
```

Provided example is:
```
$company = new Company;
$company->setTitle('KnpLabs');
$em->persist($company);

$gedi = new User;
$gedi->setUsername('Gedi');
$gedi->setCompany($company);
$em->persist($gedi);

$em->flush();

echo $gedi->getSlug(); // outputs "knplabs/gedi"

$company->setTitle('KnpLabs Nantes');
$em->persist($company);
$em->flush();
echo $gedi->getSlug(); // outputs "knplabs-nantes/gedi"
```

what is point of generating combined slug ({company}/{username}) for User?
I mean if the user slug is composed like this ({company}/{username}) in Symfony Route Annotation I can't say:
```
/**
* @Route("/{alias}/{slug}", name="user_page")
*/
public function view(Company $company, User $user){
}
```
nor like this:
```
/**
* @Route("/{slug}", name="user_page")
*/
public function view(User $user){
}
```

**Comment by Guite** [comment]
> I did several test to understand what is the difference between RelativeSlugHandler and TreeSlugHandler. They both produce the same outputs.

Did you also try an example with let's say five levels?

I _guess_ this will be different, like this:

Relative: `five/six`
Tree: `one/two/three/four/five/six`

From this point of view TreeSlugHandler is some kind of recursive, while RelativeSlugHandler is not.

**Comment by nuryagdym** [comment]
So we need to use TreeSlugHandler when it is more than 2 levels? I mean RelativeSlugHandler works only with 2 levels?

**Comment by AkenRoberts** [comment]
Correct. The most common use cases for the two:

**Relative:** Create a combo slug for a parent-child relationship, usually with different entities.
**Tree:** Create a combo slug recursively for a hierarchy. Useful for things like category breadcrumbs. Usually uses one entity that has a relationship to itself.

As for why you'd use them, remember that slugs can mean things other than URLs. And also, just because the slug generates that URL doesn't mean you have to use the generated slug as the `@ParamConverter` value.

**Comment by nuryagdym** [comment]
I want to add this:

> RelativeSlugHandler: Create a combo slug for a (2 level) parent-child relationship, usually with 2 different entities.
> TreeSlugHandler: Create a combo slug recursively for a hierarchy. Useful for things like category breadcrumbs. Usually uses one entity that has a relationship to itself.

Information at the end of `[Sluggable Documentation](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/sluggable.md)` for clarification, is it ok?
