### ISSUE TITLE
Path with parent node IDs only

### ISSUE THREAD

**Issue by jarkt** [doctrine-extensions/DoctrineExtensions#2124]
I need a tree structure with the ability to get all parent nodes up to the root, the root node, the parent node and all direct children.
Theoretical I could use nestedSets, but because of too many tree changes it's not a good choice.
So I use materialized path, but I'm confused about the "TreePathSource".
The path contains not only IDs but something additional. But what? I have nothing to use for it and also I dont't want to use it. I need only a path containing all the parent node ids. How can I achieve this?

Also it would be great to have a direct root-reference. Not optimal but passable would be to cut the ID from the path and load manually.

**Comment by AkenRoberts** [comment]
`@TreePathSource` is the annotation for defining what field to use as the identifier value in the path. If you want to use IDs, then you can put this annotation on your `$id` property.

> If your `TreePathSource` field is of type "string", then the primary key will be concatenated in the form: "value-id". This is to allow you to use non-unique values as the path source.

**Comment by AkenRoberts** [comment]
Could you tell me if you looked at any documentation to help you clarify? Just curious, to see if there's a way I can reorganize to make details like this easier to find. 😇

**Comment by jarkt** [comment]
I've seen it here: https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/tree.md

You're right, there is an important information missing. I've tried to set it on ID, but my IDs are of type UuidInterface and so I get the exception

>In Annotation.php line 206:
>Tree PathSource field - [id] type is not valid. It can be any of the integer variants, double, float or string in class - App\Entity\Example

```
    /**
     * @ORM\Id()
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     * @Gedmo\TreePathSource
     * @Groups({"api"})
     */
    private UuidInterface $id;
```

Maybe it's not possible without changes in DoctrineExtensions.
