### ISSUE TITLE
IpTraceable listener is not documented

### ISSUE THREAD

**Issue by ghost** [doctrine-extensions/DoctrineExtensions#2131]
Hello. I'm building my Symfony 5 application, but I can't find how to configure a listener for IpTraceable. Searched far and wide both in [IpTraceable docs](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/ip_traceable.md) and [Symfony 4 docs](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/symfony4.md), but there is nothing related.

**Comment by deivid11** [comment]
Any news on this or a reference link to know how to configure ipTraceable?

**Comment by AkenRoberts** [comment]
Huh, I'm surprised it was never integrated into the Symfony bundle. (Ref: https://github.com/stof/StofDoctrineExtensionsBundle/pull/233)

Metadata aside, you just need to have Symfony call `IpTraceableListener::setIpValue()` at some point with the current IP address. The "[Code of subscriber class](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/ip_traceable.md#code-of-subscriber-class)" example in the IP Traceable docs shows an example. You can also use the Symfony bundle's [Blameable implementation](https://github.com/antishov/StofDoctrineExtensionsBundle/blob/master/EventListener/BlameListener.php) as another example.
