### ISSUE TITLE
[SoftDeleteable] Use ListenersInvoker to dispatch ORM events

### ISSUE THREAD

**Issue by jorrit** [doctrine-extensions/DoctrineExtensions#2136]
This is a follow up for closed issues #1285 and #1286.

I think it is possible to use the ListenersInvoker to dispatch SoftDeleteable events by dispatching the events via the AdapterInterface implementations. In this way entity listeners would be invoked as well.

Would a PR to this end be acceptable? If so, which branch should I target, master or v2.4?

**Comment by AkenRoberts** [comment]
I'm not sure it will be possible, or worth the effort. We could definitely find a way to use `ListenersInvoker` - the challenge comes from using a custom event. The whole Entity Listeners system is designed for internally-defined lifecycle events (e.g. `postPersist`).

As nifty a feature addition as it would be, I'm concerned about how much maintenance it would take. This repo is already barely keeping up.

**Comment by AkenRoberts** [comment]
@raymondschouten I'd suggest at the very least creating a new issue with your use case and what's limiting you. Or even better, an issue with that + a pseudo-code solution.

I've been in a shadows for years now while others have been maintaining this library. So best chance is to get the idea floated and see what they and the community think!
