### ISSUE TITLE
No cache of metadata when using PhpFileCache

### ISSUE THREAD

**Issue by vladyslavstartsev** [doctrine-extensions/DoctrineExtensions#2142]
When I use `Gedmo` extensions with PhpFileCahe (the one that is recommended  https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/caching.html#phpfilecache  ), I see that 
https://github.com/Atlantic18/DoctrineExtensions/blob/f0d059b784200ff63c9c2b06e96e8e3b447423bc/lib/Gedmo/Mapping/ExtensionMetadataFactory.php#L105
provides `null` as a 3rd param, that means that `lifetime` of this cache is nothing. I means on next request I'll need to parse it again, since in driver code there is a check that `lifetime` MUST not be `null`.

I think this param should be`0`. This way I will not need to re parse it again and again on next request

**Comment by FoxxMD** [comment]
I believe I'm also experiencing this issue except its never parsed again and I lose extension functionality
