### ISSUE TITLE
Root cannot be changed manually, change parent instead 

### ISSUE THREAD

**Issue by Nebojsaa** [doctrine-extensions/DoctrineExtensions#2155]
Version of doctrine/orm that I am using is: "2.7"
Scenario in place: 
1. I come to Menu and try to delete one item in the menu itself and this is the message that I got. 
2. ![Screenshot from 2020-07-16 15-59-15](https://user-images.githubusercontent.com/3692864/87680121-52126c80-c77d-11ea-996f-ecebd3fa1c70.png)

Desired scenario:
I want to delete the item from the menu itself. 
Obviously I have checked this link, but my project is depending heavily on newest Doctrine/orm - https://github.com/Atlantic18/DoctrineExtensions/issues/1026

**Comment by AkenRoberts** [comment]
Reopening this since the original was closed. Thank you for referencing it!

If anyone is experiencing this issue, please react or comment.

**Comment by signor-pedro** [comment]
Seems like we're experiencing the same with the new `doctrine/orm` 2.10 release

**Comment by maciekpaprocki** [comment]
I started getting it too, weirdly on doctrine 2.10.0

**Comment by cfoehrdes** [comment]
> We are experiencing the same issue as soon as a second flush is called during execution of a single request. The gedmo tree listener on first flush handles the tree node insertions and modifies the nodes. A second flush detects the modification of the nodes by the tree listener from first flush as a scheduled update and throws the "Root cannot be changed manually, change parent instead" exception.
> 
> We are running on doctrine/orm 2.10 and gedmo 3.1.0 (via stof/doctrine-extensions-bundle 1.6.0)

We downgraded doctrine/orm to 2.9.* which allowed gedmo 3.2.0 and this combination is working perfectly fine
