### ISSUE TITLE
setup auto update in packagist.org

### ISSUE THREAD

**Issue by svycka** [doctrine-extensions/DoctrineExtensions#2162]
@AkenRoberts I think you made mistake and tagged the wrong branch.

**Comment by svycka** [comment]
@AkenRoberts if possible can you merge https://github.com/Atlantic18/DoctrineExtensions/pull/2163 when fixing 3.0 release because it has small  BC break would be nice to have it now?

**Comment by AkenRoberts** [comment]
Yikes, yes I did. 🤦 Thank you for pointing it out.

**Comment by AkenRoberts** [comment]
Fixed with [3.0.0-beta2](https://github.com/Atlantic18/DoctrineExtensions/releases/tag/v3.0.0-beta2) tag.

**Comment by svycka** [comment]
@AkenRoberts seems like you created tag but packagist did not update available versions and 3.0.0-beta2 is not available in https://packagist.org/packages/gedmo/doctrine-extensions because the project is not configured to auto-update it requires manual update...

**Comment by svycka** [comment]
Seems I can update myself so updated manually, but would be nice if you have access make it auto updatable

**Comment by AkenRoberts** [comment]
I don't have the permissions to. ☹️

**Comment by svycka** [comment]
@l3pp4rd can you help us with this?
