### ISSUE TITLE
SoftDelete messes with "unique" columns

### ISSUE THREAD

**Issue by bkrnetic** [doctrine-extensions/DoctrineExtensions#2184]
Hi,

I have an issue with soft deleted entities.

Technology:
Php 7.4
Symfony 5
Doctrine
PostgreSQL

Entity implements SoftDeletable behaviour and has a `boolean` column named `unique` (check the sample below).

```
class Foo
{
    use UuidPrimaryKeyEntityTrait;
    use TimestampableEntity;
    use SoftDeleteableEntity;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    private $required;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    private $unique;
}
```

When I delete an entity and when I fetch it with native query afterwards, it sets the value of `$unique` field to `null` even it is not nullable (in database it remains false, so it has to do something with Gedmo bundle and Doctrine, I would say, as well as with the fact that column name is a keyword in most of the database engines). On the other hand, there are no issues with another `boolean` field `$required` .

One of the solutions I came up with is to set default value of `$unique` field which prevents it being set to `null` but I would like to know what really happens in the background.

Anybody got an idea?

Thanks in advance,
Bruno

**Comment by LauLaman** [comment]
When using SLQ keywords you'll need to [escape it](doctrine-docs) like:
```php
/**
 * @ORM\Column(name="`unique`")
 */
private $unique;
```
This works for MySQL though. Not sure about PostgreSQL

[doctrine-docs]: https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#quoting-reserved-words
