### ISSUE TITLE
[Loggable] Are Doctrine ODM Custom Mapping Types supported?

### ISSUE THREAD

**Issue by borodiliz** [doctrine-extensions/DoctrineExtensions#2189]
First of all, thank you very much for this package!

I'm trying to use `Loggable` with [Doctrine MongoDB ODM Custom Mapping Types ](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.1/reference/custom-mapping-types.html), as an example, with the following code I'm just storing a DateTime in unix timestamp format:

```php
//src/Doctrine/Type/MyType.php

namespace App\Doctrine\Type;

use Doctrine\ODM\MongoDB\Types\ClosureToPHP;
use Doctrine\ODM\MongoDB\Types\Type;

/**
 * My custom datatype.
 */
class MyType extends Type
{
    // This trait provides default closureToPHP used during data hydration
    use ClosureToPHP;

    public function convertToPHPValue($value): \DateTime
    {
        // This is called to convert a Mongo value to a PHP representation
        return new \DateTime('@'.$value);
    }

    public function convertToDatabaseValue($value)
    {
        // This is called to convert a PHP value to its Mongo equivalent
        return $value->getTimestamp();
    }
}

```
```php
// src/Document/MyDocument.php
    ...
    /**
     * @var DateTime
     *
     * @MongoDB\Field(type="MyType")
     * @Gedmo\Versioned
     *
     */
    private $myProperty;
    ...

```

```yaml
// config/packages/doctrine_mongodb.yaml
doctrine_mongodb:
    types:
        MyType: App\Doctrine\Type\MyType

```

The Custom Mapping Type is working without problems and data is correctly stored as unix timestamp on my document:
```json
{
    ...
    "myProperty" : 1610561777
}
```

But `Loggable` stores the following:

```json
/* 1 */
{
   ....
    "objectClass" : "App\\Document\\MyDocument",
    "version" : 1,
    "data" : {
        "myProperty" : {}
    }
}
```

Thanks in advance for your time.

**Comment by AkenRoberts** [comment]
Hmph, probably not supported fully. I created a quick test scenario, and I get all of the `DateTime` data stored in the log entry:

```
{"myCustomDate":{"timezone_type":3,"date":"2021-01-24 00:52:37.653896","timezone":"UTC"}}
```

This *does* get converted into a `DateTime` when fetching the log entry via Doctrine repository, though. I'd have to dive into all the internals of Gedmo & Doctrine to see where this flow is going. I know that with other extensions, the types are kind of hardcoded (like Timestampable, for example, can't use custom types). Could be a similar situation here.

What version of Extensions are you using, btw? I tested this on the 3.x branch which uses a more up-to-date version of ODM, which may help.

**Comment by borodiliz** [comment]
Thanks for your response @AkenRoberts. My environment:

```
root@dev:/var/www# composer show|grep "gedmo\|odm"
doctrine/mongodb-odm                     2.1.3              PHP Doctrine MongoDB Object Document Mapper (ODM) provides transparent persistence for PHP objects to MongoDB.
doctrine/mongodb-odm-bundle              4.2.2              Symfony2 Doctrine MongoDB Bundle
gedmo/doctrine-extensions                v3.0.0             Doctrine2 behavioral extensions
```

The aforementioned `DateTime` case was just an example, actually I'm using `Custom Mapping Types` in conjunction with [myclabs/php-enum](https://github.com/myclabs/php-enum)
```php
//src/Enum/MyEnum.php
<?php 

namespace App\Enum;

use MyCLabs\Enum\Enum;

/**
 *
 * @method static self FOO()
 * @method static self BAR()
 */
class MyEnum extends Enum
{
    private const FOO = 'foo';
    private const BAR = 'bar';
}

```

```php
//src/Doctrine/Type/MyEnumType.php
<?php

namespace App\Doctrine\Type;

use Doctrine\ODM\MongoDB\Types\ClosureToPHP;
use Doctrine\ODM\MongoDB\Types\Type;

class MyEnumType extends Type
{

    use ClosureToPHP;

    public function convertToPHPValue($value)
    {
        return new MyEnum($value);
    }

    public function convertToDatabaseValue($value)
    {
        return $value->getValue();
    }

}
```
So I rely on the `Custom Mapping` all the conversion string<->enum.  My documents look like the following:

```php

    /**
     * @var MyEnum
     *
     * @MongoDB\Field(type="MyEnumType")
     * @Gedmo\Versioned
     *
     */
    private MyEnum $myProperty;

    /**
     * @return MyEnum
     */
    public function getMyProperty(): MyEnum
    {
        return $this->myProperty;
    }

    /**
     * @param MyEnum $myProperty
     *
     * @return self
     */
    public function setMyProperty(ServiceStatus $myProperty): self
    {
        $this->myProperty = $myProperty;

        return $this;
    }
```

A solution could be to implement the conversion string<->enum on all my setter/getters and to not use `Custom Types`, but I think is not elegant at all.

**Comment by lordrhodos** [comment]
I am having similar issues with the grouped sortable behavior on a many-to-one association where the target entity uses the ramsey/uuid as identifier type:

**Location**

```php 
    /**
     * @Gedmo\SortableGroup()
     * @ORM\ManyToOne(targetEntity="Cvs\Model\Project\Project")
     */
    private Project $project;

    /**
     * @Gedmo\SortablePosition()
     * @ORM\Column(name="position", type="integer")
     */
    private int $position;
``` 

**Project** 

```php 
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="uuid")
     */
    private UuidInterface $id;
``` 

The error I get during an integration test is the following:

```shell
Doctrine\DBAL\Exception: An exception occurred while executing 'SELECT MAX(l0_.position) AS SCLR_0 FROM locations l0_ WHERE l0_.project_id = ?' with params ["3104b264-904f-4f1b-a56a-4ae7d166bce9"]:

oci_bind_by_name(): Invalid variable used for bind
```
as you can see I am using an oracle database, but this should not be the issue, I think the main issue here ist that the listener does not resolve the correct type when calling `setParameter`:

here

https://github.com/doctrine-extensions/DoctrineExtensions/blob/320adb6f9903a0aded020d7dab709525a49c6a8c/src/Sortable/Mapping/Event/Adapter/ORM.php#L42

I have not looked into other behaviors / feature, but looking at the issue tracker it seems to be an issue at other parts as well.

@AkenRoberts how do you want this to be handled, should I create a new issue addressing this in general or do you want to continue using  this issue for all other occurences?
