### ISSUE TITLE
[Translatable] Delete a translation

### ISSUE THREAD

**Issue by gianvito** [doctrine-extensions/DoctrineExtensions#2192]
Hi all,
is there a simple way to remove a translation for a given language on an entity marked as Translatable.
I can only find ways to add new languages, but not to remove a language that was previously added.

Thanks!

**Comment by AkenRoberts** [comment]
Extensions doesn't provide an easy API for it at this time (`TranslatableAdapter` has a find method, but I'm not sure how easy it would be to use it).

Your best bet is likely to grab the repository for `Gedmo\Translatable\Entity\Translation`, and find the entry based on the object, locale, etc. And then just remove via Doctrine's EntityManager like any other removal.

If that doesn't work let us know. It's a good idea to add that to Extensions' `TranslationRepository`.
