### ISSUE TITLE
[Sluggable] Regenerate slug for empty string

### ISSUE THREAD

**Issue by wimski** [doctrine-extensions/DoctrineExtensions#2198]
The documentation says the following.

> Note: in previous versions empty strings would also cause the slug to be regenerated. This behaviour was changed in v2.3.8.

When using sluggable with strongly typed properties for non-nullable columns I'm running into issues.

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

class MyEntity
{
    /**
     * @ORM\Column(name="title", type="string", length=255, nullable=false)
     */
    protected string $title;

    /**
     * @ORM\Column(name="slug", type="string", length=255, nullable=false)
     * @Gedmo\Slug(fields={"title"})
     */
    protected string $slug;

    public function  __constructor()
    {
        $this
            ->setTitle('')
            ->setSlug('');
    }

    public function getTitle(): string
    {
        return $this->title;
    }
    
    public function setTitle(string $title): self
    {
        $this->title = $title;
        
        return $this;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }
    
    public function setSlug(string $slug): self
    {
        $this->slug = $slug;
        
        return $this;
    }
}
```

The slug of this entity is never `null`, because I want it to always consistently be a string. I believe this is very valid use-case, because what's the point of having slug that is `null`?

I've looked into extending the `SluggableListener`, but the logic for determining if the slug should be regenerated is buried deep in a method and the method itself is private, so not extendable.

How would you approach this situation and what was the reasoning behind the change of not regenerating empty strings?

**Comment by leonwitlifconnectiv** [comment]
The same issue comes up when using PHP 8.0 new constructor property promotion feature and initializing the slug as an empty string:
```php
public function __construct(
    private readonly int $id = 0,
    private string $slug = "", // <---
    private string $title = "",
    private ?string $description = null,
) {
}
```
