### ISSUE TITLE
[Tree] entity association (help needed)

### ISSUE THREAD

**Issue by skianter** [doctrine-extensions/DoctrineExtensions#2209]
I have 2 entity, **Agent** and **AgentAssociation** (id | agent_id | parent_id | begin | end, and other fields).
In this way each Agent can have more parents, and for each parent I can indicate the begin and the end of the relationship, and so the history of relatioships.
But how can I manage all that with nested-set Tree?

**Comment by skianter** [comment]
Thanks very much for helping...  
Maybe my question is too stupid to deserve a reply, I'm sorry for that.

**Comment by AkenRoberts** [comment]
@skianter Your question is certainly not stupid. This project just doesn't see much activity, so I apologize for that.

You _might_ be able to use nested sets for this model. Your `AgentAssociation` would hold all of the hierarchy, and an `Agent` ID may be duplicated in that hierarchy to model multiple parents.

It has the down side of needing to fetch another entity to get all the information needed for display (if you wanted to show a tree of all Agent names, for example, you'd have to fetch all of the appropriate `Agent` records, too).

**Comment by skianter** [comment]
Thanks for your kind reply and for your great job, 
I appreciate
