### ISSUE TITLE
Meeting problem while using symfony/uuid as primary key type

### ISSUE THREAD

**Issue by pink6440** [doctrine-extensions/DoctrineExtensions#2216]
Using 3.0.4 of the Doctrine Extensions
Using symfony 5.2.6 version 

Using symfony/uuid as type for my primary ID, i had met some problems with the tree behaviour.

The repository does not end up retrieve children because the condition where root_id=... is not using the database representation of the uuid but the default string value of the uuid object.

[Here is some discussion about that ](https://github.com/symfony/symfony/issues/40687)

It worked fine with ramsey/uuid.

Quoting @stof :
> if you are using the UuidType of the symfony package, you need to pass the type in the third argument of setParameter for things to work fine. If you don't, the ORM will cast the parameter as string (due to using the default type) and the UuidType of Symfony does not use the string representation of the Uuid object as the database representation.

**Comment by 1994rstefan** [comment]
Stumbled across this issue today... As you quoted, the UID gets converted to a String, but is saved as Binary in the Databse, thus not getting any results. As a quick fix I have changed the code in `.../src/Tree/Entity/Repository/NestedTreeRepository.php:217` to:

```
                    $qb->where($qb->expr()->eq('node.'.$config['parent'], ':pid'));
                    $identifiers = $wrapped->getIdentifier(false);
                    $identifierValue = reset($identifiers);
                    $identifierKey = key($identifiers);
                    $identifierType = $wrapped->getMetadata()->getFieldMapping($identifierKey)['type'];
                    $qb->setParameter('pid', $identifierValue, $identifierType);
```

At least the `getChildren()`-Method of the repository is working now. I am sure, there are more changes required/it is not the only place where the field type is not passed correctly, but without further investigation I can't tell for sure.

**Comment by maidmaid** [comment]
I found a workaround. The main idea is to override the tree listener so that it uses a custom query builder able to understand ulids.

<details>
 <summary>See the code to override the tree listener</summary>

```yaml
# config/packages/stof_doctrine_extensions.yaml
stof_doctrine_extensions:
    ...
    class:
        tree: \App\Gedmo\Tree\UlidAwareTreeListener
```

```php
// src/Gedmo/Tree/UlidAwareTreeListener.php
<?php

namespace App\Gedmo\Tree;

use App\Gedmo\Mapping\Event\Adapter\UlidAwareTreeAdapter;
use Doctrine\Common\EventArgs;
use Gedmo\Tree\TreeListener;

class UlidAwareTreeListener extends TreeListener
{
    protected function getEventAdapter(EventArgs $args)
    {
        $adapter = new UlidAwareTreeAdapter();
        $adapter->setEventArgs($args);

        return $adapter;
    }
}
```

```php
// src/Gedmo/Mapping/Event/Adapter/UlidAwareTreeAdapter.php
<?php

namespace App\Gedmo\Mapping\Event\Adapter;

use App\Doctrine\UlidAwareEntityManager;
use Gedmo\Mapping\Event\Adapter\ORM as BaseAdapterORM;
use Gedmo\Tree\Mapping\Event\TreeAdapter;

class UlidAwareTreeAdapter extends BaseAdapterORM implements TreeAdapter
{
    public function getObjectManager()
    {
        return new UlidAwareEntityManager(parent::getObjectManager());
    }
}

```

```php
// src/Gedmo/Mapping/Event/Adapter/UlidAwareTreeAdapter.php
<?php

namespace App\Gedmo\Mapping\Event\Adapter;

use App\Doctrine\UlidAwareEntityManager;
use Gedmo\Mapping\Event\Adapter\ORM as BaseAdapterORM;
use Gedmo\Tree\Mapping\Event\TreeAdapter;

class UlidAwareTreeAdapter extends BaseAdapterORM implements TreeAdapter
{
    public function getObjectManager()
    {
        return new UlidAwareEntityManager(parent::getObjectManager());
    }
}
```

```php
// src/Doctrine/UlidAwareEntityManager.php
<?php

namespace App\Doctrine;

use Doctrine\ORM\Decorator\EntityManagerDecorator;

class UlidAwareEntityManager extends EntityManagerDecorator
{
    public function createQueryBuilder()
    {
        return new UlidAwareQueryBuilder($this);
    }
}
```

```php
// src/Doctrine/UlidAwareQueryBuilder.php
<?php

namespace App\Doctrine;

use Doctrine\ORM\QueryBuilder;
use Symfony\Component\Uid\Ulid;

class UlidAwareQueryBuilder extends QueryBuilder
{
    public function setParameter($key, $value, $type = null)
    {
        if (null === $type) {
            if ($value instanceof Ulid) {
                $type = 'ulid';
            }

            if (method_exists($value, 'getId')) {
                if ($value->getId() instanceof Ulid) {
                    $value = $value->getId();
                    $type = 'ulid';
                }
            }
        }

        return parent::setParameter($key, $value, $type);
    }
} 
```
</details>

<details>
 <summary>See the code to fix the repos extending NestedTreeRepository</summary>

```php
class CategoryRepository extends NestedTreeRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct(new UlidAwareEntityManager($em), $em->getClassMetadata(Category::class));
    }
} 
```
</details>

**Comment by kl3sk** [comment]
@maidmaid just one thing ... Thank you 😄 

@stof @l3pp4rd did you consider this solution ?

**Comment by kl3sk** [comment]
> @maidmaid just one thing ... Thank you 😄
> 
> @stof @l3pp4rd did you consider this solution ?

Just to avoid some errors like this
![image](https://github.com/doctrine-extensions/DoctrineExtensions/assets/148959785/86f899b8-6bea-4471-9dbb-9b48b23fb883)

Do not forget to type as `Ulid` the `getId()` method.
