### ISSUE TITLE
Doctrine\Persistence\Mapping\AbstractClassMetadataFactory::getCacheDriver() is deprecated

### ISSUE THREAD

**Issue by holtkamp** [doctrine-extensions/DoctrineExtensions#2227]
As of Doctrine/Persistence 2.2 getCacheDriver was deprecated:
https://github.com/doctrine/persistence/blob/8b420f7065c2d6c0149ff523816f6b28391581d1/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php#L105-L110

It is used by a number of extensions: https://github.com/doctrine-extensions/DoctrineExtensions/search?q=getCacheDriver

I created this issue to keep track of this deprecation.

A potential solution was already mentioned here: https://github.com/doctrine-extensions/DoctrineExtensions/pull/2226#pullrequestreview-660767646

**Comment by franmomu** [comment]
👍 Fixed in https://github.com/doctrine-extensions/DoctrineExtensions/pull/2373
