### ISSUE TITLE
PHP 8+: Support for attributes

### ISSUE THREAD

**Issue by makraz** [doctrine-extensions/DoctrineExtensions#2235]
What are your plans for PHP 8+?
Is there any WIP about mapping attributes so we could use #[ORM\Column] instead of /** @var ORM\Column */?
If not, I'll like to work on this.

**Comment by ndench** [comment]
I'd love to see this. I currently can't migrate to `#[ORM\Column]` because the extensions won't detect the properties anymore. Let me know if there's anything I can do to help.

**Comment by fridde** [comment]
@makraz You might want to edit your title to "PHP 8+: Support for attributes" since I initially thought you were missing some special attribute when in fact you wish for attributes to be supported *at all*.

Good initiative!

**Comment by makraz** [comment]
Thanks @fridde for the feedback

**Comment by bpolaszek** [comment]
> I'd love to see this. I currently can't migrate to `#[ORM\Column]` because the extensions won't detect the properties anymore. Let me know if there's anything I can do to help.

```php
/**
 * @Gedmo\Timestampable(on="create")
 */
#[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
#[Groups([self::LIST, self::VIEW])]
public \DateTimeImmutable $createdAt;
```

Not elegant, but works on my side.

**Comment by fridde** [comment]
@bpolaszek Woah, for some reason I didn't realize that we could mix annotations and attributes. I thought that Gedmo would use the system I declared in ```doctrine.yaml``` with the setting for doctrine.orm.mappings.App.type (which I set to "attribute").

Thanks for pointing out this workaround. This will be useful during the transition.

**Comment by ndench** [comment]
That's a good workaround @bpolaszek. Unfortunately it doesn't work for blameable because the BlameableListener uses doctrine annotations to determine if the property is an association. 

https://github.com/doctrine-extensions/DoctrineExtensions/blob/0bce65005d4430e1037df143eab47b929d127c84/src/Blameable/BlameableListener.php#L29

**Comment by scroach** [comment]
> That's a good workaround @bpolaszek. Unfortunately it doesn't work for blameable because the BlameableListener uses doctrine annotations to determine if the property is an association.
> 
> https://github.com/doctrine-extensions/DoctrineExtensions/blob/0bce65005d4430e1037df143eab47b929d127c84/src/Blameable/BlameableListener.php#L29

Why shouldn't this work? The BlameableListener works on the ClassMetadata provided by doctrine so it should not matter how you mapped your fields.

Anyway I would definitely favor having attributes, I try to prevent mixing annotations and attributes.

**Comment by knojector** [comment]
> > I'd love to see this. I currently can't migrate to `#[ORM\Column]` because the extensions won't detect the properties anymore. Let me know if there's anything I can do to help.
> 
> ```
> /**
>  * @Gedmo\Timestampable(on="create")
>  */
> #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
> public \DateTimeImmutable $createdAt;
> ```
> 
> Not elegant, but works on my side.

Hi @bpolaszek,
I ran into the same issue but unfortunately the date fields are always populated with `null`. Do I need to adjust my doctrine.yml in order to mix attributes and annotations? This is my current mapping configuration:
`        mappings:
            App:
                type: attribute
                dir: '%kernel.project_dir%/src/Entity/'
                prefix: 'App\Entity\'`

**Comment by franmomu** [comment]
Support for ORM attribute mapping was added in `3.2`, I'm closing this one in favor of https://github.com/doctrine-extensions/DoctrineExtensions/issues/2363 where we can keep track of the needed work, any help is welcome!
