### ISSUE TITLE
[Timestampable] updatedAt set on creation when configured with on="update"

### ISSUE THREAD

**Issue by benja-M-1** [doctrine-extensions/DoctrineExtensions#2237]
Hi, 

This is more a question than a bug report.

I use the Timestampable extension to set an `updatedAt` column on update.
It appears that my entities have a value when persisted for the first time. I was expecting that they only have a value after the first persist, like when using the `change` value.

Is it expected?

Thank you very much for your answer :)

**Comment by julkwel** [comment]
Yes, i think it's expected, the `createdAt` value will be the default value of `updatedAt` when creating new entity object.

Flow : Since at creation, the last update of the object is his creation.

**Comment by benja-M-1** [comment]
I close my question since @julkwel kindly answered :)
