### ISSUE TITLE
[Bug] Working with different managers

### ISSUE THREAD

**Issue by dim49v** [doctrine-extensions/DoctrineExtensions#2247]
When creating an entity with sortable extension, a `flush` of one manager is called, during which the `eventListener` is called. In this event, a new entity with timestamp extension is created and flushed, which is managed by another manager. But in the process I get an error `class X was not found in the chain configured namespaces`. Debugging showed that the `sortableListener` is trying to change the order of the entity from the first manager using the second manager from `LifecycleEventArgs`, which does not manage the first entity.

**Comment by AkenRoberts** [comment]
If you could provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), that would help immensely.
