### ISSUE TITLE
Tree broken on ORM 2.10 

### ISSUE THREAD

**Issue by SimonVanacco** [doctrine-extensions/DoctrineExtensions#2261]
Hi, 
This is probably related to #2256, i've had to downgrade to doctrine/orm 2.9 because i had this error : 
**  Root cannot be changed manually, change parent instead **

Downgrading made the tree component work again for me. 

Here is a stacktrace : 
![image](https://user-images.githubusercontent.com/5305627/136225500-19a9de2f-65df-4c03-bc07-e1828bf75de1.png)

This happened by just persisting a new  "@Gedmo\Tree(type="nested")" tagged entity. 

If someone has an idea it would be really appreciated ! 
Thanks !

**Comment by pfpro** [comment]
same problem here

**Comment by franmomu** [comment]
Hi, thanks for reporting, could you try if https://github.com/doctrine-extensions/DoctrineExtensions/pull/2272 solves the issue? thanks!

**Comment by SimonVanacco** [comment]
Hi @franmomu,
I just tried the fix and it seems to solve this issue, thanks !
