### ISSUE TITLE
[Loggable] How to handle a relation ManyToOne with a LogEntry specific Entity

### ISSUE THREAD

**Issue by vince83110** [doctrine-extensions/DoctrineExtensions#2268]
We use Loggable for some of our entites.

What we want is to use ApiSubResource (from ApiPlatform) to easily have endpoints for our log tables.

First, we defined a new entity for our Loggable entity : 

` * @Gedmo\Loggable(logEntryClass="App\Domain\Product\Entity\History\ProductPriceHistory")`

Then we defined the logEntry entity like this : 
```

/**
 * @ApiResource()
 *
 * @ORM\Table(
 *     name="product_price_history",
 *     options={"row_format":"DYNAMIC"},
 *  indexes={
 *      @ORM\Index(name="product_price_idx", columns={"object_class"}),
 *      @ORM\Index(name="product_price_date_idx", columns={"logged_at"}),
 *      @ORM\Index(name="product_price_user_idx", columns={"username"}),
 *      @ORM\Index(name="product_price_version_idx", columns={"object_id", "object_class", "version"})
 *  }
 * )
 * @ORM\Entity(repositoryClass="Gedmo\Loggable\Entity\Repository\LogEntryRepository")
 */
class ProductPriceLog extends AbstractLogEntry
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ProductPrice", inversedBy="logs")
     * @JoinColumn(name="object_id", referencedColumnName="id")
     */
    protected $objectId;
```

But the main problem is : Gedmo Loggable Listener uses ID and not Objects to persist the log.

So it can't work, Doctrine will expect the field to be an object, not an ID.

Translatable uses Objects, why Loggable was made in this way ? Can't we easily find a solution ? We can "override" the Listener, but not a big fan.

**Comment by MisatoTremor** [comment]
You could work with an `Doctrine\Common\EventSubscriber` or maybe its subclass `Gedmo\Mapping\MappedEventSubscriber` on the `prePersist` (and `postLoad` if you need to restore the object when loading from the DB) events.
