### ISSUE TITLE
New translation changes default values

### ISSUE THREAD

**Issue by micayael** [doctrine-extensions/DoctrineExtensions#2269]
Hi

I have configured an entity with translatable annotations and when I try to save a new translation, not being the default locale, a new record is inserted in the translation table, but at the same time, it replaces the values of the main table, where according to the documentation should always remain the default translation.

```php
$category = new Category();

// attributes without translations
$category->setNumber(100000);
$category->setDate(new \DateTime());

// attributes with translations: @Gedmo\Translatable()
$category->setName('name es');
$category->setDescripcion('descr es');

$this->entityManager->persist($category);
$this->entityManager->flush(); 

// create translation: in the main table, this updates the texts, at the same time it creates the records in the translation table, and so the default locale is lost.
$category->setName('name en');
$category->setDescripcion('descr en');
$category->setTranslatableLocale('en');

$this->entityManager->persist($category);
$this->entityManager->flush(); 
```
if I use the Translation Repository, it works as expected. The default locale remains without changes at the main table and a new registry on the translation table is inserted. But I really want to know if the first way is posible

```php
$repository->translate($category, 'name', 'en', 'name en')
    ->translate($category, 'description', 'en', 'descr en')
;
```

Can some body give me some help?

**Comment by patrickbussmann** [comment]
Which version of `doctrine/orm` do you have?
I had the same issue and solved it with `2.9.*` instead `2.10.*`.

**Comment by franmomu** [comment]
Can you please try the latest release (`3.3.1`) to see if this issue is fixed? thanks!

**Comment by micayael** [comment]
Thanks @patrickbussmann and @franmomu 

With 3.3.1 it works perfectly
