### ISSUE TITLE
[Sortable] Automatically maintain SortablePosition

### ISSUE THREAD

**Issue by mbrodala** [doctrine-extensions/DoctrineExtensions#2274]
This is more a question than a request since I am not sure this should already work:

Given a collection property with a few related entities, These related entites have a `SortablePosition` property.

If I manually reorder the related entities in the collection, I expect the `SortablePosition` to be automatically updated on all entities in the collection. ATM it looks like I need to manually update the `SortablePosition` for all related entities instead.

Did I just miss something?

**Comment by franmomu** [comment]
I'm not using this extension, but looking at the [`SortableListener`](https://github.com/doctrine-extensions/DoctrineExtensions/blob/d9c13053448ffbe2100492e192e1ac85812ddf36/src/Sortable/SortableListener.php) seems like this is not supported. 

I guess that would require another class to use it as attribute/annotation like `SortableCollection` and modify the listener to listen to collection updates.
