### ISSUE TITLE
[help] Use Id instead of username while logging

### ISSUE THREAD

**Issue by Xbirdfr** [doctrine-extensions/DoctrineExtensions#2281]
Hi,
I use gedmo/loggable and it's working fine, but it use username in table "ext_log_entries", and i want to use user Id instead.
I have not found anything so far in docs, so is it possible to do this ?

thanks

**Comment by Xbirdfr** [comment]
Hi, I still need help on this 🙏

**Comment by franmomu** [comment]
Hi, seeing https://github.com/doctrine-extensions/DoctrineExtensions/blob/4fc3b4d9a90b9f684c4ed6371642dc1ec87b374a/doc/loggable.md#loggable-username, I guess you can call:

```php
$loggableListener->setUsername('userId');
```
maybe we should change the method name to `setUserIdentifier`.

**Comment by franmomu** [comment]
If you are using loggable extension right now and it's working fine you should have some "glue" code to make it work, in case you are using Symfony, are you using https://github.com/stof/StofDoctrineExtensionsBundle?

If that's the case, the bundle for examples defines two services in https://github.com/stof/StofDoctrineExtensionsBundle/blob/a2bffca41974d1c968557b343e269a60a8d5ffa4/src/Resources/config/loggable.xml#L12-L23

The first one is the Gedmo one and the other one is in charge of setting the username of the logged user:

https://github.com/stof/StofDoctrineExtensionsBundle/blob/a2bffca41974d1c968557b343e269a60a8d5ffa4/src/EventListener/LoggerListener.php#L44-L48 

in that case you could override that service to set the user id.

**Comment by Xbirdfr** [comment]
I'm using Stof yes

so i have to create a listener into srv/EventListener to replace the one comming with stof ?

thanks for replying

**Comment by Xbirdfr** [comment]
it's working !

if someone need the solution

1) create a src\EventListener\LoggerListener.php file, and copy the content of 

https://github.com/stof/StofDoctrineExtensionsBundle/blob/a2bffca41974d1c968557b343e269a60a8d5ffa4/src/EventListener/LoggerListener.php#L44-L48

2) edit the `$this->loggableListener->setUsername()` function

on my side, I got the user object from the token, and then I use 
`$user->getFullname() . ' - '. $user->getMainGroup()->getName()`

those two getter comming from my user entity

So my final code is : 

```
<?php

namespace Stof\DoctrineExtensionsBundle\EventListener;

use Gedmo\Loggable\LoggableListener;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\HttpKernelInterface;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

/**
 * Sets the username from the security context by listening on kernel.request
 *
 * @author Christophe Coevoet <stof@notk.org>
 */
class LoggerListener implements EventSubscriberInterface
{
    private $authorizationChecker;
    private $tokenStorage;
    private $loggableListener;

    public function __construct(LoggableListener $loggableListener, TokenStorageInterface $tokenStorage = null, AuthorizationCheckerInterface $authorizationChecker = null)
    {
        $this->loggableListener = $loggableListener;
        $this->tokenStorage = $tokenStorage;
        $this->authorizationChecker = $authorizationChecker;
    }

    /**
     * @internal
     */
    public function onKernelRequest(RequestEvent $event)
    {
        if (HttpKernelInterface::MASTER_REQUEST !== $event->getRequestType()) {
            return;
        }

        if (null === $this->tokenStorage || null === $this->authorizationChecker) {
            return;
        }

        $token = $this->tokenStorage->getToken();

        if (null !== $token && $this->authorizationChecker->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            /**
             * @var User $user
             */
            $user = $token->getUser();
            
            $this->loggableListener->setUsername($user->getFullname() . ' - '. $user->getMainGroup()->getName());
        }
    }

    public static function getSubscribedEvents()
    {
        return array(
            KernelEvents::REQUEST => 'onKernelRequest',
        );
    }
}
```

**Comment by Xbirdfr** [comment]
Actually, I think I fail something :

I got sometime an error like this :

```
Expected to find class "App\EventListener\LoggerListener" in file "/local.dev.src/EventListener/LoggerListener.php" while importing serv
  ices from resource "../src/", but it was not found! Check the namespace pre
  fix used with the resource in /local.dev/src/../config/servic
  es.yaml (which is being imported from "/local.dev/src/Kernel.
  php").
```

and

```
Expected to find class "App\EventListener\LoggerListener" in file "/local.dev/src/EventListener/LoggerListener.php" while importing serv
  ices from resource "../src/", but it was not found! Check the namespace pre
  fix used with the resource.
```

Do I need to setup the ' src\EventListener\LoggerListener.php ' file in an other directory ?

**Comment by franmomu** [comment]
Hi @Xbirdfr, the place of the file doesn't matter as long the service is properly registered, I would check the namespace of the listener as suggested by the error message.

For docs about symfony services: https://symfony.com/doc/current/service_container.html

For service overriding: https://symfony.com/doc/current/service_container/service_decoration.html

I'm closing this issue as it is not an issue of this package anymore
