### ISSUE TITLE
Change listeners order globaly

### ISSUE THREAD

**Issue by mervit** [doctrine-extensions/DoctrineExtensions#2292]
Hi,
is there a way to change order of listeners globaly for all project? I need to slug and tree be generated allways before translation.

In documentation i found this code:
```
<?php
$evm = new \Doctrine\Common\EventManager();
$treeListener = new \Gedmo\Tree\TreeListener();
$evm->addEventSubscriber($treeListener);
$sluggableListener = new \Gedmo\Sluggable\SluggableListener();
$evm->addEventSubscriber($sluggableListener);
$translatableListener = new \Gedmo\Translatable\TranslatableListener();
$translatableListener->setTranslatableLocale('en_us');
$evm->addEventSubscriber($translatableListener);
// now this event manager should be passed to entity manager constructor
```

I used it like that in MyRepository every time when i call some query like this:

```
$qb = $this->createQueryBuilder('p')
  ->andWhere('p.status = :status')
  ->setParameters([
      'status' => EnumProductStatus::ACTIVE
  ])
  ->orderBy('p.priority','desc');

$query = $qb->getQuery();

$query->getEntityManager()->getEventManager()->addEventSubscriber(new SluggableListener());
$query->getEntityManager()->getEventManager()->addEventSubscriber(new TreeListener());
$translatableListener = new TranslatableListener();
$translatableListener->setTranslatableLocale($locale);
$query->getEntityManager()->getEventManager()->addEventSubscriber($translatableListener);

return $query->getResult();
```
Its working but i think there shuld be some better way to do this. 

Moreover. in case when i call:
```
$this->translationRepository->translate($product, 'name', $locale, $translatedName);
```
before object manager flush, i cant reache event manager so i am not able to change listeners order anyway.

Please somebody help mw with this. I spend so much time to figure it out.

**Comment by franmomu** [comment]
Hi @mervit, doctrine listeners [do not support priority](https://github.com/doctrine/DoctrineBundle/issues/157), so maybe what you can do is to create a listener that contains the listeners you want in order as suggested in https://github.com/doctrine/DoctrineBundle/issues/157#issuecomment-377229600
