### ISSUE TITLE
Cannot be installed on 5.3.*

### ISSUE THREAD

**Issue by birkof** [doctrine-extensions/DoctrineExtensions#2300]
>Problem 1
    - doctrine/orm is locked to version 2.10.2 and an update of this package was not requested.
    - gedmo/doctrine-extensions v3.2.0 conflicts with gedmo/doctrine-extensions v3.2.0.
    - Root composer.json requires gedmo/doctrine-extensions ^3.2 -> satisfiable by gedmo/doctrine-extensions[v3.2.0].

Anyone have an idea about this conflict?
Doctrine ORM version installed as you see below:

>doctrine/orm                          2.10.2    Object-Relational-Mapper for PHP

**Comment by phansys** [comment]
You are using a version 3.2.0 of this package that does not support `doctrine/orm` >= 2.10:
https://github.com/doctrine-extensions/DoctrineExtensions/blob/8c02cee09e3dd43799ec3b84b619b19982c47f43/composer.json#L59-L64
The next minor release (3.3.0) will include support for `doctrine/orm` >= 2.10.2 (see #2272).

I'm closing this issue.

**Comment by birkof** [comment]
Yeap, you're totally right! Didn't follow the right tag to find this too. 
Thanks!
