### ISSUE TITLE
Deprecation notice Symfony 5.4

### ISSUE THREAD

**Issue by stephanvierkant** [doctrine-extensions/DoctrineExtensions#2362]
As of Symfony 5.4 I get these deprecation notices:
> Method "Doctrine\Common\EventSubscriber::getSubscribedEvents()" might add "array" as a native return type declaration in the future. Do the same in implementation "Gedmo\Uploadable\UploadableListener" now to avoid errors or add an explicit `@return` annotation to suppress this message.

Can we safely add these return types, or should we add a `@return` annotation instead?

**Comment by art-cg** [comment]
I guess it is save to add it as return type. Maybe you can make a PR and let's see what Github Actions tests say.

**Comment by stephanvierkant** [comment]
Technically, change the signature of a public method is a breaking change. And I don't think the test suite tests if a change is a BC-break or not.

Maybe we should mark listeners as final first? Don't think extending them is a good practice after all.

**Comment by franmomu** [comment]
I think this was sorted out in https://github.com/doctrine-extensions/DoctrineExtensions/pull/2355

**Comment by stephanvierkant** [comment]
Symfony doesn't recognize `string[]` is an `array` :(

**Comment by stephanvierkant** [comment]
See https://github.com/symfony/symfony/blob/60ce5a3dfbd90fad60cd39fcb3d7bf7888a48659/src/Symfony/Component/ErrorHandler/DebugClassLoader.php#L565
