### ISSUE TITLE
Support of PHP 8 attributes

### ISSUE THREAD

**Issue by franmomu** [doctrine-extensions/DoctrineExtensions#2363]
This is an issue to keep track the work needed to fully support PHP 8 attributes.

In `3.2.0` we added support to use PHP 8 attributes with Doctrine ORM mapping, in `3.3.0` we added support to use Translatable annotations as attributes and in `3.4.0` we added support to use PHP 8 attributes with Doctrine MongoDB and also added support to use Timestampable and Loggable annotations as attributes.

This is the list of extensions:

- [x] [Blameable](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2375)
- [x] [Loggable](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2357)
- [x] [Sluggable](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2379)
- [x] [Timestampable](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2325)
- [x] [Translatable](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2253)
- [x] [Tree](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2388)
- [x] [IpTraceable](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2377)
- [x] [SoftDeleteable](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2374)
- [x] [Sortable](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2380)
- [x] [Uploadable](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2386)
- [x] [References](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2389)
- [x] [ReferenceIntegrity](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2389)

~We may need to change the `AttributeReader` to support repeatable attributes.~

**Comment by tacman** [comment]
I can work on the Tree extension, I'll submit a PR this afternoon.

**Comment by tacman** [comment]
I think Tree is almost done, but I need some help bringing it across the finish line.  

I can take a look at Slug next unless someone else is already working on it.

**Comment by franmomu** [comment]
> I can take a look at Slug next unless someone else is already working on it.

@tacman have you started with Slug? I think I can try that one.

**Comment by tacman** [comment]
No, I haven't.  Thanks!

**Comment by vstelmakh** [comment]
I prepared the PR for Sortable #2380. Please add it to issue description.

**Comment by franmomu** [comment]
It's done! all extensions can be used with attributes in the next minor version (`3.5.0`).

**Comment by wkup** [comment]
When will the next release take place ? I need the attributes for Tree...

**Comment by maxbethke** [comment]
What would be the easiest way to refactor entities to use attributes instead of annotations?
For doctrine itself I used [rector](https://github.com/rectorphp/rector) with the `DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES`.
Is there a similar ruleset for gedmo/doctrine-extensions?

**Comment by franmomu** [comment]
Apparently there a `DoctrineSetList:: GEDMO_ANNOTATIONS_TO_ATTRIBUTES `: https://github.com/rectorphp/rector-doctrine/blob/9d71cfb2f3ea34cf347b7205c3e8607b8f5b61e9/src/Set/DoctrineSetList.php#L77
