### ISSUE TITLE
Timestampable on="change" field="integerValue" broken in 3.4.0

### ISSUE THREAD

**Issue by holtkamp** [doctrine-extensions/DoctrineExtensions#2367]
I did not have time to try to reproduce it but it seems the following configuration broke when upgrading from `3.3.1` => `3.4.0`:

```xml
<field name="someTimestampPopulatedWhenFieldChangesTo10" type="datetime_immutable" precision="6" column="some_timestamp_populated_when_field_changes_to_10" nullable="true">
    <gedmo:timestampable on="change" field="state" value="10"/>
</field>
```

Note that the "state" field of the involved entity is an integer. 

The column `some_timestamp_populated_when_field_changes_to_10` is not populated anymore when the `state` field changes to 10. 

Maybe this is because the integer `10` does not equal the configured value `"10"` anymore...

Reverting back to `3.3.1` fixed it. 

Will try to pinpoint the cause, but wanted to report early to warn others.

**Comment by franmomu** [comment]
Based on the description looks like it could be something related to https://github.com/doctrine-extensions/DoctrineExtensions/commit/d573d269c8b3eef72553a0011d377c4eb690d682, the only thing I see at first sight is this line:

https://github.com/doctrine-extensions/DoctrineExtensions/commit/d573d269c8b3eef72553a0011d377c4eb690d682#diff-25844f6a0588b21dbad934d2925e310a4977be5595f9db4fcd29ef0dae538ddeR140

can you please try to see if it's that one?

**Comment by holtkamp** [comment]
Thanks @franmomu for the quick follow up, that strict comparison of `in_array()` seems as a potential cause indeed.

Will try to come up with a failing test tomorrow/soon to actually "prove" it.

**Comment by holtkamp** [comment]
Ok, I can confirm that the strict comparison of `in_array()` in line https://github.com/doctrine-extensions/DoctrineExtensions/blob/81458019f09ae999c4509e670f64594c6d8f7e3c/src/AbstractTrackingListener.php#L140 causes the problem with not detecting field changes to a specific integer value when using XML annotations on `3.4.0`.

Disabling the strict comparison causes the change of the field to an integer value like `10` work again.

The root cause seems to be the use of XML as annotations format in which it is not possible to indicate that the 'value' is an integer: 

```XML
<gedmo:timestampable on="change" field="state" value="10"/>
```

Note that removing the double quotes for the value attribute results in an invalid mapping file: 

```XML
<gedmo:timestampable on="change" field="state" value=10/>
```

**Test**
When trying to create a new or adapt an existing test to proof this, I noticed that no XML annotations are used in the tests?

This seems a proper scenario, but XML annotations are required.: 

https://github.com/doctrine-extensions/DoctrineExtensions/blob/81458019f09ae999c4509e670f64594c6d8f7e3c/tests/Gedmo/Timestampable/Fixture/Comment.php#L57
https://github.com/doctrine-extensions/DoctrineExtensions/blob/81458019f09ae999c4509e670f64594c6d8f7e3c/tests/Gedmo/Timestampable/Fixture/Comment.php#L60

**Solution**
A pragmatic / naive / backward compatible solution would be to disable strict comparison (when XML annotations are used) 

A better approach might be to change the XML driver in such a way to detect the integer type of the tracked field and cast the value to integer here: https://github.com/doctrine-extensions/DoctrineExtensions/blob/81458019f09ae999c4509e670f64594c6d8f7e3c/src/Timestampable/Mapping/Driver/Xml.php#L80-L89

**Comment by phansys** [comment]
As I'm not using this extension, this proposal is just theoretical:
```php
$type = Type::getType($meta->getTypeOfField($options['field']));
$configuredValue = $type->convertToPHPValue($options['value'], $om->getConnection()->getDatabasePlatform());

if (null === $options['value'] || ($singleField && in_array($value, (array) $configuredValue, true))) {
```
However, I think we should have a test case covering this behavior.

BTW, if `$options['value']` is intended to hold a scalar value (like in the snippet shown in the first comment), does anyone know why we are checking it as an array?

**Comment by franmomu** [comment]
> BTW, if `$options['value']` is intended to hold a scalar value (like in the snippet shown in the first comment), does anyone know why we are checking it as an array?

Apparently it's not only scalar: https://github.com/doctrine-extensions/DoctrineExtensions/blob/05e0780273389764dc6dcebfcea34bbac84ff6f0/tests/Gedmo/Timestampable/Fixture/TitledArticle.php#L73-L81

If we could solve it in the `AbstractTrackingListener` would be nice, otherwise we need to fix it in every XML driver I guess.

**Comment by phansys** [comment]
@holtkamp, could you please check if #2372 fixes the issue?

**Comment by holtkamp** [comment]
@phansys I can confirm that https://github.com/doctrine-extensions/DoctrineExtensions/pull/2372 resolves this issue. 

Regarding your comment:

>Even if these changes could work, I'll be trying to get this solved from the mapping instead, as I think that will be the proper fix.

Indeed: solving / preventing the problem to occur at the mapping level seems more elegant. When metadata cache is used, it is executed only once. When solving it in the TrackingListener, the functionality is executed many times... And additionally, maybe this problem pops up in other situations as well when the metadata is not configured properly?
