### ISSUE TITLE
Class 'SoftDeleteable' is not annotated with 'Attribute' 

### ISSUE THREAD

**Issue by Lenny4** [doctrine-extensions/DoctrineExtensions#2376]
stof/doctrine-extensions-bundle: v1.7.0

In the [documentation](https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/softdeleteable.md#traits) we can see that we can use `SoftDeleteable` either with annotation or attribute:

```php
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;

/**
 * @ORM\Entity
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, hardDelete=false)
 */
#[ORM\Entity]
#[Gedmo\SoftDeleteable(fieldName: 'deletedAt', timeAware: false, hardDelete: false)]
class UsingTrait
{
```
Yet when I try to use `SoftDeleteable` as attribute, my IDE say:

> Class 'SoftDeleteable' is not annotated with 'Attribute' 

And SoftDeleteable doesn't work, which mean that when I try to delete an entity, it actually delete it from the bdd (when I use it with attribute).

**Comment by franmomu** [comment]
Hi @Lenny4, you are looking at the documentation of the `main` branch, we added support but it is not released yet, you can see it in the changelog:

https://github.com/doctrine-extensions/DoctrineExtensions/blob/4943e2430a5e0182498f7f764751a557242ebea8/CHANGELOG.md#unreleased

I guess we'll tag a new release soon, but there are still some open PR that would be interesting to have them solved.
