### ISSUE TITLE
PHPVersion mismatch 

### ISSUE THREAD

**Issue by Luscope** [doctrine-extensions/DoctrineExtensions#2421]
I currently work on a PHP 7.4 project with DoctrineExtensions and stumbled across some problems. The composer.json tells me it should be possible to use DoctrineExtensions with PHP 7.2 and higher (  "require": { "php": "^7.2 || ^8.0",) ...). It seems the provided container runs on PHP 7.2. But the tests fail because at some places PHP 8 Syntax occures in DoctrineExtensions-Code (PHP 8: Attributes f.ex.). 

This behaviour was detected due to the use of the codeanalyzer PHPStan (2^).

Am I missing something or is this an unknown issue?

**Comment by mbabker** [comment]
Attributes being present in PHP 7 isn't an issue, the syntax was explicitly chosen because it'll be parsed as comments on PHP 7 and earlier.

**Comment by delorie** [comment]
true, the attributes work, nice idea, thanks.

But property types and nullable property work not unter 7.2, or?
When we run PHPStan in the Docker image, we get the following error messages:

```
root@830fa08da20d:/var/www# bin/phpstan
Note: Using configuration file /var/www/phpstan.neon.dist.
 732/732 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
.......
------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   tests/Gedmo/Uploadable/UploadableEntitySizeTypeTest.php                                                                                                                                       
------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
         ParseError (syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST)) thrown while looking for class Gedmo\Tests\Uploadable\Fixture\Entity\ImageWithTypedProperties.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                                                                                            
  16     ParseError (syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST)) thrown while looking for class Gedmo\Tests\Uploadable\Fixture\Entity\ImageWithTypedProperties.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                                                                                            
  27     ParseError (syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST)) thrown while looking for class Gedmo\Tests\Uploadable\Fixture\Entity\ImageWithTypedProperties.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
.....
```

PHPunit runs through because the test is skipped

 https://github.com/doctrine-extensions/DoctrineExtensions/blob/2def628a9a8304c1e7f56847a0b21778a3a9ed61/tests/Gedmo/Uploadable/UploadableEntitySizeTypeTest.php#L23

**Comment by mbabker** [comment]
There are tests covering PHP features used in PHP versions beyond the minimum supported version.  That's a pretty common thing (you'll see it a lot in the Doctrine and Symfony repos).

If you're just trying to lint the entire project at the minimum PHP version (be it with PHP's own linter or a static analysis tool), then odds are you're going to get some errors that will need to be filtered out.
