### ISSUE TITLE
BlameableListener not contemplating getUserIdentifier method availability (still getUsername)

### ISSUE THREAD

**Issue by AlexBevilacqua** [doctrine-extensions/DoctrineExtensions#2424]
I think it would make sense that when the user is an object, the listener should expect / try to use a getUserIdentifier method on it

currently it's not: 

https://github.com/doctrine-extensions/DoctrineExtensions/blob/2def628a9a8304c1e7f56847a0b21778a3a9ed61/src/Blameable/BlameableListener.php#L48-L57

I didn't have a chance at using Blameable myself yet, so I'm not 100% sure if this actually makes sense to you, so, just ignore if I'm wrong...

but, btw, I also noticed Loggable received a similar update, in 396faefb9eef46ebdf56a9b146abae50b66b73f5 

https://github.com/doctrine-extensions/DoctrineExtensions/blob/ca2849656df9f5097a7a92fba2162fdba34c504a/src/Loggable/LoggableListener.php#L76-L87

**Comment by franmomu** [comment]
Hi @AlexBevilacqua, looks like you are right, feel free to create a PR with these changes.
