### ISSUE TITLE
improvement of the documentation

### ISSUE THREAD

**Issue by devozanges** [doctrine-extensions/DoctrineExtensions#2431]
Hello,
it would be great to have this kind of information in priority in the doc because often, we are obliged to go and look in stackoverflow for this kind of information essential to the good functioning of the extension we want to use. 

![image](https://user-images.githubusercontent.com/15364311/157847084-4085dc66-9ec8-4088-80f2-d7ee47ca3069.png)
Thanks for your great work

**Comment by franmomu** [comment]
thanks @devozanges, but that documentation is for the bundle https://github.com/stof/StofDoctrineExtensionsBundle, not this library.

By the way, maybe the bundle could be moved to `doctrine-extensions`? to ease the maintenance if @stof and @AkenRoberts agree 🤔

**Comment by AkenRoberts** [comment]
I've pinged Christophe about that a couple times with no response. Definitely support moving it here if he does.

**Comment by seyfcom** [comment]
The documentation is relly missing parts for non-super-specialist !!

I'm testing translatable and I see nowhere that I need to update doctrine.yaml and without a bunch of lines, nothing is working !

I had to add the last part

`mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            translatable:
                type: annotation
                is_bundle: false
                prefix: Gedmo\Translatable\Entity
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity'
                alias: GedmoTranslatable`

**Comment by franmomu** [comment]
> The documentation is really missing parts for non-super-specialist !!
> 
> I'm testing translatable and I see nowhere that I need to update doctrine.yaml and without a bunch of lines, nothing is working !
> 
> I had to add the last part
> 
> > mappings:
> > App:
> > is_bundle: false
> > dir: '%kernel.project_dir%/src/Entity'
> > prefix: 'App\Entity'
> > alias: App
> > translatable:
> > type: annotation
> > is_bundle: false
> > prefix: Gedmo\Translatable\Entity
> > dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity'
> > alias: GedmoTranslatable
> 
> php 8.1 symf6.1

Yeah any PR to improve the documentation is very welcome! by the way you can find that documentation in https://github.com/doctrine-extensions/DoctrineExtensions/blob/af2f05212300fc275cd7fa59f3040567dbffd72d/doc/symfony4.md#mapping, in this case I guess we should remove the "Symfony 4" part and replace it with "Symfony >= 4.4"

**Comment by seyfcom** [comment]
Anyway thanks to all the people having done those extensions !!

I missed that file ! sorry !
