### ISSUE TITLE
Attempted to call an undefined method named "getCacheDriver" of class "Doctrine\Bundle\DoctrineBundle\Mapping\ClassMetadataFactory". Symfony 5.4.8

### ISSUE THREAD

**Issue by frizquierdo** [doctrine-extensions/DoctrineExtensions#2449]
I have upgraded to symfony 5.4.8 from symfony 5.4.7 and got the error in gedmo/doctrine-extensions

**Comment by kissifrot** [comment]
Looks like it's a duplicate of #2448

**Comment by frizquierdo** [comment]
> Looks like it's a duplicate of #2448

Yeah, when I published
