### ISSUE TITLE
#[Gedmo\Loggable] on parent entity?

### ISSUE THREAD

**Issue by stephanvierkant** [doctrine-extensions/DoctrineExtensions#2463]
I've got something like this:

```
class User extends BaseEntity {}

#[Gedmo\Loggable]
class BaseEntity {}

```

This worked, but on 3.7 I got this error message:

> Uncaught PHP Exception Gedmo\Exception\InvalidMappingException: "Class must be annotated with Loggable annotation in order to track versioned fields in class - App\Entity\User"

I sticked to `"doctrine/persistence": "2.5.3"` to found out if this related to this dependency, but as far as I can see now, the problem started when updating to 3.7 of this library.

My test suite didn't fail on 3.7, but in production I've got this problem. So it might be related to caching. I'll try to create a reproducible example, but please let me know your thoughts.

**Comment by franmomu** [comment]
hmm that seems to be fine, that commit it's the only one modifying things related to cache, I would try to see the difference between the previous version of the commit

**Comment by stephanvierkant** [comment]
The previous version returns this:

```
^ Symfony\Component\Cache\Adapter\PhpArrayAdapter {#337 ▼
  -file: "/home/stephan/PhpstormProjects/qurplus/var/cache/prod/doctrine/orm/default_metadata.php"
  -keys: array:898 [▶]
  -values: array:443 [▶]
  -computing: []
  -pool: Symfony\Component\Cache\Adapter\ArrayAdapter {#338 ▶}
}
```

So far more cache items, including my entities:

```
-values: array:443 [▼
    0 => Closure() {#410 ▶}
    1 => []
    2 => array:3 [▼
      "create" => array:1 [ …1]
      "update" => array:1 [ …1]
      "useObjectClass" => "App\Entity\User\User"
    ]
```

**Comment by stephanvierkant** [comment]
The previous version returns this:

```
^ Symfony\Component\Cache\Adapter\PhpArrayAdapter {#337 ▼
  -file: "{project}/var/cache/prod/doctrine/orm/default_metadata.php"
  -keys: array:898 [▶]
  -values: array:443 [▶]
  -computing: []
  -pool: Symfony\Component\Cache\Adapter\ArrayAdapter {#338 ▶}
}
```

So far more cache items, including my entities:

```
-values: array:443 [▼
    0 => Closure() {#410 ▶}
    1 => []
    2 => array:3 [▼
      "create" => array:1 [ …1]
      "update" => array:1 [ …1]
      "useObjectClass" => "App\Entity\User\User"
    ]
```

**Comment by franmomu** [comment]
😕 so using 3.7 and `doctrine/persistence` 2, can you try to see if these are equal? 

```php
$cacheFromFactory = CacheAdapter::wrap($objectManager->getMetadataFactory()->getCacheDriver());
$cacheFromConf = $objectManager->getConfiguration()->getMetadataCache();
```
I'll try to see if I can reproduce it also somehow

**Comment by stephanvierkant** [comment]
From factory:

```
^ Symfony\Component\Cache\Adapter\ArrayAdapter {#11872 ▼
  -storeSerialized: true
  -values: array:1 [▼
    "App__Entity__User__User__CLASSMETADATA__" => null
  ]
  -tags: []
  -expiries: []
  -defaultLifetime: 0
  -maxLifetime: 0.0
  -maxItems: 0
  #logger: null
}
```

From config:
```

^ Symfony\Component\Cache\Adapter\PhpArrayAdapter {#12282 ▼
  -file: "{projectDir}/var/cache/prod/doctrine/orm/default_metadata.php"
  -computing: []
  -pool: Symfony\Component\Cache\Adapter\ArrayAdapter {#18205 ▼
    -storeSerialized: true
    -values: []
    -tags: []
    -expiries: []
    -defaultLifetime: 0
    -maxLifetime: 0.0
    -maxItems: 0
    #logger: null
  }
}
```

**Comment by stephanvierkant** [comment]
I changed some configuration of my cache pools and now it's working fine.  If someone else has this problem too, please let me know. Otherwise, this was just a case of misconfiguration from my side. Thanks for helping @franmomu !

**Comment by dpfaffenbauer** [comment]
I am having the same problem with DoctrineBundle using the "standard" php array file cache. It is working fine with 3.6 and broken with 3.7. maybe this is related https://github.com/doctrine/orm/issues/8866?

**Comment by franmomu** [comment]
sorry for the late reply @dpfaffenbauer, have you tried to debug the issue? to see where the problem is?

**Comment by dpfaffenbauer** [comment]
@franmomu just a bit, but I didn't spent enough time to actually figure out the Problem. It has to do with the cache....

Mabye this helps? https://github.com/doctrine/orm/issues/8866
