### ISSUE TITLE
[Translatable]How to use the translationWalker

### ISSUE THREAD

**Issue by geoffroyp** [doctrine-extensions/DoctrineExtensions#2464]
Greetings,

First of all, thank you for this very handy tool that is Translatable. This being said, the documentation is a bit unclear to me on some points concerning the translationWalker:

- I see that it must be passed to the query as setHint(). So it implies we have to write the query itself to be able to use it. Therefore, I was thinking about recreating the findBy(), findOneBy() and findAll() methods from repositories in order to set the query hint. For the findAll() it was easy, but the others... anyone here has an example?

- What about serialization? Let's imagine I have an author table and a book table, with their title and description translated. If I want to fetch an author and bring back per author all the books they wrote, by setting a serialization group. I would then get something like that:

```
[
	[
		"name" => "J.R.R Tolkien",
		"books" => [
			0 => [
				"title" => "The lord of the rings",
				"description" => "An old man who spent the night smoking pot forces a kid to travel the world to throw a ring in a volcano",
			],
			1 => [
				"title" => "The two towers",
				"description" => "The old man argue with his even older neighbour and get so pissed, he ends up flooding his garden",
			],
			2 => [
				"title" => "The Return of the King",
				"description" => "The old man gather all his friends for a LARP battle, then brings the kid somewhere far away from his home",
			]
		]
	],
	[
		"name" => "J.K.Rowlings",
		"books" => [
			0 => [
				"title" => "Harry Potter and the Philosopher's Stone",
				"description" => "A young kid from England is invited by an old man in a weird school to master usage of his wand",
			]
		]
	]
]
```

It works, but then I would get 4 differents SQL requests for the books. Is there a way to make the TranslationWalker works with serialization?

- Still about serialization, I have noticed that even if the translatable fields does not belong to the serialization groups we are fetching, we still get multiple SQL queries for translation. So it mean that it doesn't matter which field we are fetching in the Book entity, we always get the translation queries. Is there a way to fix this? It's a waste to query for translation when all we ask is the entity ID...

Thank you!

**Comment by Thibibi** [comment]
Agreed, the TranslationWalker usage should be simplified. Some ideas:

- Set it always on/off with a parameter in the yaml
- Set it on/off alternatively when needed, by functions like:

enableWalker(...)
findAll()
disableWalker(...)
