### ISSUE TITLE
ErrorException  preg_match()

### ISSUE THREAD

**Issue by RajLik** [doctrine-extensions/DoctrineExtensions#2473]
Hi we have a problem with this part of the code:
```
  if (preg_match("@^{$target}{$config['pathSeparator']}@smi", $objectSlug)) {
      $objectSlug = str_replace($target, $slug, $objectSlug);
      $meta->getReflectionProperty($config['slug'])->setValue($object, $objectSlug);
      $ea->setOriginalObjectProperty($uow, $oid, $config['slug'], $objectSlug);
  }
```
We got this error from Sentry. is there any way how to fix it?
`Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated
`

**Comment by phansys** [comment]
Thank you @RajLik.
Do you mind to create a PR adding the required check in order to avoid this error?
