### ISSUE TITLE
Timestampable error if #[Assert\EnableAutoMapping]

### ISSUE THREAD

**Issue by tacman** [doctrine-extensions/DoctrineExtensions#2483]
With automapping on, I'm getting validation errors for anything using the Timestampable trait

```php
#[Assert\EnableAutoMapping]
class MyEntity {
    use Timestampable;
```

![image](https://user-images.githubusercontent.com/619585/176995903-9adab84f-bbcb-4869-99bc-5bcd2e97197a.png)

Both values are indeed set.

It has something to do with PHP8 and requiring that the entity be valid if there are types, including the annotations

```php
    /**
     * @var \DateTime
     */
    protected $createdAt;

    /**
     * @var \DateTime
     */
    protected $updatedAt;
```

I'm not sure what the solution is. It could be
```
    /**
     * @var ?\DateTime
     */
    protected $createdAt=null;

    /**
     * @var ?\DateTime
     */
    protected $updatedAt=null;
```

so that the entity would be valid before it is persisted.

**Comment by franmomu** [comment]
Not sure if we can do something from the package because the extension sets these variables when persisting/updating.

> so that the entity would be valid before it is persisted.

This is the main problem, entities should always be in a valid state, in this case when using `Timestampable` I usually also set those properties in the constructor.
