### ISSUE TITLE
Breaking BC when using with Doctrine Bundle since version 3.7.0

### ISSUE THREAD

**Issue by ossinkine** [doctrine-extensions/DoctrineExtensions#2484]
Since version 3.7.0 this library [uses cache from persisting configuration](https://github.com/doctrine-extensions/DoctrineExtensions/pull/2451) and this is a bug and I will describe below.

Doctrine Bundle [uses PhpArrayAdapter](https://github.com/doctrine/DoctrineBundle/blob/59c101a5e80078648b5f558db9d0dd40fe91e147/DependencyInjection/DoctrineExtension.php#L1010-L1017) by default as metadata cache as the fastest one. This adapter requires cache warming up before using, this is doing by [DoctrineMetadataCacheWarmer](https://github.com/doctrine/DoctrineBundle/blob/59c101a5e80078648b5f558db9d0dd40fe91e147/CacheWarmer/DoctrineMetadataCacheWarmer.php). It set up `ArrayAdapter` to `MetadataFactory` and get metadata for all classes, and then dump all cached metadata to php file. So if this library wants to use the same cache from persisting layer configuration it should fill the same `ArrayAdapter` before but it doesn't, so configuration isn't warmed up and can't be received from cache in the future.

The best way would be to get cache not from configuration but from metadata factory like this
```diff
    private function getCacheItemPool(ObjectManager $objectManager): CacheItemPoolInterface
    {
        if (null !== $this->cacheItemPool) {
            return $this->cacheItemPool;
        }

        if ($objectManager instanceof EntityManagerInterface || $objectManager instanceof DocumentManager) {
-           $metadataCache = $objectManager->getConfiguration()->getMetadataCache();
+           $metadataCache = $objectManager->getMetadataFactory()->getCache();

            if (null !== $metadataCache) {
                $this->cacheItemPool = $metadataCache;

                return $this->cacheItemPool;
            }
        }

        $this->cacheItemPool = new ArrayAdapter();

        return $this->cacheItemPool;
    }
```
but `getCache` method is protected, so I don't how to fix it.

**Comment by franmomu** [comment]
Thanks @ossinkine for reporting, I didn't know that `DoctrineMetadataCacheWarmer` was modifying the cache of `MetadataFactory`, I thought it was only set from the `Configuration` class.

This explains https://github.com/doctrine-extensions/DoctrineExtensions/issues/2463#issuecomment-1137797451.

What we can do is use `\Closure::bind` to access the protected method in the meantime, ideally if the user sets its own `CacheItemPool`, this shouldn't happen.
