### ISSUE TITLE
[Tree] [NestedSet] Sorting by a ManyToOne association in childrenQueryBuilder

### ISSUE THREAD

**Issue by pmishev** [doctrine-extensions/DoctrineExtensions#2486]
While sorting by a ManyToOne association field is perfectly valid, it is currently not allowed.
For example, if you want to sort trees in a forest by their tree root:
```
    #[Gedmo\TreeRoot]
    #[ORM\ManyToOne(fetch: 'EAGER')]
    #[ORM\JoinColumn(name: 'tree_id', referencedColumnName: 'id')]
    private ?Category $root = null;
```
```
    $qb = $repo->childrenQueryBuilder($category, false, 'root');
```
Now you'd get an Exception:
```
Invalid sort options specified: field - root, direction - ASC
```

I've pushed a fix in 926fcb90b374d5f5a7c8e9d305fc2d4ab20b606c as part of https://github.com/doctrine-extensions/DoctrineExtensions/pull/2447 PR

**Comment by franmomu** [comment]
I missed this one, fixed in https://github.com/doctrine-extensions/DoctrineExtensions/pull/2493
