### ISSUE TITLE
SoftDeleteable works through query builder but not ORM relationship functions

### ISSUE THREAD

**Issue by danielrhodeswarp** [doctrine-extensions/DoctrineExtensions#2494]
Hello DoctrineExtensions team,

I am maintaining some code that uses SoftDeleteable.

I have PEOPLE who are SoftDeleteable and who belong to one or more GROUPS:

- PEOPLE <--many-to-many via intermediary table--> GROUPS

Now, when I use Symfony query builder to retrieve entries from the PEOPLE table directly, this is fine and SoftDeleted PEOPLE are excluded.

But when I use the ORM relationship function of the GROUP to get the associated PEOPLE:

- $associatedPeople = $someGroupEntity->getPeople();

This does not work and it returns all PEOPLE for that group - even if they are SoftDeleted.

Is this expected behaviour? Or is this a bug or usage quirk?

**Comment by franmomu** [comment]
Hi @danielrhodeswarp, thanks for reporting, I would say that's a bug, apparently there are no tests covering that case, it would be nice to add them, but I don't know how hard would be to solve this issue, feel free to send a PR.

**Comment by JarJak** [comment]
@danielrhodeswarp is $associatedPeople a collection of proxies or real soft-deleted entities?

**Comment by danielrhodeswarp** [comment]
@JarJak This is where I admit that I don't really know what proxies are in Doctrine (I'm coming back to Doctrine after many, many years of using other ORMs).

I'm not sure how I can find out the answer to your question, but I appreciate that it gives me something to investigate - thanks.

**Comment by JarJak** [comment]
@danielrhodeswarp if you dump $associatedPeople you will see if it contains objects the entity class or something with `Proxy` in namespace

**Comment by danielrhodeswarp** [comment]
OK @JarJak so $associatedPeople comes out as a `Doctrine\ORM\PersistentCollection` with 24 `App\Entity\SupportStaff` elements in it. And one of those elements is already a soft-deleted SupportStaff entry.

It's quite a mystery for me, I can work around this issue, but it's very annoying! (And does feel like a bug - unless I'm missing something obvious...)

**Comment by JarJak** [comment]
@danielrhodeswarp then it looks like a bug. Could you share your filter configuration for this entity?

**Comment by danielrhodeswarp** [comment]
Thanks @JarJak  your comment about filter config intrigued me. Here is the answer to all of the riddles:

- I've got `enabled: true` commented out in the filter config in doctrine.yaml!

Setting `enabled: true` fixes my issue. Thanks for your help and I now feel very embarrassed.

Good to know this isn't a bug in SoftDeleteable, though I need to have serious words with the previous developer!
