### ISSUE TITLE
[SoftDeletable] Softdeletable entity on relation

### ISSUE THREAD

**Issue by JoDarma-lp** [doctrine-extensions/DoctrineExtensions#2506]
I am facing the same issue mentioned in this post [#1427](https://github.com/doctrine-extensions/DoctrineExtensions/issues/1427), I am using Symfony 6.1 and API-PLATFORM.
After several unsuccessful attempts I come back here to find out if there has been anything new in the implementation of DoctrineExtension to solve this problem? (@AkenRoberts 👀 )

@patrickdamery I would like to use your solution but I don't want to create custom controller (because in this case I have to make custom controller for all GET routes of all my entity) and I want to use custom annotation directly on entity (but it doesn't work) did you find a way to make it work on the entity?

**Comment by patrickdamery** [comment]
Hey @JoDarma-lp, in the end I didn't have to make it work on entities so I just used it on the controller's methods since this was enough for my requirements. I'm also no longer working with Symfony or PHP so I can't be of much help, but looking back on the code, if I take a stab in the dark, I think I'm missing a `handlePropertyAnnotation` in `/src/EventListener/IgnoreFilterListener.php`.

If you can find code for other annotations that work on entities you can use that as an example of how to do it.

If it helps, [this](http://www.inanzzz.com/index.php/post/ey9k/creating-a-custom-annotation-for-controller-class-and-method-in-symfony) is the article I used to write the custom annotation in the first place.

**Comment by semnickolas** [comment]
Hi @JoDarma-lp, try something like this:

1. Create custom doctrine annotation 
`use Doctrine\ORM\Mapping\Annotation;

/**
 * @Annotation
 * @Target("PROPERTY")
 */
final class IgnoreFilter implements Annotation
{
    private const FILTER_INDEX = 'filter';

    /**
     * @Required
     */
    public string $filter;

    /**
     * @param array<string, string> $filter
     */
    public function __construct(array $filter)
    {
        $this->filter = $filter[self::FILTER_INDEX];
    }
}`

2. Create custom doctrine metadata event listener. For example
`use App\Annotation\Doctrine\IgnoreFilter;
use Doctrine\Common\Annotations\Reader;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Event\LoadClassMetadataEventArgs;
use Doctrine\ORM\Mapping\Entity;

class IgnoreFilterListener
{
    /**
     * @param array<string, string[]> $supportedClassesMap
     */
    public function __construct(
        private Reader $annotationReader,
        private EntityManagerInterface $entityManager,
        private array $supportedClassesMap,
    ) {
    }

    public function loadClassMetadata(LoadClassMetadataEventArgs $eventArgs): void
    {
        $classMetadata = $eventArgs->getClassMetadata();
        $reflectionClass = $classMetadata->getReflectionClass();
        if (\array_key_exists($reflectionClass->getName(), $this->supportedClassesMap)) {
            $this->handleFilterAnnotation($reflectionClass);
        }
    }

    /**
     * @param \ReflectionClass<Entity> $reflectionClass
     */
    private function handleFilterAnnotation(\ReflectionClass $reflectionClass): void
    {
        foreach ($this->supportedClassesMap[$reflectionClass->getName()] as $allowedProperty) {
            try {
                $property = $reflectionClass->getProperty($allowedProperty);
                $annotation = $this->annotationReader->getPropertyAnnotation($property, IgnoreFilter::class);
                $this->entityManager->getFilters()->disable($annotation->filter);
            } catch (\Throwable) {
                continue;
            }
        }
    }
}`

3. Add custom annotation for necessary property
`class SomeEntity
{
    /**
     * @ORM\ManyToOne(targetEntity=RelationEntity::class)
     * @IgnoreFilter(filter="softdeleteable") //our custom annotation
     */
    private RelationEntity $relation;

}`

4. Add config for your custom listener
`    App\EventListener\Doctrine\IgnoreFilterListener:
        arguments:
            $supportedClassesMap: {
                App\Entity\SomeEntity: ['relation']
            }
        tags:
            - { name: 'doctrine.event_listener', event: 'loadClassMetadata' }`

It works for me. Good luck!

**Comment by semnickolas** [comment]
Hi @JoDarma-lp, try something like this:

1. Create custom doctrine annotation 

```php
namespace App\Annotation\Doctrine;

use Doctrine\ORM\Mapping\Annotation;

/**
 * @Annotation
 * @Target("PROPERTY")
 */
final class IgnoreFilter implements Annotation
{
    private const FILTER_INDEX = 'filter';

    /**
     * @Required
     */
    public string $filter;

    /**
     * @param array<string, string> $filter
     */
    public function __construct(array $filter)
    {
        $this->filter = $filter[self::FILTER_INDEX];
    }
}

```

3. Create custom doctrine metadata event listener. For example

```php
use App\Annotation\Doctrine\IgnoreFilter;
use Doctrine\Common\Annotations\Reader;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Event\LoadClassMetadataEventArgs;
use Doctrine\ORM\Mapping\Entity;

class IgnoreFilterListener
{
    /**
     * @param array<string, string[]> $supportedClassesMap
     */
    public function __construct(
        private Reader $annotationReader,
        private EntityManagerInterface $entityManager,
        private array $supportedClassesMap,
    ) {
    }

    public function loadClassMetadata(LoadClassMetadataEventArgs $eventArgs): void
    {
        $classMetadata = $eventArgs->getClassMetadata();
        $reflectionClass = $classMetadata->getReflectionClass();
        if (\array_key_exists($reflectionClass->getName(), $this->supportedClassesMap)) {
            $this->handleFilterAnnotation($reflectionClass);
        }
    }

    /**
     * @param \ReflectionClass<Entity> $reflectionClass
     */
    private function handleFilterAnnotation(\ReflectionClass $reflectionClass): void
    {
        foreach ($this->supportedClassesMap[$reflectionClass->getName()] as $allowedProperty) {
            try {
                $property = $reflectionClass->getProperty($allowedProperty);
                $annotation = $this->annotationReader->getPropertyAnnotation($property, IgnoreFilter::class);
                $this->entityManager->getFilters()->disable($annotation->filter);
            } catch (\Throwable) {
                continue;
            }
        }
    }
}
```

4. Add custom annotation for necessary property

```php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Annotation\Doctrine\IgnoreFilter;

class SomeEntity
{
    /**
     * @ORM\ManyToOne(targetEntity=RelationEntity::class)
     * @IgnoreFilter(filter="softdeleteable") //our custom annotation
     */
    private RelationEntity $relation;

}
```

5. Add config for your custom listener

```yaml
    App\EventListener\Doctrine\IgnoreFilterListener:
        arguments:
            $supportedClassesMap: {
                App\Entity\SomeEntity: ['relation']
            }
        tags:
            - { name: 'doctrine.event_listener', event: 'loadClassMetadata' }
```

It works for me. Good luck!

**Comment by vince83110** [comment]
I don't understand your code, I don't think you use correctly your annotation and having to configure all your entities in service.yaml and then in the entity itself is anti-pattern.

In any case, this behavior is really a must have, and since it doesn't have, it makes this package a little useless.
