### ISSUE TITLE
[Tree] [NestedSet] - childrenHierarchy - Invalid sort options specified

### ISSUE THREAD

**Issue by peter38340** [doctrine-extensions/DoctrineExtensions#2508]
Since the following modification https://github.com/doctrine-extensions/DoctrineExtensions/commit/60c453e27370c645c84d664af120c8d679d1773d , I do no more succeed to retrieve the whole tree as described at  https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/tree.md :
$repo = $em->getRepository(Category::class);
$arrayTree = $repo->childrenHierarchy();

The error message is "Invalid sort options specified"

**Comment by Pepino483** [comment]
I have the same problem.

Invalid sort options specified: field - root, direction - asc

**Comment by hgabka** [comment]
Same here. The problem is that if root is configured, NestedTreeRpository::getNodesHierarchyQueryBuilder adds 'root' as sort field (line 893 in src/Tree/Repository/NestedTreeRepository.php), but it is not in doctrine metadata fields, as this is an association mapping.  So $meta->hasField is false that causes an exception in NestedTreeRpository::childrenQueryBuilder (line 256)

**Comment by imajim** [comment]
version 3.8 crash my category tree. Return to version 3.7 working great.

@hgabka  your temporary fix not working for me. All categories are mixed.

**Comment by hgabka** [comment]
@imajim As I wrote, this only works if the tree is single rooted. However, you can alter the childrenQueryBuilder to add the sorting by root id

**Comment by Lreus** [comment]
Hello, 
I faced the same issue.
I tried to upgrade to gedmo/doctrine-extensions 3.10 but a new error about TreeListener was raised

> Gedmo\Exception\InvalidMappingException: Tree listener was not found on your entity manager, it must be hooked into the event manager

I fixed my version to 3.7 and will keep an eye for any news about it.

**Comment by stereo-type** [comment]
Any solutions?
