### ISSUE TITLE
[Loggable] Monolog injection in custom LoggableListener

### ISSUE THREAD

**Issue by brusin** [doctrine-extensions/DoctrineExtensions#2529]
Hi guys,

I'm trying to implement a custom LoggableListener to log every change in a specific monolog channel instead of persisting it in our database.

So far the custom listener is doing it's job but I can't get monolog injected/autowired in my listener. I keep getting the following error :

```
CRITICAL  [php] Uncaught Error: Too few arguments to function App\EventListener\CustomLoggableListener::__construct(), 0 passed in /var/www/symfony/var/cache/dev/ContainerYnHe4Yu/App_KernelDevDebugContainer.php on line 2859 and exactly 1 expected ["exception" => ArgumentCountError { …}]

In CustomLoggableListener.php line 14:

  Too few arguments to function App\EventListener\CustomLoggableListener::__construct(), 0 passed in /var/www/symfony/var/cache/dev/ContainerYnHe4Yu/App_KernelDevDebugContaine
  r.php on line 2859 and exactly 1 expected


cache:clear [--no-warmup] [--no-optional-warmers]
```

My `CustomLoggableListener` extends `LoggableListener`, which extends `MappedEventSubscriber`, which has the following constructor signature

```
public function __construct()
{
    $parts = explode('\\', $this->getNamespace());
    $this->name = end($parts);
}
```

Here is some code :

**config/packages/dev/monolog.yaml** 
```
monolog:
    channels: [..., 'loggable']
    handlers:
        main:
            ...
        loggable:
            type: rotating_file
            path: "%kernel.logs_dir%/loggable.log"
            level: debug
            channels: ["loggable"]
```

**config/services.yaml**
```
App\EventListener\CustomLoggableListener:
        arguments: ['@monolog.logger.loggable']
```

**src/EventListener/CustomLoggableListener.php**
```
namespace App\EventListener;

use Gedmo\Loggable\LoggableListener;
use Gedmo\Loggable\Mapping\Event\LoggableAdapter;
use Gedmo\Tool\Wrapper\AbstractWrapper;
use Psr\Log\LoggerInterface;

class CustomLoggableListener extends LoggableListener
{
    private $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
        parent::__construct();
    }

    protected function createLogEntry($action, $object, LoggableAdapter $ea)
    {
        // Magic code of my own 

        $this->logger->info('Some logs')
    }
}
```

Any idea on how to workaround this issue please ? Any type of injection in my Listener leads to the same error (EntityManagerInterface, TranslatorInterface..).

Thanks a lot !

**Comment by franmomu** [comment]
Hi @brusin, it depends on what you want to achieve, based on the code you showed, I would say there is no need to extend from `LoggableListener` and you could achieve what you want with a simple subscriber like https://symfony.com/doc/current/doctrine/events.html#doctrine-lifecycle-subscribers

**Comment by brusin** [comment]
Hi @franmomu, 

Event subscribers won't do the job in my case since my goal is to log every change on a monolog channel without persisting `LogEntry` in our database ?

Basically, I want Loggable to do it's job and prevent entity persisting to do some code of my own instead.

**Comment by franmomu** [comment]
in that case you should [use service decoration](https://symfony.com/doc/current/service_container/service_decoration.html) instead of extending `LoggableListener`.

Anyway, for the error you are receiving, looks like it's about `LoggerInterface $logger` in your `CustomLoggableListener` constructor, so it doesn't seem to be becaused of `LoggableListener`.

**Comment by brusin** [comment]
Thanks, I'll be looking into this implementation !

**Comment by bdaler** [comment]
@brusin Did you try to use tags in your `services.yaml` instead `arguments`? Something like:
```
App\EventListener\CustomLoggableListener:
        tags:
          - { name: monolog.logger, channel: loggable}
```

**Comment by brusin** [comment]
Yep, (sadly) getting the exact same error.
