### ISSUE TITLE
[Tree][NestedSet] Is possible to `recover` without `verify`?

### ISSUE THREAD

**Issue by ZZromanZZ** [doctrine-extensions/DoctrineExtensions#2555]
Hi, I have very large nested set tree (~ 10 thousand of nodes with depth around 10). I ocassionaly need to recover whole tree, but this operation is very resource demanding. After some inspecitions, it looks like there is verification before actual tree recovering, verification looks more demanding then actual recover. Is there any possiblity to run recover directly without verification ? Does the recover even need to run verificiation, when I just want to force recover anyway and woul'd this speed up the process?

**Comment by damianz5** [comment]
https://github.com/doctrine-extensions/DoctrineExtensions/blob/94ef07aebf78db38cbff80f39f3e87006c19bc9d/src/Tree/Entity/Repository/NestedTreeRepository.php#L1063

```
        $repository->recover([
            'treeRootNode' => $treeRootElement, 
            'skipVerify' => true, 
            'flush' => true,
            // ...
        ]);
```

**Comment by ZZromanZZ** [comment]
Thank you, works
