### ISSUE TITLE
[SoftDeleteable] Deprecated `LifecycleEventArgs`

### ISSUE THREAD

**Issue by misaert** [doctrine-extensions/DoctrineExtensions#2560]
Hi,

It seems `doctrine/orm` with version `2.14` deprecates the use of the class `Doctrine\ORM\Event\LifecycleEventArgs`. It will be removed in ORM `3.0`. (see [changelog](https://github.com/doctrine/orm/blob/2.14.x/UPGRADE.md#deprecated-doctrineormeventlifecycleeventargs-class))

I think it will affect the `SoftDeleteable` behavior. Right?

Thanks,

Mickaël

**Comment by misaert** [comment]
Hi,

Is it affect `SoftDeleteable` behavior?

Thank you,

Mickaël

**Comment by misaert** [comment]
Up.

**Comment by misaert** [comment]
Up again 😄

**Comment by mbabker** [comment]
This was fixed with 3.15.  There's a B/C layer for event listeners with a typehint to the deprecated ORM event class, otherwise, the `Gedmo\SoftDeleteable\Event\PreSoftDeleteEventArgs` and `Gedmo\SoftDeleteable\Event\PostSoftDeleteEventArgs` classes should be used in listeners going forward.

**Comment by misaert** [comment]
Oh right :+1: 

Related links:
- https://github.com/doctrine-extensions/DoctrineExtensions/issues/2648
- https://github.com/doctrine-extensions/DoctrineExtensions/pull/2649
- https://github.com/doctrine-extensions/DoctrineExtensions/releases/tag/v3.15.0
