### ISSUE TITLE
[Sortable] SortableRepository is final

### ISSUE THREAD

**Issue by aleho** [doctrine-extensions/DoctrineExtensions#2573]
With the latest release the repository for sortables is marked final.

The docs state:
> You should register SortableRepository (**or a subclass**) …

How is the SortableRepository supposed to be used now after classes are final?

It this an oversight and we can still extend from SortableRepository and ignore the final annotation?
Should we handle our own repo's constructor like a decorator?

**Comment by mbabker** [comment]
IMO repository classes shouldn't have the `@final` annotation.  By convention with Doctrine, these should be open for extension (especially as an entity in the ORM can only have one repository class).

**Comment by CreativeNative** [comment]
This also applies to @final class Gedmo\Translatable\Entity\Repository\TranslationRepository. I would be interested to know how to handle this.

**Comment by develth** [comment]
IMHO also the Listeners like BlameableListener to set something different as `user` value.
This close API commit makes this extension sadly less flexible and extendable, what i loved previously
