### ISSUE TITLE
document how to setTranslatableLocale

### ISSUE THREAD

**Issue by tacman** [doctrine-extensions/DoctrineExtensions#2577]
The Basic Usage section starts off

>> Currently a global locale used for translations is "en_us" which was set in TranslationListener globally. To save article with its translations:

Unfortunately, there's no documentation or examples of what a TranslationListener class would look like.  I'm stuck trying to inject the listener, which isn't found.  So I'm probably not registering it, I would expect to see something in services that registers the listener, but the only documentation I can find is https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/annotations.md#em-setup, .

I can see from ->findTranslations() that my translations are being stored in the database, but I can't figure out how to set the translation locale.

Thanks.

**Comment by specdrum-agc** [comment]
If you use Symfony, you probably want to look at https://github.com/stof/StofDoctrineExtensionsBundle. It integrates DoctrineExtensions into Symfony projects.
