### ISSUE TITLE
Timestampable Type Carbon

### ISSUE THREAD

**Issue by jrean** [doctrine-extensions/DoctrineExtensions#2631]
Would it be possible to have the option/configuration to set "timestampable" fields using Carbon instead of a DateTime/DateTimeImutable types?
https://github.com/doctrine-extensions/DoctrineExtensions/blob/v3.2.0/src/Timestampable/Mapping/Event/Adapter/ORM.php#L26-L31

So for instance while working on unit tests and using `Carbon::setTestNow(now()->subDays(2));` automatically the `createdAt` and `updatedAt` attribute will be of the new "now" value since end-to-end it would use Carbon.

**Comment by phansys** [comment]
Hi @jrean!
IMO, any improvement like this could be provided as an extension point, as long it respect the current contract. If you think this is possible with "Carbon" (and other) objects, please feel free to create a PR with your proposal.

**Comment by phansys** [comment]
See
https://github.com/doctrine-extensions/DoctrineExtensions/blob/a2364710d2f367f74d9f041c3356f2929b8c6690/tests/Gedmo/SoftDeleteable/CarbonTest.php#L23
https://github.com/doctrine-extensions/DoctrineExtensions/blob/a2364710d2f367f74d9f041c3356f2929b8c6690/tests/Gedmo/Timestampable/CarbonTest.php#L28
