### ISSUE TITLE
RFC: Drop support of php < 7.4?

### ISSUE THREAD

**Issue by Chris53897** [doctrine-extensions/DoctrineExtensions#2635]
I like to suggest to drop support of php < 7.4
The [Usage](https://packagist.org/packages/gedmo/doctrine-extensions/php-stats#3) is under 3%

Im in favour to drop support for 7.4 as well and only use attributes.
But i guess this is to fast for most users.

**Comment by franmomu** [comment]
https://github.com/doctrine-extensions/DoctrineExtensions/pull/2636 was merged
