### ISSUE TITLE
Doctrine deprecations

### ISSUE THREAD

**Issue by DubbleClick** [doctrine-extensions/DoctrineExtensions#2638]
https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/Mapping/Event/Adapter/ORM.php#L98

This calls LifeCycleEventArgs->getEntityManager() which has been deprecated for getObjectManager() instead. Likewise, calls to getEntity() have been deprecated for getObject() as well.

**Comment by phansys** [comment]
Thank you @DubbleClick.
Do you plan to create a PR for these deprecation?

**Comment by franmomu** [comment]
Fixed in https://github.com/doctrine-extensions/DoctrineExtensions/pull/2639
