### ISSUE TITLE
EventArgs::getEntityManager is replaced by getObjectManager in Doctrine parent classes

### ISSUE THREAD

**Issue by DubbleClick** [doctrine-extensions/DoctrineExtensions#2640]
https://github.com/doctrine/orm/issues/9875 deprecates retrieving entity managers and instead only allows retrieving object managers with no promise that they are entity managers.

UploadableBaseEventArgs should follow suit and at least add a getObjectManager() method to be in-line with the orm changes.

**Comment by franmomu** [comment]
Fixed in https://github.com/doctrine-extensions/DoctrineExtensions/pull/2639
