### ISSUE TITLE
Possible bug (and fix) found in `SortableRepository.php`

### ISSUE THREAD

**Issue by groovenectar** [doctrine-extensions/DoctrineExtensions#2643]
It's in the `main` branch and also latest tag `v3.11.1`

Here: https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/Sortable/Entity/Repository/SortableRepository.php#L64

```php
$this->config = $this->listener->getConfiguration($this->_em, $this->meta->getName());
```
I was getting an error `$this->_em` is undefined.

`Warning: Undefined property: Gedmo\Sortable\Entity\Repository\SortableRepository::$_em in vendor/gedmo/doctrine-extensions/src/Sortable/Entity/Repository/SortableRepository.php on line 64`

`$em` is actually provided as a dependency in the method arguments: https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/Sortable/Entity/Repository/SortableRepository.php#L44

`public function __construct(EntityManagerInterface $em, ClassMetadata $class)`

And `$this->_em` isn't defined or used in the class...

When I change the last line of the method to:

```php
$this->config = $this->listener->getConfiguration($em, $this->meta->getName());
```

I no longer get the error...

Is that a proper fix, or am I doing something else wrong in the first place to have gotten the error?

**Comment by mbabker** [comment]
`$this->_em` should be set in the [parent constructor call](https://github.com/doctrine/orm/blob/2.15.x/lib/Doctrine/ORM/EntityRepository.php#L69-L74).  What ORM version are you working with?

That said, just using the entity manager from the constructor argument instead of reaching out elsewhere seems like it would be fine, but the fact you're getting this error to me implies there might be something else wrong in your application or the vendor files are changed in an unexpected way.

**Comment by groovenectar** [comment]
Thanks, I think it may have been a version issue indeed. As I'm diving into Doctrine, the goals for ORM version 3 seem a bit unclear, yet DBAL has gotten to v3. Also this repository is at version 3. I assume that's unrelated, but sometimes an extension will follow the major versions of the base project.

At first I wanted to use ORM 3, which worked well for a basic setup but for now I've reverted back to the standard current versions. In v3 of ORM it looks like the constructor var is `$em`: https://github.com/doctrine/orm/blob/3.0.x/lib/Doctrine/ORM/EntityRepository.php#L43

Which also matches the constructor of version 3 of `SortableRepository.php` in this repository. It's resolved as a version issue, still a bit confusing though...

**Comment by mbabker** [comment]
This package right now only supports the stable ORM 2.x branch, it's not compatible with the in-dev 3.0 branch.  Maybe the Composer conflict statements can be adjusted to block installing alongside newer major releases than the ones officially supported (as right now they only enforce a minimum, no maximum, compared to the constraints in `require` and `require-dev` which through Composer's semver library enforce maximum versions).

That said, the ORM's 2.x branch now documents `Doctrine\ORM\EntityRepository::$_em` as internal (alongside some other protected properties) and suggests using the getter instead (which will also be needed for 3.0 compatibility), so a pull request updating `EntityRepository` subclasses (like this one) to avoid using the properties that will be renamed and made private in 3.0 would definitely be welcome.
