### ISSUE TITLE
Updating Documentation for EventManager Error

### ISSUE THREAD

**Issue by colinpade** [doctrine-extensions/DoctrineExtensions#2654]
Hello All,

Recently I tried adding the `soft-deleteable` extension to our codebase and kept getting this error:
`Listener "SoftDeleteableListener" was not added to the EventManager!`

I don't see any mention of adding the it to the EventManager on the README located here:
https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/softdeleteable.md

I tried making a PR, but got request denied to update the docs. While not the best formatting, I wanted to add something along these lines to the file. This would've saved me a lot of time searching around if I had known this also needs to be added for it to be functional.

#### Answer: This happens when we forget to also add the extension to the Event Manager. To do that in the configuration remember to include a line like:
````php
$em->getEventManager()->addEventSubscriber(new SoftDeleteableListener());
````

Curious for your thoughts or if I can get perms to PR the README.

**Comment by Chris53897** [comment]
You can create a Fork and make a PR.
