### ISSUE TITLE
Determine what to do with the BC layer for `doctrine/common` 2.2 at `ExtensionMetadataFactory::getDriver()`

### ISSUE THREAD

**Issue by phansys** [doctrine-extensions/DoctrineExtensions#2677]
We need to confirm what is the purpose for the BC layer provided at `ExtensionMetadataFactory::getDriver()`, as it is not clear if this is intended to provide compatibility for `doctrine/common` >= 2.2.0 or `doctrine/common` < 2.2.0.

https://github.com/doctrine-extensions/DoctrineExtensions/blob/7493440008419ab1740e4263de6162abfe3b8753/src/Mapping/ExtensionMetadataFactory.php#L206

It seems confusing to me, as the commit where the change was introduced is also updating the constraint to `"doctrine/common": ">=2.2,<2.4-dev"`. See 9e58bb76e7931f2eae909021a9549601c7a7e186.

**Comment by stof** [comment]
Actually, this comment was already there before that commit. See the deleted lines (it appears as added and deleted because its indentation has changed)

**Comment by stof** [comment]
the comment was added in https://github.com/doctrine-extensions/DoctrineExtensions/commit/01ca83002414a8e585108b79632881d7ce21cb36

In doctrine/common 2.3+, the driver is an instance of MappingDriver
