### ISSUE TITLE
Clock Mocking doesn't work from v3.12.0

### ISSUE THREAD

**Issue by rasstislav** [doctrine-extensions/DoctrineExtensions#2700]
Hello,

[this commit](https://github.com/doctrine-extensions/DoctrineExtensions/commit/2ed66e372073369418e4c8457725b5d7cc54b30c) broke [Clock mocking](https://symfony.com/doc/current/components/phpunit_bridge.html#clock-mocking).

Is it possible to fix it?

Thanks

**Comment by stof** [comment]
The future-proof way would be to support injecting a PSR-20 clock in the listener and using it to get the current time.

**Comment by Chris53897** [comment]
@rasstislav Can this be closed as completed (see linked PR)?

**Comment by rasstislav** [comment]
@Chris53897 my tests are still not working due to DateTime as @boedah also mentioned.

**Comment by rasstislav** [comment]
@boedah, can you please test it as well?

**Comment by mbabker** [comment]
> @Chris53897 my tests are still not working due to DateTime as @boedah also mentioned.

What tests specifically?  Without a specific use case, it's hard to know what it is that's causing your issue.  The last release supports injecting a PSR-20 where practical, with the only places using still using `new \DateTime()` being an ODM query filter where injecting a clock isn't really feasible (or if it is I guess that'd be through the parameters API, but not being an ODM user I couldn't tell you if that's good or bad), and the `setLoggedAt()` methods on the base log entry document/entity classes that it's recommended to extend from for that integration, and you can work around that with implementing your own log entry object and overloading those methods to use some other time source if need be.

**Comment by phansys** [comment]
Closing as #2760 implemented a solution for this.
Thanks!
