### ISSUE TITLE
Conflict incompatible version 2.16.2 of doctrine/orm

### ISSUE THREAD

**Issue by Chris-Basson-Grundling** [doctrine-extensions/DoctrineExtensions#2707]
Unfortunately still having the same issue with doctrine/orm 2.16.2, which includes https://github.com/doctrine/orm/pull/10915

**Comment by mbabker** [comment]
What issue specifically are you referring to?

What version of this package + the Doctrine packages do you have installed?

What database backend are you using?  The conversation in #2659 points to there being an issue with some functionality on PostgreSQL databases.  But, this package's test suite (using SQLite) and the features I'm using in a MySQL-backed app are working fine.
