### ISSUE TITLE
Add ascii_string to allowed type for @Gedmo\Blameable

### ISSUE THREAD

**Issue by Nirator78** [doctrine-extensions/DoctrineExtensions#2726]
### Summary

I'm encountering an error when attempting to use the ascii_string type in the @Gedmo\Blameable annotation. Currently, the error message is as follows:
```
bash

Field - [createdBy] type is not valid and must be 'string' or a one-to-many relation in class - App\Entity\MyClass
```
### Description

The error occurs in Annotation.php at line 63, indicating that the ascii_string type is not recognized as valid for the createdBy field in the @Gedmo\Blameable annotation. As a solution, I propose adding support for the ascii_string type in this context.

### Benefits

Error Resolution: This addition will address the error currently encountered when using ascii_string, allowing for seamless integration within the @Gedmo\Blameable annotation.

### Additional Information

I want to add ascii_string because i'm using a Microsoft SQL Server database and the ascii_string allow me to create char column.

Thank you for your consideration.

Sincerely,

**Comment by Nirator78** [comment]
Pull request
https://github.com/doctrine-extensions/DoctrineExtensions/pull/2802

**Comment by franmomu** [comment]
closing here as the https://github.com/doctrine-extensions/DoctrineExtensions/pull/2802 was merged
