### ISSUE TITLE
Can't escape quote in orderby with the function INSTR()

### ISSUE THREAD

**Issue by aleblanc** [doctrine-extensions/DoctrineExtensions#2799]
When I add a quote in the function INSTR() like this : 

```php

$value = " string with quote ' that make error ";
$queryBuilder->orderBy('INSTR(field, '.$this->getEntityManager()->getConnection()->quote($value).')');
```

This code generate this error : 

<pre>
"[Syntax Error] line 0, col 131: Error: Expected Doctrine\\ORM\\Query\\Lexer::T_CLOSE_PARENTHESIS, got 'that'"
</pre>

NB: If I remove the quote in the string the query works.

Environnement : 
<pre>
            "name": "gedmo/doctrine-extensions",
            "version": "v3.15.0",

            "name": "doctrine/orm",
            "version": "2.19.5",
</pre>

**Comment by mbabker** [comment]
This doesn't look to be a bug related to this package's functionality?  Seems better reported to https://github.com/doctrine/orm
