### ISSUE TITLE
[Repo] Codecov not uploading on push to `main`

### ISSUE THREAD

**Issue by mbabker** [doctrine-extensions/DoctrineExtensions#2852]
See https://github.com/doctrine-extensions/DoctrineExtensions/actions/runs/10436110807/job/28900763611

This would explain why all the coverage reports and diffs are based on a 6-month-old commit.

**Comment by phansys** [comment]
Thanks for the finding @mbabker!

I don't know if the secret `CODECOV_TOKEN` is configured in the repository as I haven't the required permission to see the settings, but at least I can confirm the token was not configured in the action. So let's wait for the next merge to the `main` branch to see if this issue is fixed.

**Comment by phansys** [comment]
I can confirm that it still doesn't work after adding the `token` input.
https://github.com/doctrine-extensions/DoctrineExtensions/blob/ee91783fd0277a1d00f6f5d10c0e6723296d1fe3/.github/workflows/continuous-integration.yml#L142-L146

@AkenRoberts, do you have a chance to confirm if there is a configured secret for the [Codecov token](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions)?

**Comment by AkenRoberts** [comment]
@phansys Thanks for being patient. There is no token configured in the settings as their documentation suggests.

Happy to add one, though. DM it to me?

**Comment by AkenRoberts** [comment]
Never mind, I was able to get one by logging into my account. Not sure how those are shared, but I added it to the repo's secrets settings.

**Comment by AkenRoberts** [comment]
Seems to be working now. I [reran CI here](https://github.com/doctrine-extensions/DoctrineExtensions/actions/runs/11226450637/job/31582862259) and see a positive result on Codecov.

Ping me again if things are still weird. Sorry again for the delay. Feel free to get spammy if something important is happening and you need my attention!

**Comment by phansys** [comment]
Thank you so much!
