### ISSUE TITLE
[Timestampable] Allow setting clock manually for bulk imports/fixtures

### ISSUE THREAD

**Issue by Leobaillard** [doctrine-extensions/DoctrineExtensions#2868]
## Feature Request

Hi, I am trying to create a Symfony command to bulk load records from a CSV file (for loading fixtures or loading backups for instance). The records map to an entity that is timestampable.

The issue I'm encountering is that is does not currently seem possible to set a custom Clock object (MockClock for instance) before each entity is persisted. The clock can be set when registering the listener but that does not solve my issue as I need to set the clock for each object that will be inserted as date and times are already defined.

I'm also using IpTraceable on these objects and I was able to use the same logic to manually set the IP address before each object is persisted.

As far as I understand, `TimestampableListener` extends the `AbstractTrackingListener` class which then calls the `getEventAdapter()` method of its parent class `MappedEventSubscriber`. The issue is that the adapters (for ORM or ODM) are loaded once into an array of this object and the clock is passed at that time but all subsequent calls refer to the same clock object, which prevents changing the clock object/value on each run.

See: https://github.com/doctrine-extensions/DoctrineExtensions/blob/ade7387e47c635cf8b66a14d26fed1ca451fcabd/src/Mapping/MappedEventSubscriber.php#L277-L298

Is there a way we could modify the existing behaviour to allow the clock to be set dynamically or for the event subscriber to not retain the same instance of the adapters? I understand that the latter might not be desirable for performance reasons but at least allow the clock object to be updated at runtime maybe?

Thanks!

**Comment by Leobaillard** [comment]
Thanks a lot for your answer and suggestions!

Regarding your last comment, does it mean that if I have a setter for `createdAt` for instance and if I manually call it before persisting the entity, the listener won't set that value with a generated timestamp? If so, that seems ideal! If this is in the documentation, I'm sorry I missed it, but if not, it might be useful to include it!

If I did not understand that last part correctly, I think I will manage with the other solutions you provided. I will report back after testing and close this issue accordingly.

Thanks!

**Comment by mbabker** [comment]
> if I manually call it before persisting the entity, the listener won't set that value with a generated timestamp?

Yeah.  The `AbstractTrackingListener` should always respect a user-provided value (and it'd be a bug if it's not).  Pretty sure this isn't documented right now, but it can just be another thing I throw on the mile long TODO list as I try to rewrite it.

**Comment by Leobaillard** [comment]
Ok, it works as advertised! Sorry for not reading the code better.

Good luck for your backlog, I know the feeling!
