### ISSUE TITLE
Using Doctrine subscribers is deprecated since symfony/doctrine-bridge 6.3

### ISSUE THREAD

**Issue by shtumi** [doctrine-extensions/DoctrineExtensions#2890]
I got a lot of deprecation messages:

`Since symfony/doctrine-bridge 6.3: Registering "Gedmo\Tree\TreeListener" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] or #[AsDocumentListener] attribute.`

`Registering "Gedmo\Translatable\TranslatableListener" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] or #[AsDocumentListener] attribute.`

`Since symfony/doctrine-bridge 6.3: Registering "Gedmo\Timestampable\TimestampableListener" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] or #[AsDocumentListener] attribute.`

`Since symfony/doctrine-bridge 6.3: Registering "Gedmo\Sluggable\SluggableListener" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] or #[AsDocumentListener] attribute.`

`Since symfony/doctrine-bridge 6.3: Registering "Gedmo\Sortable\SortableListener" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] or #[AsDocumentListener] attribute.`

`Since symfony/doctrine-bridge 6.3: Registering "Gedmo\Loggable\LoggableListener" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] or #[AsDocumentListener] attribute.`

Does it make sense to transform event subscribers to event listeners?

**Comment by mbabker** [comment]
Are you using StofDoctrineExtensionsBundle or manually configuring the services?  If it's the former, update the bundle as it already addressed that.  If it's the latter, check your config against the documentation as that was somewhat recently updated to use the non-deprecated alternative.

**Comment by shtumi** [comment]
thanks.
found
