### ISSUE TITLE
Can't update other fields on translatable entity

### ISSUE THREAD

**Issue by zolakt** [doctrine-extensions/DoctrineExtensions#327]
Sorry for disturbing again, but I have been running from one problem to another with these extensions for some time now.
This is the latest and biggest one. I have been trying to come up with something for hours but with no luck.

Let say, you have this entity class: (letf out getters/setters)

``` php
namespace models;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * models\Book
 *
 * @ORM\Table(name="book")
 * @ORM\Entity(repositoryClass="models\Repositories\BookRepository")
 * @Gedmo\TranslationEntity(class="models\Translation\Book")
 */
class Book extends Base\BaseEntity
{
    /**
    * @var integer $id
    *
    * @ORM\Column(name="id", type="integer")
    * @ORM\Id
    * @ORM\GeneratedValue(strategy="IDENTITY")
    */
    protected $id;

    /**
    * @var string $name
    *
    * @Gedmo\Translatable
    * @ORM\Column(name="name", type="string")
    */
    protected $name;

    /**
    * @var string $image
    *
    * @ORM\Column(name="image", type="string")
    */
    protected $image;

    /**
    * @Gedmo\Locale
    * Used locale to override Translation listener`s locale
    * this is not a mapped field of entity metadata, just a simple property
    */
    protected $locale;

    public function setTranslatableLocale($locale)
    {
        $this->locale = $locale;
    }
}
```

When I try to do something like:

``` php
$book = \models\Book::getRepository()->find(1);
$book->setImage('some image');
Doctrine::em()->persist($book);
Doctrine::em()->flush();
```

it doesn't update. It fills the values, after persist they are still there, but on flush it doesn't save them to the DB.
If I create a new entity and save it, it works. So insert works, update does not.
Also if I set the name field, the translation in the other table gets updated, but other entity fields in the entity table don't change.
When I remove the @Gedmo\Translatable annotation, and run the same code, it works just fine.

I'm using the #af3e430 changeset version. Tried it with Doctrine 2.2.0 and 2.2.2, no difference

Here is my configuration file http://pastebin.com/4yM6wYbW . It is a wrapper for Kohana framework

Also, I'm using custom change notification policy, like described here http://readthedocs.org/docs/doctrine-orm/en/latest/cookbook/implementing-the-notify-changetracking-policy.html. Maybe it has got something to do with this. I have a feeling that the change isn't registered on the managed entity, so flush thinks it has nothing to do

**Comment by florianmarical** [comment]
@zolakt Thank you very much for your comment. I had the same problem for several hours.

However, I have only commented the line :  $ea->clearObjectChangeSet($uow, $oid); 

It works.

"doctrine/orm": "~2.2,>=2.2.3,<2.5",
"stof/doctrine-extensions-bundle": "^1.2"

Thanks !!
