### ISSUE TITLE
[branch 2.2.x] childrenHierarchy() doesn't translate

### ISSUE THREAD

**Issue by ma2thieu** [doctrine-extensions/DoctrineExtensions#369]
With a schema like that :

```
/**
 * @ORM\Table()
 * @ORM\Entity()
 * @Gedmo\Tree(type="nested")
 */
class Aaa {

    /**
     * @ORM\Column(name="name", type="string", length=255)
     * @Gedmo\Translatable
     */
    private $name;

    (...)

}
```

when I use `childrenHierarchy()` to retrieve nodes their `name` are not translated. (they are with `children()`)

**Comment by ryanesrapado** [comment]
> its because it uses array hydration query. you need to make [somethitng like that](https://github.com/l3pp4rd/gediminasm.org/blob/master/src/Gedmo/DemoBundle/Controller/CategoryController.php#L69) in order to get it translated.

Hi @l3pp4rd thanks for the hint "...it uses array hydration query..." but the link you added it is not working any more, have you another code link example? Thanks again!
