### ISSUE TITLE
Sluggable + Softdeleteable + Unique

### ISSUE THREAD

**Issue by umpirsky** [doctrine-extensions/DoctrineExtensions#449]
I have noticed problem when using sluggable in combination with softdeleteable.

When slug is unique:

```
<field name="slug" column="slug" type="string" unique="true">
    <gedmo:slug fields="name" unique="true" />
</field>
```

and softdeletable is configured like:

```
<field name="deletedAt" column="deleted_at" type="datetime" nullable="true" />
<gedmo:soft-deleteable field-name="deletedAt" />
```

and you insert row with some name, then delete it (soft), then try to insert row with same name again, it tries to insert row with same slug and unique constraint causes an error.

**Comment by Assem** [comment]
Hi,

Did you automated the call to the addManagedFilter function ?

Thks
