### ISSUE TITLE
Support for on-delete='CASCADE' with soft deletes

### ISSUE THREAD

**Issue by mbadolato** [doctrine-extensions/DoctrineExtensions#505]
When using soft deletes, and entity object is not actually being deleted, thus no cascades trigger down to associated objects.

My original email with @l3pp4rd  and @comfortablynumb:

> I'm using the soft delete feature, and its working well. In the relationship defined below, I have soft delete set up on both the Event entity (where this association is defined), as well as the associated entity, EventMetaDataValue. 
> 
> I'd like to include on-delete="CASCADE" so that the associated EventMetadataValue's deletedAt timestamp also gets updated, however this doesn't seem to trigger. Presumably this is because I'm not actually deleting the Event entity, since I'm using soft delete. 
> 
> My question is, is there a way to have that behavior take place (i.e., cascade the soft-delete down to the associated table)?  Scouring the net didn't lead me to anything useful, and your docs don't reference a situation like that. I was hoping there was a syntactical way to carry out this operation, and that I won't have to write a listener to take care of it.

``` xml
    <entity name="Cms\CoreBundle\Entity\Event" table="event">
         ...
        <many-to-many field="eventMetadataValues" target-entity="EventMetadataValue">
            <join-table name="event_metadata">
                <join-columns>
                    <join-column name="event_id" referenced-column-name="id" />
                </join-columns>
                <inverse-join-columns>
                    <join-column name="event_metadata_value_id" referenced-column-name="id" />
                </inverse-join-columns>
            </join-table>
        </many-to-many>
         ...
    </entity>
```

And Gustavo's response:

> You're right, since entities which are not explicitly removed from the entity manager don't trigger any events, they are not handled by softdeleteable. One way would be to use cascade delete. But, of course, this avoids the perfomance boost of using normal db cascade delete.
> 
> We could detect, however, an entity which is being deleted and, if it has a configuration in its join columns with cascade delete, we could softdelete its children.

**Comment by andrey-bondar** [comment]
+1

**Comment by joseandrespg** [comment]
+1

**Comment by liverbool** [comment]
:+1:

**Comment by broncha** [comment]
+1

**Comment by velanor** [comment]
+1

**Comment by respinoza** [comment]
+1

**Comment by prvijesh** [comment]
subscribe the event 'preSoftDelete'

**Comment by rufinus** [comment]
+1

**Comment by stephanvierkant** [comment]
This would be a great improvement!

Any update or work-around on this?

**Comment by Mopster** [comment]
+1

**Comment by ricardogama** [comment]
+1

**Comment by murilolobato** [comment]
+1

**Comment by puty** [comment]
+1

**Comment by glen-84** [comment]
@puty Please use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) now, instead of +1 comments.

**Comment by gpenverne** [comment]
:+1:

**Comment by RubenHarms** [comment]
see https://github.com/E-vence/SoftDeleteableListenerExtensionBundle

**Comment by gpenverne** [comment]
:+1:

**Comment by nurikabe** [comment]
@RubenHarms GitHub needs a "weeps for joy" reaction icon. Thank you!

**Comment by Adapik** [comment]
+1

**Comment by versh23** [comment]
+1

**Comment by ghanbari** [comment]
+1

**Comment by glnemeth** [comment]
+1

**Comment by funcphp** [comment]
+1 from 2018

**Comment by gustavodpont** [comment]
+1

**Comment by stephanvierkant** [comment]
@Adapik @gustavodpont @funcphp @glnemeth @ghanbari @versh23 @gpenverne 

I've removed your comments. Please use reactions instead of +1 comments.

**Comment by ersin-demirtas** [comment]
1+

**Comment by jelovac** [comment]
Hi,

Has any progress been made during the years regarding this missing feature? Is it still an issue in v3?

**Comment by AkenRoberts** [comment]
No progress that I'm aware of.

**Comment by asdfMaciej** [comment]
Has this issue been solved? The completed tag seems misleading, perhaps it should be reopened?
