### ISSUE TITLE
Sorting don't work correct if you give position for multiple entities

### ISSUE THREAD

**Issue by mavik** [doctrine-extensions/DoctrineExtensions#538]
I have:
## Name : Position

Item 1: 1
Item 2: 2
Item 3: 3
Item 4: 4
Item 5: 5
Item 6: 6
Item 7: 7

I set:
Item 1: 7
Item 2: 6
Item 3: 5
Item 4: 4
Item 5: 3
Item 6: 2
Item 7: 1

After Flush I have:
Item 5: 1
Item 6: 1
Item 7: 1
Item 3: 3
Item 4: 4
Item 2: 5
Item 1: 7

**Comment by Hartiikz** [comment]
Same problem,
i had to set multiple item and i get duplicated positions
Someone fixed this problem ?

**Comment by Padam87** [comment]
Are you using the master branch, or a release? There are a lot of fixes in the master branch. Could you try that? (The format has also changed, it is a bit of work to adapt)

**Comment by Hartiikz** [comment]
I'm using StofDoctrineExtensionsBundle. I suppose that he is not using the master branch and that can explain my problem

**Comment by Padam87** [comment]
We are using it with this hack:

"gedmo/doctrine-extensions": "dev-master as 2.5.x-dev",
"stof/doctrine-extensions-bundle": "~1.2.2",

**Comment by Hartiikz** [comment]
I use your hack for keep stof bundle. But always the same problem :/

**Comment by Padam87** [comment]
Then it seems like this issue hasn't been fixed yet.

**Comment by Hartiikz** [comment]
Think so. Thany you for the help :)

**Comment by Padam87** [comment]
I believe that the problem is caused by the sql updates. You could try flushing after each entity change...

$entity->setPosition($x);
$em->flush();

**Comment by Hartiikz** [comment]
It works ! Is very slow but it works for the moment ! i will try improve that for better performances 
Thank you !

**Comment by Padam87** [comment]
Np :). If you always set the position for every entity, you could ditch the listener completely.
