### ISSUE TITLE
Nested Set and Soft delete combination problem

### ISSUE THREAD

**Issue by zorang** [doctrine-extensions/DoctrineExtensions#554]
Hello, I tried to use Nested Set tree and Soft Delete extensions on the same Entity. But I saw that it produce problems. For example, if I delete (SoftDelete) some entity in the middle of the tree, other entity property values (lft, rgt, ...) will be properly updated, but the same properties of softly deleted entity will not be updated. This cause problem when I want to verify Tree structure:

$entityRepository->verify();

It returns errors.

So it looks like combining of Tree Extension and Soft Delete extension is not compatible. Maybe I am doing something wrong? Or there is some solution?

**Comment by patrickomeara** [comment]
I am hitting the same logic issue as you have outlined @caponica, in addition to this what if a parent that has a soft deleted child is moved elsewhere in the hierarchy, do the soft deleted children move as well?

I'm toying with the idea of leaving the `parent` intact but removing the `lft` and `rgt`. Has anyone come across a solution to this problem?

**Comment by l3pp4rd** [comment]
this would be too complex to implement a generic resolution, adding many options would also make it confusing. different implementations may want something different in their logic. I would recommend to have a custom softdeleting extension combined with nested set tree.

**Comment by caponica** [comment]
Nice necromancy :-)

In general, I think:
 - SoftDeleting a node should soft-delete its children too (and the children cannot be un-deleted unless the parent is first).
 - Un-deleting a node should not automatically undelete its children (but users can customise this easily enough)
 - if you move a node, all its children move (even the SoftDeleted ones)
 - SoftDeleted nodes should keep their lft and rgt values intact

But I understand why the custodians of the library think this is too complex. IIRC, my issue was that the default behaviour was broken (in all cases) so doesn't help anybody. If there was a sane default solution it would also provide example code for people that wanted to customise the behaviour - you wouldn't need to expose every possibility through _options_, just point people in the right direction through the existing code.

**Comment by l3pp4rd** [comment]
hi @caponica that make sense, unless someone is wanting to contribute. because I personally stopped developing with php 2 years ago. @Atlantic18 should have taken over the maintenance, but so far I do not see them contributing at all, hope that can be resolved someday.

**Comment by Rikijs** [comment]
Hello!

I think i may be hitting the same problem outlined in this issue. 

It seams that soft deletion works, yet undeleting node presents a problem - node is not restored in the correct place.

I am in a search of resolution to this problem. Is it still `not fixed` today or am i using `Gedmo tree` and `Gedmo soft deleteble` wrong? How can one undelete node in the correct posititon in the tree?

I aggre with @caponica [coment 1](https://github.com/Atlantic18/DoctrineExtensions/issues/554#issuecomment-28247240) and [comment 2](https://github.com/Atlantic18/DoctrineExtensions/issues/554#issuecomment-253187441)
Is said behaviour not implemented yet?

**Comment by AkenRoberts** [comment]
@Rikijs This has not been fixed, and likely won't any time soon.

Tree and Soft Deletable simply weren't designed to work flawlessly together in the first place, even though they're both available in this same package. And with the currently level of maintenance (basically keeping the lights on, no real advancement), it's unlikely to be addressed any time soon.

We're always open to pull requests if you are interested in helping tackle this issue. Or, check out [doctrine-extensions](https://github.com/doctrine-extensions/doctrine-extensions) where we're trying to put together a modern version of these packages.

**Comment by Rikijs** [comment]
@AkenRoberts Thank you for status update on this problem.

**Comment by stipic** [comment]
Soft Delete and TREE in combination makes me alot of headaches. Hope will be fixed soon

I'll try to get into the code
