### ISSUE TITLE
Turn off Softdelete filter for specific onetomany/manytoone relations?

### ISSUE THREAD

**Issue by oscargala** [doctrine-extensions/DoctrineExtensions#555]
Hi,

I have a system where I have a Client entity and a Form entity. Every client can have multiple filled out forms.

I use the softdelete function on both entities.

Now when I have a page where I want to list all the clients with their filled out forms I do not want to see the deleted clients (filter should be on), but I would like to see the filled out forms, even if they are deleted using softdelete (filter should be off).  

However, I generate the list of filledout forms in twig using

```
{% for form  in client.getForms %}
```

I can disable the softdelete filter in the Controller by using 

```
$em->getFilters()->disable('softdeleteable');
```

But then I will also see all the deleted clients, which I don't want. 

Is there a way to add a "disable filter" annotation in the entity?

Something like:

```
    /**
     * @var $forms
     * @Gedmo\SoftDeleteable(enabled=false)
     * @ORM\OneToMany(targetEntity="Form", mappedBy="client")
     */
    private $forms;
```

**Comment by Glideh** [comment]
In @oscargala's case (for guys searching) he can still disable the filter for a given entity:

```php
$em->getFilters()->getFilter('softdeleteable')->disableForEntity(Form::class);
```

**Comment by zaiddabaeen** [comment]
Reference to @Glideh 's comment:
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/SoftDeleteable/Filter/SoftDeleteableFilter.php#L72
