### ISSUE TITLE
Translatable - Remove translation

### ISSUE THREAD

**Issue by xmateos** [doctrine-extensions/DoctrineExtensions#684]
Hey,

I´m retrieving translation for an entity as it follows:
    $repository->findTranslations($myEntity);

I works fine, and I can see all translatable columns for that entity in an array, as it follows:
    array (size=2)
      'de' => 
        array (size=2)
          'title' => string 'German title' (length=12)
          'description' => string '' (length=0)
      'en' => 
        array (size=2)
          'title' => string 'English title' (length=13)
          'description' => string 'Here is the description 2' (length=25)

As you can see, german description is not set, hence I want to remove it.
Is there a way so I can delete just the german description? Or even the whole german array?

Thanks & Regards,

**Comment by JPernerstorfer** [comment]
Hi @l3pp4rd , is there any update on this? Just in case it has already been developed.
