### ISSUE TITLE
[Uploadable] Consider introducing FileHandler

### ISSUE THREAD

**Issue by marcospassos** [doctrine-extensions/DoctrineExtensions#705]
Would be nice the possibility of choose the file handler desirable. For example, we use KnpLabs/Gaufrette for filesystem abstraction and today is not possible use with `Uploadable` once all file handling logic is hardcoded in `UploadableListeneer`.

My suggestion is introducing a FileHandler interface and the `handler` mapping. If any handler is specified, then `SimpleFileHandler` is used. 

``` php
interface FileHandler
{
    public function remove($filePath);
    public function rename($source, $dest);
    public function move($source, $dest, $isUploadedFile = true);
}
```

Annotation mapping:

``` php
/**
 * @ORM\Entity
 * @Gedmo\Uploadable(handler="MyCustomFileHandler")
 */
class File
{
}
```

XML mapping:

``` php
<?xml version="1.0" encoding="UTF-8"?>

<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:gedmo="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping">

    <entity name="Entity\File" table="files">
        <gedmo:uploadable handler="MyCustomFileHandler" />
    </entity>

</doctrine-mapping>
```

This is a subtle improvement that will allow much more flexibility and seems easy to be implemented.

Considerations?

**Comment by stephanvierkant** [comment]
Looks fantastic!

**Comment by l3pp4rd** [comment]
is anyone up for this implementation? master branch may have some incompatible changes, since next release will be 3.0.0. I personally haven't used php in a while, which makes it hard to maintain this library well.
