### ISSUE TITLE
[Sluggable] temporary disable slug generation

### ISSUE THREAD

**Issue by birko** [doctrine-extensions/DoctrineExtensions#785]
Hello.

Is there in Sluggable extension a way to disable slug generation?
I want to implement a external link feature in my Category Entity.
Default behavior is to generate slug from category title but if he user checks the external option he could write there custom url like "http://google.com/..."

I hope there is a option to do it something like this.

``` php
 $slug = $entity->getSlug();
 $em->persist($entity);
 $em->flush();
 if($entity->isExternal())
 {
       /* 
       Code to mute listener
       */
       $entity->setSlug($slug);
       $em->persist($entity);
       $em->flush();
       /*
         Code to unmute listener
       */
 }
```

I know I could just make e extra field for that . but just wanted to know if there is this option to

**Comment by mdjaman** [comment]
Hello any updates on this? @birko Can you please share how did you resolve issue

**Comment by futuster** [comment]
Please, can you explain about handler to disable slug generation, if slug was setted directed.
