### ISSUE TITLE
Table 'ext_translations' doesn't exist

### ISSUE THREAD

**Issue by csaoh** [doctrine-extensions/DoctrineExtensions#790]
Hello there !

This is not a real issue, since I'm pretty sure it's all about me doing something wrong, but i still would like to get a heads-up about what it could be.

I'm trying to create a nested tree with translation handling. When I use the example as it given, everything works fine, but when I try to recreate it in a new application, I get this error, no matter whether I try an implementation using an extra translation class or without it:

``` bash
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ab_test.ext_translations' doesn't exist in /Users/andrey/nested-annotation/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php on line 47
```

I use a em.php file that's basically the same as in the examples but a little bit stripped off. The Category, CategoryTranslation and CategoryRepository classes are basically the sames as in the example.

Here is my test script:

``` php
<?php

use Doctrine\ORM\Query;

$em = include 'em.php';

$repository = $em->getRepository('Gedmo\Translatable\Entity\Translation');

$category = $em->getRepository('Entity\Category')->find(1);

$translations = $repository->findTranslations($category);

var_dump($translations);
```

and here is my composer.json file:

``` json
{
    "name": "nested-annotation",
    "require": {
        "php"                              : ">=5.3.3",
        "doctrine/orm"                     : "~2.3.0",
        "doctrine/common"                  : ">=2.2,<2.5-dev",
        "gedmo/doctrine-extensions"        : "~2.3.0",
    }
}
```

I thought maybe I'm missing something somewhere ?..

Sorry for this pretty vague description, but I don't really know where to look at the moment...

Thank you for your attention !

**Comment by ThomasH13090** [comment]
Hello, 

I have the same problem, but I can't figure out where to put your "Gedmo\DoctrineExtensions::registerMappingIntoDriverChainORM(......"

Thanks ahead  !
