### ISSUE TITLE
[Loggable] Loggable does not support composite identifiers.. any way around that?

### ISSUE THREAD

**Issue by ioleo** [doctrine-extensions/DoctrineExtensions#798]
In my database I have:
- Superclass USER
- sub-class AGENT

Each user has an `@ORM/Id` field `id`. But AGENT should have also another identifier field - `agent_no`.

The `agent_no` has to be marked with `@ORM/Id` to be able to use it in `@ORM/JoinColumn` [see Doctrine doc](http://docs.doctrine-project.org/en/latest/reference/annotations-reference.html#annref-joincolumn).

But this makes AGENT class have two `@ORM\Id` marked fields, and leads to an error: 

``` bash
[Gedmo\Exception\InvalidMappingException]                                        
  Loggable does not support composite identifiers in class - Acme\UserBund  
  le\Entity\Agent
```

Am I forced to drop loggable on users (which I really wouldn't like) or is there any way around that?

**Comment by adioe3** [comment]
Related to #1124 ?
