### ISSUE TITLE
[Translatable] Is it possible to get all locales ?

### ISSUE THREAD

**Issue by KeGaWeb** [doctrine-extensions/DoctrineExtensions#816]
Hi,

As I'm asking in the object, is it possible to get all locales ?

Let's say you have a table which contain movies, their productor and their name.
The name'll be translated in many languages, but not the productor who don't need to.
If i want to know all the locale in which the movie's name is translated, can I get it easily ?

Hope I'm clear...

**Comment by zoomtronic** [comment]
Anyone knows how to get this array with the fallback fields ?
I set to true this param `persist_default_translation: true` but i already have data before. 
So, its only giving me an array of all the locales and some default translations i've just persisted..
