### ISSUE TITLE
[Translatable] MySQL index not used on translation table

### ISSUE THREAD

**Issue by mnapoli** [doctrine-extensions/DoctrineExtensions#860]
When the Query Hint makes the Join with the translation table:

``` sql
... AND ext_translations.foreign_key = my_entity.id
```

Here `ext_translations.foreign_key` is a VARCHAR column, and `my_entity.id` is an INT column.

Because of that, MySQL will not use the index! It ends up to scan almost the whole table.

Just try something like this:

``` sql
-- Uses the index
... AND ext_translations.foreign_key = '123'
-- Doesn't use the index
... AND ext_translations.foreign_key = 123
```

We have been able to make the query use the index by casting `my_entity.id` to string, but it's not very stable because if the MySQL connection encoding is not the same as the table, then it produces an error (for example we had the problem with utf8_unicode_ci ≠ utf8_general_ci) -> very hard to debug.

Do you have an idea to solve this?
- cast INT columns to string?
- create 2 `foreign_key` columns: one VARCHAR and one INT? (doesn't seem like a good idea)?
- switch `foreign_key` to an INT column, but then Translatable wouldn't be compatible with string ids?
- create personal translation entities? Would it work? It's not an ideal solution though because most of Entities have numeric ids, so in short you'd have to use only personal translations...

I've seen your work in #764, it's very impressive. Would that problem be solved in 3.0?

Thanks for the feedback!

**Comment by zloyrusskiy** [comment]
Same problem, in table with ~2M rows.

There is no stable v3.0 version.

Please add casting of foreignKey to string on php side, and solve this problem.

**Comment by l3pp4rd** [comment]
you can override mapping for protected properties and make it explicitly an integer. This translatable extension is not meant to be performance wise. It is meant for an easy multilingual startup. The personal translation approach is a little better, but still it holds only on field per relation. For use cases with 2m rows and more I would advice to have custom implementations.

**Comment by zloyrusskiy** [comment]
[custom Translation Entity](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#translation-entity) and overriding foreignKey with another type helps me.
