### ISSUE TITLE
Form "Personal Translation"

### ISSUE THREAD

**Issue by pdias** [doctrine-extensions/DoctrineExtensions#888]
Hello,

I'm trying to use the "Personal Translation" in a normal form (no Sonata) ... created everything as indicated in https://github.com/l3pp4rd/DoctrineExtensions/blob/master/doc/translatable.md#personal-translations.

I add can add the code indicated in https://gist.github.com/2437078 .
`(/Form/TranslatedFieldType.php;  /Form/EventListener/addTranslatedFieldSubscriber.php; /Resources/services.yml)`

I have this error:

```
The options "field", "personal_translation" do not exist.
```

I do not know if what I'm trying to do is possible or what am I doing wrong.

I use Symfony 2.3.6.

Thanks,

Paulo

**Comment by velikanov** [comment]
@pdias, your switch doesn't solve the issue btw
