### ISSUE TITLE
[Uploadable]  Remove file does not work.

### ISSUE THREAD

**Issue by imulot** [doctrine-extensions/DoctrineExtensions#963]
Hi, 

I have an "K" entity  with OneToOne relationship with Image Entity. (@Uploadable).
Upload work fine. But when I try to delete my entity, associated image entity is correctly remove from database but image file stays in my directory. 
Why file is not removed automatically ?

In K entity : /*\*                                                                                                                                          \* @ORM\OneToOne(targetEntity="Image",cascade={"persist", "remove"})  
     */
    private $logo;

Upload code :  
$uploadableManager = $this->get('stof_doctrine_extensions.uploadable.manager');
           $logo=new Image;
           $logo->setTitle($k->getName().' logo');
           $k->setLogo($logo);
           $uploadableManager->markEntityToUpload($k->getLogo(), $k->getFile());
           $em->persist($k);
           $em->flush();

Remove code
   $em = $this->getDoctrine()->getManager();
   $em->remove($k);
   $em->flush();

Help appreciate.
Thanks.
David.

**Comment by jeremyjumeau** [comment]
Is someone working on that?

**Comment by l3pp4rd** [comment]
the uploadable maintainer has not recently been active, so guess its up to contributions. I personally use custom uploadable solutions in all cases.

**Comment by jeremyjumeau** [comment]
Ok thanks for your feedback, for the time being I'll use @imulot's trick to force hydratation.

**Comment by imulot** [comment]
Hi jeremy,

I choose to use my own custom
solution too. 
uploadable is too buggy at this time and developpement of this extension  seems stuck. 

imulot.

**Comment by l3pp4rd** [comment]
will need to update documentation to warn about uploadable
